// Prototype aggregates only. Calendar integration must supply stable person IDs
// and replace cancelled/edited source records; no production connection exists.
function attendanceSummary(site){
 const people=new Map(),days=new Map(),seen=new Set();
 for(const r of visitRecords(site).filter(r=>r.date<=jpToday())){
  const key=r.personId||JSON.stringify([r.name.trim(),(r.affiliation||'').trim()]);
  const unique=JSON.stringify([key,r.date]);if(seen.has(unique))continue;seen.add(unique);
  if(!people.has(key))people.set(key,{name:r.name,affiliation:r.affiliation,last:r.date,count:0});
  const p=people.get(key);p.count++;if(r.date>p.last)p.last=r.date;
  if(!days.has(r.date))days.set(r.date,[]);days.get(r.date).push(r);
 }
 return {total:seen.size,people:[...people.values()].sort((a,b)=>b.last.localeCompare(a.last)),days:[...days.entries()].sort((a,b)=>b[0].localeCompare(a[0]))};
}
overview=function(s){let box=document.createElement('div');box.innerHTML=previousOverview(s);let panel=box.querySelector('.panel'),address=box.querySelector('.map-address');if(s.mapLink&&safePlaceUrl(s.mapLink)){if(address)address.href=safePlaceUrl(s.mapLink);else panel.insertAdjacentHTML('beforeend',`<a class="map-address" href="${esc(safePlaceUrl(s.mapLink))}" target="_blank" rel="noopener noreferrer">現場の位置情報を開く ↗</a>`)}panel.querySelector('.section-head').insertAdjacentHTML('afterend',`<button class="text-action" style="margin-bottom:18px" onclick="siteForm(${s.id})">＋ 現場の住所・位置情報を登録／編集</button>`);return box.innerHTML};
visitsPanel=function(s,full=false){let a=attendanceSummary(s.id),sales=Number(s.sales)||0;return `<section class="panel"><div class="section-head"><h2>この現場に来た人</h2><span class="visit-source">連携前・試作データ</span></div><div class="row between" style="padding:18px 0;border-bottom:1px solid var(--line)"><div><label>累計人工（延べ人数）</label><strong style="font-size:34px;font-weight:500">${a.total}</strong> <small>人工</small></div><div class="meta">実人数 ${a.people.length}名<br>同じ人が5日来場 → 5人工</div></div><div class="row between" style="padding:16px 0"><div><span class="meta">売上金額</span><br><b>${sales?sales.toLocaleString('ja-JP')+'円':'未設定'}</b></div><div><span class="meta">1人工あたりの売上</span><br><b>${sales&&a.total?Math.round(sales/a.total).toLocaleString('ja-JP')+'円':'—'}</b></div><button class="text-action" onclick="salesForm(${s.id})">売上を設定</button></div>${a.people.map(p=>`<div class="visit-line"><span class="avatar">${esc(p.name.slice(0,1))}</span><div style="flex:1"><b>${esc(p.name)}</b><small>${esc(p.affiliation||'所属未登録')}<br>最終入場 ${esc(p.last)} ／ ${p.count}人工</small></div></div>`).join('')||'<p>来場履歴はまだありません。</p>'}<details ${full?'open':''} style="margin-top:18px"><summary style="cursor:pointer;font-size:12px;color:#345a8a">日別の動きを見る（${a.days.length}日）</summary>${a.days.map(([day,rs])=>`<div class="item"><b style="font-size:12px">${day}　${rs.length}人工</b>${rs.map(r=>`<p>${esc(r.name)} <small>${esc(r.affiliation||'')}</small><br><span class="meta">${esc(r.work||'')}</span></p>`).join('')}</div>`).join('')}</details><p class="hint">配置カレンダーから自動で集計する設計です。現在は未接続のため試作の履歴を集計しています。未来の日付を除き、同じ人・同じ現場・同じ日は1人工として計算します。半日などの換算は未対応です。</p></section>`};
function salesForm(id){let s=state.sites.find(s=>s.id===id);show(`<h2>現場の売上金額</h2><form id="salesForm"><label>売上金額（円）</label><input name="sales" type="number" min="0" step="1" required value="${esc(s.sales||'')}" placeholder="1000000"><p class="hint">売上 ÷ 累計人工で計算します。利益ではありません。</p>${foot()}</form>`);$('salesForm').onsubmit=e=>{e.preventDefault();s.sales=Number(e.target.sales.value);save();closeModal();render()}};
render();
