(function(){
'use strict';
const memory=new Map(),pending=new Map();let generation=0;
const escape=SiteChatCore.escape;
const actor=()=>window.portalSession?.connected()?JSON.stringify([portalSession.identity()?.kind||'employee',portalSession.identity()?.code||'']):'';
async function load(sid){
 const key=sitePortalSiteKey(sid),owner=actor(),ticket=generation;if(!owner)return;const existing=pending.get(key);if(existing?.owner===owner&&existing.ticket===ticket)return existing.job;
 const marker={owner,ticket};marker.job=Promise.resolve().then(async()=>{try{const rows=await siteSharedStore.list(key,'チャット');if(generation!==ticket||actor()!==owner)return;memory.set(key,{rows,error:''})}catch(e){if(generation!==ticket||actor()!==owner)return;memory.set(key,{rows:[],error:e.message})}finally{if(pending.get(key)===marker)pending.delete(key);if(generation===ticket&&actor()===owner)await mountHistory(sid)}});pending.set(key,marker);return marker.job;
}
function authorName(r){const me=portalSession.identity();return me&&r.created_by===((me.kind||'employee')+':'+me.code)&&me.name?me.name:String(r.created_by||'').replace(/^employee:/,'社員ID：').replace(/^worker:/,'外注ID：')}
function validDate(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d}
function entries(value){return (value.rows||[]).filter(r=>!r.deleted).slice().sort((a,b)=>String(b.payload?.date||b.created_at||'').slice(0,10).localeCompare(String(a.payload?.date||a.created_at||'').slice(0,10))||String(b.created_at).localeCompare(String(a.created_at))).map(r=>`<article class="chat-entry"><div class="chat-entry-body"><div class="chat-entry-meta"><strong>${escape(authorName(r))}</strong><time>連絡日 ${escape(validDate(r.payload?.date||'')?r.payload.date:r.created_at?new Date(r.created_at).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}):'不明')}</time><small>送信 ${escape(r.created_at?new Date(r.created_at).toLocaleString('ja-JP'):'')}</small></div><p>${escape(r.payload?.message||'')}</p></div></article>`).join('')||'<p>まだ連絡はありません。</p>'}
async function mountHistory(sid){const section=document.querySelector('.shared-chat');if(!section||section.dataset.site!==String(sid))return;const owner=actor(),ticket=generation,key=sitePortalSiteKey(sid),value=memory.get(key);section.querySelector('.chat-stream').innerHTML=value?entries(value):'<p>読み込み中…</p>';section.querySelector('[data-load-error]').textContent=value?.error||'';section.querySelector('[data-chat-count]').textContent=value&&!value.error?(value.rows||[]).filter(r=>!r.deleted).length+' 件':'— 件';
 try{const queued=await siteSharedStore.pending();if(!section.isConnected||ticket!==generation||actor()!==owner)return;const ops=queued.filter(op=>op.value.p_site_key===key&&op.value.p_section==='チャット');section.querySelector('[data-chat-pending]').innerHTML=ops.map(op=>`<div class="notice"><strong>送信結果を確認できていない連絡</strong><p>連絡日 ${escape(op.value.p_payload.date||'未設定')}<br>${escape(op.value.p_payload.message||'')}</p><button type="button" class="secondary" data-chat-retry="${escape(op.key)}">この連絡の送信を確認・再試行</button></div>`).join('')}catch(e){if(section.isConnected&&ticket===generation&&actor()===owner)section.querySelector('[data-load-error]').textContent=e.message}
}
window.renderSiteChat=function(sid){const key=sitePortalSiteKey(sid);queueMicrotask(()=>load(sid));return `<section class="site-chat shared-chat" data-site="${escape(sid)}"><div class="row between"><div><span class="chat-eyebrow">SITE COMMUNICATION</span><h2>現場の連絡</h2></div><span class="chat-count" data-chat-count>— 件</span><button type="button" class="secondary" data-chat-refresh>更新</button></div><p>この現場のチャットを閲覧できるメンバーと共有します。</p><p data-load-error role="alert"></p><form class="shared-chat-form" data-site="${escape(sid)}"><div class="chat-fields"><label>記入者<input name="authorDisplay" readonly value="${escape(portalSession.identity()?.name||portalSession.identity()?.code||'ログイン確認中')}"></label><label>連絡日<input type="date" name="dateDisplay" required value="${escape(SiteChatCore.todayJST())}"></label></div><label>連絡内容<textarea name="message" required maxlength="2000" rows="3"></textarea></label><p class="chat-feedback" role="status"></p><button type="submit" class="primary" ${actor()?'':'disabled'}>送信する</button>${actor()?'':'<p>ポータルのログインを確認しています。</p>'}</form><div data-chat-pending></div><div class="chat-stream">${memory.has(key)?entries(memory.get(key)):'<p>読み込み中…</p>'}</div></section>`};
document.addEventListener('click',async e=>{if(e.target.matches('[data-chat-refresh]'))load(e.target.closest('.shared-chat').dataset.site);if(e.target.matches('[data-chat-retry]')){const b=e.target,section=b.closest('.shared-chat'),owner=actor(),ticket=generation;const f=section.querySelector('form');b.disabled=true;try{const queued=(await siteSharedStore.pending()).find(op=>op.key===b.dataset.chatRetry);await siteSharedStore.retry(b.dataset.chatRetry);if(!section.isConnected||ticket!==generation||actor()!==owner)return;const key=siteSharedStore.key(sitePortalSiteKey(section.dataset.site),'チャット',f.dataset.recordId);if(key===b.dataset.chatRetry){if(f.elements.message.value.trim()===queued?.value.p_payload.message&&f.elements.dateDisplay.value===(queued?.value.p_payload.date||f.elements.dateDisplay.value))f.elements.message.value="";delete f.dataset.recordId;f.querySelector('.chat-feedback').textContent='送信結果を確認しました。';}await load(section.dataset.site)}catch(err){if(section.isConnected&&ticket===generation&&actor()===owner)f.querySelector('.chat-feedback').textContent=err.message}finally{if(b.isConnected)b.disabled=false}}});
document.addEventListener('submit',async e=>{
 const f=e.target;if(!f.matches('.shared-chat-form'))return;e.preventDefault();const button=f.querySelector('[type=submit]'),feedback=f.querySelector('.chat-feedback');if(button.disabled)return;
 const owner=actor(),ticket=generation,message=f.elements.message.value.trim();if(!message)return;const date=f.elements.dateDisplay.value;if(!validDate(date)){feedback.textContent='有効な連絡日を選択してください';return}if(message.length>2000){feedback.textContent='連絡内容は2000文字以内で入力してください';return}button.disabled=true;f.dataset.recordId||=crypto.randomUUID();
 try{await siteSharedStore.save(sitePortalSiteKey(f.dataset.site),'チャット',f.dataset.recordId,{message,date},{revision:0});if(!f.isConnected||ticket!==generation||actor()!==owner)return;f.elements.message.value='';delete f.dataset.recordId;feedback.textContent='送信しました。';await load(f.dataset.site)}
 catch(err){if(f.isConnected&&ticket===generation&&actor()===owner){feedback.textContent=err.message+' 入力は残っています。';await mountHistory(f.dataset.site)}}
 finally{if(f.isConnected&&ticket===generation&&actor()===owner)button.disabled=!actor()}
});
window.addEventListener('portal-session-ready',()=>{generation++;memory.clear();pending.clear();const s=document.querySelector('.shared-chat');if(s){s.querySelector('.chat-stream').replaceChildren();s.querySelector('[data-chat-pending]').replaceChildren();s.querySelector('[data-load-error]').textContent='';const f=s.querySelector('form');f.elements.authorDisplay.value=portalSession.identity()?.name||portalSession.identity()?.code||'ログイン確認中';f.elements.dateDisplay.value=SiteChatCore.todayJST();s.querySelector('[data-chat-count]').textContent='— 件';f.elements.message.value='';f.querySelector('.chat-feedback').textContent='';f.querySelector('button').disabled=!actor();delete f.dataset.recordId;if(actor())load(s.dataset.site)}});
window.addEventListener('DOMContentLoaded',()=>{if(typeof window.renderSiteChat==='function'&&window.siteSharedStore)window.appSharedFeatures={...window.appSharedFeatures,'チャット':true}});
})();

