(function(){'use strict';
let generation=0,cache=new Map(),seen=new Set(),search='';
const who=()=>{const a=window.portalSession?.identity();return portalSession?.connected()&&a?.code?JSON.stringify([a.kind||'employee',a.code]):''};
const valid=(owner,ticket)=>owner&&who()===owner&&generation===ticket;
const area=()=>page==='allTasks'||(page==='detail'&&tab==='タスク');
function clearLegacyCounts(){const nav=document.querySelector('[data-work=tasks]');if(nav)nav.textContent='☑　タスク一覧';for(const card of document.querySelectorAll('.overview-stat'))if(card.querySelector('label')?.textContent.includes('タスク')){card.querySelector('strong').textContent='—';const small=card.querySelector('small');if(small)small.textContent='共有一覧で確認';}for(const b of document.querySelectorAll('#app button[onclick]'))if(b.getAttribute('onclick').includes('タスク')&&b.textContent.includes('未完了'))b.textContent='共有タスクを開く';}
function shell(){if(!area())return;const tabs=document.querySelector('#app .tabs');if(page==='detail'&&tabs){while(tabs.nextSibling)tabs.nextSibling.remove();tabs.insertAdjacentHTML('afterend','<section class="panel" id="cloudTasks"><p>共有タスクを確認中…</p></section>')}else $('app').innerHTML='<section class="panel" id="cloudTasks"><h1>全現場のタスク</h1><p>共有タスクを確認中…</p></section>';const nav=document.querySelector('[data-work=tasks]');if(nav)nav.textContent='☑　タスク一覧';}
async function load(){const box=$('cloudTasks');if(!box)return;const owner=who(),ticket=generation;if(!owner){box.innerHTML='<p>ログイン後に、閲覧を許可された現場のタスクを表示します。</p>';return}try{
 let sites=[];if(page==='detail'){const s=state.sites.find(x=>String(x.id)===String(siteId));sites=[{site_key:sitePortalSiteKey(siteId),name:s?.name||'現場'}]}else{let cursor='';for(let n=0;n<100;n++){const rows=await portalSession.call('sharedSites',{p_after_key:cursor});if(!valid(owner,ticket)||!box.isConnected)return;if(!Array.isArray(rows))throw Error('現場一覧を取得できません');sites.push(...rows);if(rows.length<100)break;const next=rows.at(-1).site_key;if(next<=cursor)throw Error('現場の読込位置が正しくありません');cursor=next;if(n===99)throw Error('対象現場が多すぎます')}}
 if(page==='allTasks')sites=sites.filter(s=>s.sections?.includes('タスク'));
 const queued=await siteSharedStore.pending();if(!valid(owner,ticket)||!box.isConnected)return;const result=[];for(const s of sites){try{const rows=await siteSharedStore.list(s.site_key,'タスク');if(!valid(owner,ticket)||!box.isConnected)return;const pending=queued.filter(o=>o.value.p_site_key===s.site_key&&o.value.p_section==='タスク').map(o=>({id:o.value.p_id,payload:o.value.p_payload,revision:o.value.p_expected_revision,_pending:true}));const entry={...s,rows:[...rows.filter(r=>!pending.some(p=>p.id===r.id)),...pending],access:siteSharedStore.access(s.site_key,'タスク')};cache.set(s.site_key,entry);result.push(entry)}catch(e){if(!valid(owner,ticket)||!box.isConnected)return;cache.delete(s.site_key);result.push({...s,rows:[],error:e.message})}}
 if(!valid(owner,ticket)||!box.isConnected)return;draw(box,result,owner,ticket);
 }catch(e){if(valid(owner,ticket)&&box.isConnected)box.innerHTML='<p role="alert">'+esc(e.message)+'</p><button data-task-reload>もう一度読み込む</button>'}}
function draw(box,sites,owner,ticket){const heading=page==='allTasks'?'全現場のタスク':'現場のタスク';box.innerHTML='<h2>'+heading+'</h2><button class="secondary" data-task-reload>最新の内容を読み込む</button><input data-task-search placeholder="現場名・件名で検索" value="'+esc(search)+'"><div data-task-list></div>';const list=box.querySelector('[data-task-list]');const paint=()=>{list.innerHTML=sites.filter(s=>page!=='allTasks'||s.error||s.rows.some(r=>(s.name+' '+(r.payload.title||'')).includes(search))).map(s=>'<section><h3>'+esc(s.name)+'</h3>'+(s.error?'<p role="alert">'+esc(s.error)+'</p>':(s.access?.manage?'<button class="primary" data-task-new="'+esc(s.site_key)+'">＋ タスク</button>':'')+s.rows.filter(r=>(s.name+' '+r.payload.title).includes(search)).map(r=>'<div class="item">'+(page==='detail'?'<label><input type="checkbox" data-task-toggle="'+esc(r.id)+'" data-task-site="'+esc(s.site_key)+'" '+(r.payload.done?'checked ':'')+(!s.access?.manage||r._pending?'disabled':'')+'> 完了</label>':'')+'<button class="work-item" data-task-open="'+esc(r.id)+'" data-task-site="'+esc(s.site_key)+'"><strong>'+esc(r.payload.title||'名称未入力')+'</strong><p>'+(r._pending?'送信結果未確認 ／ ':'')+(r.payload.done?'完了':'未完了')+(!seen.has(s.site_key+':'+r.id+':'+r.revision)?' ／ 未確認':'')+'</p></button><p data-task-inline-status role="status"></p></div>').join('')+(!s.rows.length?'<p>タスクはまだありません。</p>':''))+'</section>').join('')||(search?'<p>検索条件に一致するタスクはありません。</p>':'<p>タスクはまだありません。各現場の画面から登録できます。</p>')};paint();box.querySelector('[data-task-search]').oninput=e=>{search=e.target.value;paint()};}
function editor(key,row){const s=cache.get(key),owner=who(),ticket=generation;if(!s||!owner)return;const id=row?.id||crypto.randomUUID();let revision=Number(row?.revision||0),busy=false;show('<h2>'+esc(s.name)+'のタスク</h2><form id="cloudTaskForm"><label>タスク名<input name="title" maxlength="2000" required value="'+esc(row?.payload.title||'')+'" '+(!s.access?.manage?'readonly':'')+'></label><label><input type="checkbox" name="done" '+(row?.payload.done?'checked':'')+' '+(!s.access?.manage?'disabled':'')+'> 完了</label><p data-task-feedback role="status"></p><div class="modalfoot"><button type="button" data-task-close>戻る</button>'+(s.access?.manage?'<button class="primary" type="submit">共有先に保存する</button><button type="button" data-task-compare hidden>最新の内容と比較</button>':'')+'</div><div data-task-comparison></div></form>');const f=$('cloudTaskForm');f.dataset.owner=owner;const alive=()=>f.isConnected&&valid(owner,ticket),feedback=f.querySelector('[data-task-feedback]'),compare=f.querySelector('[data-task-compare]'),comparison=f.querySelector('[data-task-comparison]');if(row)seen.add(key+':'+id+':'+revision);f.querySelector('[data-task-close]').onclick=()=>{closeModal();if(area()){shell();load()}};if(!s.access?.manage)return;
 const value=()=>({title:f.elements.title.value.trim(),done:f.elements.done.checked}),opKey=siteSharedStore.key(key,'タスク',id);
 const lock=v=>{busy=v;f.querySelectorAll('input,button').forEach(x=>x.disabled=v)};
 f.onsubmit=async e=>{e.preventDefault();if(busy)return;const input=value();if(!input.title)return;lock(true);feedback.textContent='保存中…';try{const r=await siteSharedStore.save(key,'タスク',id,input,{revision});if(!alive())return;revision=Number(r.revision);feedback.textContent='共有先に保存しました';compare.hidden=true;comparison.replaceChildren();}catch(e){if(alive()){feedback.textContent=e.message+' 入力はこの画面に残っています。';compare.hidden=false}}finally{if(alive())lock(false)}};
 compare.onclick=async()=>{if(busy)return;lock(true);comparison.replaceChildren();try{const rows=await siteSharedStore.list(key,'タスク'),op=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;const latest=rows.find(x=>x.id===id),nextRevision=Number(latest?.revision||0),input=value(),requestId=op?.requestId;comparison.innerHTML='<h3>保存済みの最新版</h3><p>'+esc(latest?.payload.title||'記録なし')+' ／ '+(latest?.payload.done?'完了':'未完了')+'</p><h3>今回の入力</h3><p>'+esc(input.title)+' ／ '+(input.done?'完了':'未完了')+'</p><button type="button" data-task-resave>この入力で保存し直す</button>';comparison.querySelector('button').onclick=async()=>{if(busy||!alive())return;if(JSON.stringify(value())!==JSON.stringify(input)){feedback.textContent='入力が変わりました。もう一度比較してください。';comparison.replaceChildren();return}lock(true);let handed=false;try{const now=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;if((now?.requestId||null)!==(requestId||null))throw Error('未送信記録が変わりました');if(requestId)await siteSharedStore.resolvePending(opKey,requestId);if(!alive())return;revision=nextRevision;comparison.replaceChildren();lock(false);handed=true;f.requestSubmit()}catch(e){if(alive())feedback.textContent=e.message+' もう一度比較してください。'}finally{if(!handed&&alive())lock(false)}}}catch(e){if(alive())feedback.textContent=e.message}finally{if(alive())lock(false)}};
}
document.addEventListener('change',async e=>{const input=e.target;if(!input.matches('[data-task-toggle]'))return;const owner=who(),ticket=generation,key=input.dataset.taskSite,s=cache.get(key),row=s?.rows.find(r=>r.id===input.dataset.taskToggle),status=input.closest('.item').querySelector('[data-task-inline-status]');if(!owner||!row||!s.access?.manage||row._pending)return;const done=input.checked;input.disabled=true;status.textContent='保存中…';try{await siteSharedStore.save(key,'タスク',row.id,{...row.payload,done},{revision:Number(row.revision||0)});if(valid(owner,ticket)&&input.isConnected){shell();load()}}catch(error){if(valid(owner,ticket)&&input.isConnected){input.checked=!!row.payload.done;status.textContent=error.message+' タスクを開いて送信結果と最新版を確認してください。';row._pending=true}}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-task-reload')){shell();load()}if(b.dataset.taskNew)editor(b.dataset.taskNew);if(b.dataset.taskOpen){const s=cache.get(b.dataset.taskSite);editor(b.dataset.taskSite,s?.rows.find(r=>r.id===b.dataset.taskOpen))}});
window.addEventListener('DOMContentLoaded',()=>{const old=render;render=function(){old();clearLegacyCounts();if(area()){shell();load()}};window.taskForm=()=>{const key=sitePortalSiteKey(siteId);if(cache.get(key)?.access?.manage)editor(key);else notify('この現場のタスク編集権限を確認してください')};clearLegacyCounts();if(area()){shell();load()}window.appSharedFeatures={...window.appSharedFeatures,'タスク':true,allTasks:true}});
window.addEventListener('portal-session-ready',()=>{generation++;cache.clear();seen.clear();search='';if($('cloudTaskForm'))closeModal();if(area()){shell();load()}const nav=document.querySelector('[data-work=tasks]');if(nav)nav.textContent='☑　タスク一覧'});
})();



