(function(){'use strict';let epoch=0,readVersion=0;const rows=new Map(),listReads=new Map(),urls=new Set();
const track=blob=>{const url=URL.createObjectURL(blob);urls.add(url);setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url)},60000);return url};
const guard=(owner,g)=>{if(owner!==identity()||g!==epoch)throw Error("ログインが変わりました")};
const identity=()=>portalSession.connected()?JSON.stringify(portalSession.identity()):'';
async function rpc(method,p){const a=portalSession.identity(),owner=identity(),g=epoch;if(!owner)throw Error('ログインを確認してください');const result=await portalSession.call(method,{p_actor_kind:a.kind||'employee',p_actor_code:a.code,...p});if(owner!==identity()||g!==epoch)throw Error('ログインが変わりました');return result}
function invalidateReads(){readVersion++;listReads.clear()}
function list(site){const owner=identity(),g=epoch,version=readVersion,k=JSON.stringify([owner,g,version,site]);if(!owner)return Promise.reject(Error('ログインを確認してください'));if(listReads.has(k))return listReads.get(k);const job=Promise.resolve().then(()=>{guard(owner,g);return loadList(site,version)}).finally(()=>{if(listReads.get(k)===job)listReads.delete(k)});listReads.set(k,job);return job}
async function loadList(site,version){const owner=identity(),g=epoch,result=[];let after=null;for(let i=0;i<100;i++){const r=await rpc('educationLibraryRead',{p_site_key:site,p_id:null,p_after_id:after});guard(owner,g);if(version!==readVersion)throw Error('教材が更新されました。読み直してください');if(!Array.isArray(r))throw Error('教材一覧を確認できません');result.push(...r);if(r.length<100){rows.set(site,result);return result}const next=r.at(-1).id;if(after&&next<=after)throw Error('読込位置が不正です');after=next}throw Error('教材が多すぎます')}
async function open(site,id){const owner=identity(),g=epoch;try{const r=(await rpc('educationLibraryRead',{p_site_key:site,p_id:id,p_after_id:null}))[0];if(!r?.document_base64)throw Error('教材の閲覧権限を確認してください');if(!['application/pdf','image/png','image/jpeg'].includes(r.mime))throw Error('教材形式を確認できません');const bytes=Uint8Array.from(atob(r.document_base64),c=>c.charCodeAt(0));if(owner!==identity()||g!==epoch)return;const url=track(new Blob([bytes],{type:r.mime}));const w=window.open(url,'_blank');if(!w){const a=document.createElement('a');a.href=url;a.download=r.title+'.'+(r.mime==='application/pdf'?'pdf':r.mime==='image/png'?'png':'jpg');a.click()}}catch(e){notify(e.message)}}
function form(){const owner=identity(),g=epoch,id=crypto.randomUUID(),sites=window.siteSharedProfilesSnapshot?.().rows||[];show('<h2>全社共通の教育教材を登録</h2><p>個人の署名・受講記録を含む書類は登録しないでください。選んだ現場の安全教育閲覧者だけが教材を開けます。</p><form id="companyEducationLibrary"><label>教材名<input name="title" required maxlength="200"></label><label>版<input name="version" required maxlength="100"></label><label>教材ファイル<input name="file" type="file" required accept=".pdf,.png,.jpg,.jpeg"></label><fieldset><legend>配布する現場</legend>'+sites.map(s=>'<label><input type="checkbox" name="site" value="'+esc(s.site_key)+'">'+esc(s.name||s.profile?.name)+'</label>').join('')+'</fieldset><p role="alert"></p><button type="button" onclick="closeModal()">戻る</button><button type="submit">登録する</button></form>');const f=$('companyEducationLibrary');let pending=null,busy=false;f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{if(owner!==identity()||g!==epoch)throw Error('ログインが変わりました');const file=f.elements.file.files[0];if(!file||file.size>10485760||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw Error('10MB以内のPDF・PNG・JPEGを選んでください');const buffer=await file.arrayBuffer();if(owner!==identity()||g!==epoch)throw Error('ログインが変わりました');let binary='';for(const b of new Uint8Array(buffer))binary+=String.fromCharCode(b);const p={p_id:id,p_title:f.elements.title.value.trim(),p_version:f.elements.version.value.trim(),p_mime:file.type,p_base64:btoa(binary),p_site_keys:[...f.querySelectorAll('[name=site]:checked')].map(x=>x.value),p_revision:0};if(pending&&JSON.stringify(pending)!==JSON.stringify(p))throw Error('前の送信と同じ内容で再試行してください');pending=p;await rpc('educationLibrarySave',p);invalidateReads();window.siteEducationShared?.invalidate?.();if(owner===identity()&&g===epoch&&f.isConnected){closeModal();render()}}catch(e){if(f.isConnected)f.querySelector('[role=alert]').textContent=e.message+' 入力は残しています。'}finally{busy=false}}}
async function assignment(id){const owner=identity(),g=epoch;try{const d=(await rpc('educationLibraryRead',{p_site_key:null,p_id:id,p_after_id:null}))[0];if(!d)throw Error('教材を確認できません');const sites=window.siteSharedProfilesSnapshot?.().rows||[];show('<h2>教材の配布先を変更</h2><form id="libraryAssignment">'+sites.map(x=>'<label><input type="checkbox" name="site" value="'+esc(x.site_key)+'" '+(d.site_keys.includes(x.site_key)?'checked':'')+'>'+esc(x.name||x.profile?.name)+'</label>').join('')+'<p role="alert"></p><button type="button" onclick="closeModal()">戻る</button><button type="submit">保存</button></form>');const f=$('libraryAssignment');let busy=false;f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{if(owner!==identity()||g!==epoch)throw Error('ログインが変わりました');await rpc('educationLibrarySave',{p_id:d.id,p_title:d.title,p_version:d.version,p_mime:d.mime,p_base64:d.document_base64,p_site_keys:[...f.querySelectorAll('[name=site]:checked')].map(x=>x.value),p_revision:d.revision});listReads.clear();window.siteEducationShared?.invalidate?.();if(f.isConnected){closeModal();render()}}catch(e){if(f.isConnected)f.querySelector('[role=alert]').textContent=e.message}finally{busy=false}}}catch(e){notify(e.message)}}
async function mount(){const global=page==='safetyLibrary',site=page==='detail'&&tab==='安全教育'?sitePortalSiteKey(siteId):null;if(!window.appGateCanMount?.(page,siteId,tab))return;if(!global&&!site||$('companyLibraryPanel'))return;const box=document.createElement('section');box.id='companyLibraryPanel';box.className='panel';box.innerHTML='<h2>共通の教育教材</h2><p>閲覧権限を確認中…</p>';if(global)$('app').replaceChildren(box);else $('app').append(box);try{const r=await list(site);if(!box.isConnected||!window.appGateCanMount?.(page,siteId,tab))return;box.innerHTML='<h2>共通の教育教材</h2>';if(global){const add=document.createElement('button');add.textContent='＋ 共通教材を登録';add.onclick=form;box.append(add)}for(const x of r){const b=document.createElement('button');b.textContent=x.title+' ／ '+x.version;b.onclick=()=>open(site,x.id);box.append(b);if(global){const edit=document.createElement('button');edit.textContent='配布する現場を変更';edit.onclick=()=>assignment(x.id);box.append(edit)}}if(!r.length)box.insertAdjacentHTML('beforeend','<p>この範囲に配布された共通教材はありません。</p>')}catch(e){if(box.isConnected)box.textContent=e.message}}
window.addEventListener('DOMContentLoaded',()=>{const previous=render;render=function(){previous();mount()};mount()});window.addEventListener('portal-session-ready',()=>{epoch++;listReads.clear();for(const u of urls)URL.revokeObjectURL(u);urls.clear();rows.clear();if($('companyEducationLibrary')||$('libraryAssignment'))closeModal();$('companyLibraryPanel')?.remove();mount()});window.siteCompanyEducationLibrary={list,open,blob:async(site,id)=>{const r=(await rpc('educationLibraryRead',{p_site_key:site,p_id:id,p_after_id:null}))[0];if(!r?.document_base64)throw Error('教材を確認できません');return new Blob([Uint8Array.from(atob(r.document_base64),c=>c.charCodeAt(0))],{type:r.mime})}};
})();
