(function(){'use strict';
const api='https://tcxbtanumtuyfrqtjtvo.supabase.co/rest/v1/rpc/',key='sb_publishable_UVAjFJSjIs7Sl2tMpLWRkQ_uyDw9eyW';
const $=id=>document.getElementById(id),kind=$('kind'),status=$('status');let generation=0,busy=false;
const authKey=k=>k==='worker'?'jinshou_sub_auth':'jinshou_device_auth';
function stored(k){let raw;try{raw=localStorage.getItem(authKey(k))}catch{}if(!raw){const c=document.cookie.split('; ').find(x=>x.startsWith(authKey(k)+'='));if(c)try{raw=decodeURIComponent(c.slice(authKey(k).length+1))}catch{}}if(!raw)try{raw=sessionStorage.getItem(authKey(k))}catch{}try{return JSON.parse(raw||'null')}catch{return null}}
function persist(k,value){const raw=JSON.stringify(value);let saved=false;try{localStorage.setItem(authKey(k),raw);saved=true}catch{}try{sessionStorage.setItem(authKey(k),raw);saved=true}catch{}document.cookie=authKey(k)+'='+encodeURIComponent(raw)+'; Max-Age=15552000; Path=/; SameSite=Lax; Secure';if(!saved&&!stored(k))throw Error('ログイン情報を保存できません。ブラウザーの保存設定を確認してください。')}
async function rpc(name,params,k,token){const headers={'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key};if(token)headers[k==='worker'?'X-Sub-Device-Token':'X-Device-Token']=token;const res=await fetch(api+name,{method:'POST',headers,body:JSON.stringify(params),signal:AbortSignal.timeout(25000)});const data=await res.json();if(!res.ok)throw Error(data?.message||'ログインを確認できませんでした。');return Array.isArray(data)?data[0]:data}
const session=(k,code,token)=>rpc(k==='worker'?'site_worker_session':'site_member_session',k==='worker'?{p_login_code:code}:{p_employee_code:code},k,token);
function enter(k){const params=new URLSearchParams();if(k==='worker')params.set('portal','sub');if(new URLSearchParams(location.search).get('view')==='ky')params.set('view','ky');location.replace('./'+(params.size?'?'+params.toString():''))}
function mode(){generation++;$('code-label').textContent=kind.value==='worker'?'ログインID':'社員番号';$('help').href='https://shota-1003.github.io/jinshou-employee-app/'+(kind.value==='worker'?'sub/':'');$('pin').value='';status.textContent='';const a=stored(kind.value);$('code').value=a?.employeeCode||a?.loginCode||''}
kind.value=new URLSearchParams(location.search).get('portal')==='sub'?'worker':'employee';kind.onchange=mode;mode();
$('login').onsubmit=async event=>{event.preventDefault();if(busy)return;const k=kind.value,code=$('code').value.trim(),pin=$('pin').value,version=++generation,before=JSON.stringify(stored(k));if(!code||!/^\d{4,6}$/.test(pin)){status.textContent='ログイン番号と4〜6桁の暗証番号を入力してください。';return}busy=true;kind.disabled=true;$('submit').disabled=true;status.textContent='本人を確認しています…';
try{const row=await rpc(k==='worker'?'subcontractor_verify_pin':'verify_employee_pin',k==='worker'?{p_login_code:code,p_pin:pin}:{p_employee_code:code,p_pin:pin},k);if(version!==generation)return;if(!row?.out_device_token)throw Error('ログイン番号または暗証番号を確認してください。');let token=row.out_device_token;
 if(k==='employee'&&row.out_approval_status==='pending'){const prior=stored(k);if(prior?.employeeCode===code&&prior.token){try{await session(k,code,prior.token);token=prior.token}catch{}}}
 await session(k,code,token);if(version!==generation||before!==JSON.stringify(stored(k)))throw Error('別の画面でログインが変わりました。もう一度確認してください。');persist(k,k==='worker'?{loginCode:code,token,workerName:row.out_worker_name,companyName:row.out_company_name}:{employeeCode:code,token});$('pin').value='';enter(k);
}catch(e){if(version===generation)status.textContent=e.message||'通信できませんでした。もう一度お試しください。'}finally{busy=false;kind.disabled=false;$('submit').disabled=false;$('pin').value=''}};
window.addEventListener('storage',event=>{if(event.key===authKey(kind.value)){generation++;status.textContent='別の画面でログイン情報が変わりました。本人を確認してログインしてください。'}});
if(!new URLSearchParams(location.search).has('switch')){const k=kind.value,a=stored(k),code=a?.employeeCode||a?.loginCode,version=generation;if(code&&a?.token){status.textContent='保存済みのログインを確認しています…';session(k,code,a.token).then(()=>{if(version===generation&&!busy)enter(k)}).catch(()=>{if(version===generation&&!busy)status.textContent='暗証番号でログインしてください。'})}}
})();
