(function(){
'use strict';
let mode='overview',query='',siteQuery='',matrixPage=0,itemPage=0,batch=null,importRows=[],focusSite=null,focusSlip=null,slipReturn=null;
const uid=()=>crypto.randomUUID(),today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10),fmt=n=>n.toLocaleString('ja-JP');
const snapshot=()=>inventorySnapshot();
function filtered(){return inventorySummary().filter(i=>i.name.toLowerCase().includes(query.toLowerCase()))}
function searchBox(){return `<input aria-label="部材を検索" placeholder="部材名・規格を検索" value="${esc(query)}" oninput="stockSearch(this.value)">`}
window.stockSearch=v=>{query=v;itemPage=0;render();const el=document.querySelector('[aria-label="部材を検索"]');if(el){el.focus();el.setSelectionRange(v.length,v.length)}};
window.stockSiteSearch=v=>{siteQuery=v;matrixPage=0;render();const el=document.querySelector('[aria-label="現場を検索"]');if(el){el.focus();el.setSelectionRange(v.length,v.length)}};
window.stockMode=v=>{mode=v;focusSite=null;focusSlip=null;render()};window.stockPage=(type,delta)=>{if(type==='site')matrixPage=Math.max(0,matrixPage+delta);else itemPage=Math.max(0,itemPage+delta);render()};
function matrix(){const sites=state.sites.filter(s=>s.name.includes(siteQuery));return `<div class="stock-tools"><input aria-label="現場を検索" placeholder="現場名で検索" value="${esc(siteQuery)}" oninput="stockSiteSearch(this.value)"></div><p class="hint">現場を選ぶと、現在その現場にある部材だけを表示します。</p><div class="stock-site-picker">${sites.map(s=>`<button class="stock-slip-link" onclick="stockSitePage(${s.id})"><strong>${esc(s.name)}</strong><span>${inventorySummary(s.id).filter(i=>i.held>0).length}品目</span><span>保有部材を見る →</span></button>`).join('')||'<p>該当する現場はありません。</p>'}</div>`}
function balanceTable(sid){let rows=inventorySummary(sid).filter(i=>i.name.toLowerCase().includes(query.toLowerCase()));if(sid)rows=rows.filter(i=>i.held>0);const available=document.querySelector('main')?.clientWidth||innerWidth-300,cols=available>=1150?3:available>=740?2:1,size=Math.ceil(rows.length/cols)||1;const chunks=Array.from({length:Math.min(cols,rows.length)},(_,i)=>rows.slice(i*size,(i+1)*size));return `<div class="stock-tools">${searchBox()}<span class="meta">${rows.length}品目${sid?'（この現場にある部材のみ）':''} ／ 横に${cols}組で表示</span></div><div class="stock-scroll stock-fold"><div class="stock-fold-columns" style="--stock-cols:${cols}">${chunks.map(rs=>`<table class="stock-sheet"><colgroup>${sid?'<col style="width:calc(100% - 95px)"><col style="width:30px"><col style="width:65px">':'<col style="width:calc(100% - 160px)"><col style="width:30px"><col style="width:65px"><col style="width:65px">'}</colgroup><thead><tr><th>部材名・規格</th><th>単位</th>${sid?'':'<th>倉庫残数</th>'}<th>${sid?'現場残数':'全現場'}</th></tr></thead><tbody>${rs.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.unit)}</td>${sid?'':`<td>${fmt(i.warehouse)}</td>`}<td class="value">${fmt(i.held)}</td></tr>`).join('')}</tbody></table>`).join('')||'<p>該当する部材はありません。</p>'}</div></div>`}
function history(sid){const d=snapshot(),groups=new Map();for(const m of [...d.moves].reverse().filter(m=>!sid||String(m.site)===String(sid))){let k=m.batchId||m.id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m)}return `<div class="stock-docs">${[...groups].map(([id,ms])=>{const m=ms[0],s=state.sites.find(s=>String(s.id)===String(m.site));return `<button class="stock-slip-link" data-slip="${esc(id)}" data-site="${sid||''}" onclick="stockSlipPage(this.dataset.slip,this.dataset.site)"><span class="pill">${stockMoveLabel(m.type)}</span><span>${esc(m.date)}</span><strong>${esc(s?.name)} ／ ${esc(m.actor)}</strong><span>${ms.length}品目</span><span>伝票を開く →</span></button>`}).join('')||'<p>入出庫の記録はありません。</p>'}</div>`}
window.stockSitePage=id=>{focusSite=id;focusSlip=null;query='';page='inventory';render();window.scrollTo(0,0)};
window.stockSlipPage=(id,sid)=>{slipReturn=sid||focusSite;focusSlip=id;page='inventory';render();window.scrollTo(0,0)};
window.stockSlipBack=()=>{focusSlip=null;if(slipReturn){focusSite=slipReturn}else{focusSite=null;mode='history'}render()};
function slipPage(){return correctedSlipPage(focusSlip)}
function legacySlipPage(){const d=snapshot(),ms=d.moves.filter(m=>(m.batchId||m.id)===focusSlip),m=ms[0];if(!m)return '<p>伝票が見つかりません</p>';const s=state.sites.find(s=>String(s.id)===String(m.site)),cols=(document.querySelector('main')?.clientWidth||innerWidth-300)>=1150?3:innerWidth>=1000?2:1,size=Math.ceil(ms.length/cols),chunks=Array.from({length:Math.min(cols,ms.length)},(_,i)=>ms.slice(i*size,(i+1)*size));return `<section class="stock-fullpage"><button class="secondary" onclick="stockSlipBack()">← 伝票一覧へ戻る</button><div class="section-head"><div><span class="eyebrow">MATERIAL SLIP</span><h2>${esc(s?.name)} ／ ${stockMoveLabel(m.type)+'伝票'}</h2><p>${esc(m.date)} ・ 実施者：${esc(m.actor)} ・ ${ms.length}品目</p><p>${esc(m.note||'')}</p></div></div><div class="stock-fold"><div class="stock-fold-columns" style="--stock-cols:${cols}">${chunks.map(rs=>`<table class="stock-sheet"><thead><tr><th>部材・規格</th><th>数量</th><th>単位</th><th>状態</th></tr></thead><tbody>${rs.map(x=>`<tr><td>${esc(d.items.find(i=>i.id===x.item)?.name)}</td><td>${fmt(x.qty)}</td><td>${esc(d.items.find(i=>i.id===x.item)?.unit)}</td><td>${d.moves.some(r=>r.reverse===x.id)?'訂正済み':x.type==='reverse'?'訂正記録':!['dispatch','return'].includes(x.type)?stockMoveLabel(x.type):`<button onclick="inventoryReverseForm('${x.id}')">訂正</button>`}</td></tr>`).join('')}</tbody></table>`).join('')}</div></div></section>`}
window.renderInventory=function(sid){if(!sid&&focusSlip)return slipPage();if(!sid&&focusSite){const s=state.sites.find(s=>String(s.id)===String(focusSite));return `<section class="stock-fullpage"><button class="secondary" onclick="stockMode('sites')">← 現場別の保有表へ戻る</button><div class="section-head"><div><h2>${esc(s?.name)} の保有部材</h2><p>現在この現場に残っている部材のみ。全数返却した部材は表示しません。</p></div>${orderActions(focusSite)}</div>${siteSlipHub(focusSite)}${balanceTable(focusSite)}${stockDemandView(focusSite)}${zoneOrders(focusSite)}</section>`}let view=sid?'stock':mode;return `<div class="inventory-view"><div class="section-head"><div><span class="eyebrow">SCAFFOLDING / STOCK SHEET</span><h2>${sid?'この現場の部材一覧':'資材管理・在庫表'}</h2><p>多数の部材を、１枚の伝票でまとめて動かす。</p></div><div class="${sid?'row':'stock-action-bar'}">${sid?orderActions(sid):'<button onclick="stockPurchase()">購入資材を追加</button><button onclick="orderCenter()">資材センター・注文一覧</button><button onclick="stockBatchForm()">直接出荷・返却</button><button class="danger" onclick="stockSettlement()">破損・紛失を精算する</button>'}</div></div>${!sid?`<div class="stock-tabs"><button class="${view==='overview'?'active':''}" onclick="stockMode('overview')">総合在庫表</button><button class="${view==='stock'?'active':''}" onclick="stockMode('stock')">部材別の在庫</button><button class="${view==='sites'?'active':''}" onclick="stockMode('sites')">現場から探す</button><button class="${view==='history'?'active':''}" onclick="stockMode('history')">伝票履歴</button></div>`:''}${sid?siteSlipHub(sid):''}${view==='overview'?stockOverview(query,siteQuery):view==='sites'?matrix():view==='history'?history():balanceTable(sid)}${sid?`${stockDemandView(sid)}${zoneOrders(sid)}`:''}${stockUpdatedLabel()}${!sid?'<details class="stock-setup"><summary>資材管理の設定・初回登録</summary><p>初期在庫は利用開始時に登録します。購入による追加は「購入資材を追加」を使ってください。</p><button class="secondary" onclick="stockImportForm()">初期在庫を一括登録</button></details>':''}<p class="hint">端末内の試作です。現場別の数量は台帳から自動計算します。初期在庫の表は「部材名・単位・倉庫数量」の列で貼り付けできます。</p></div>`};
window.stockBatchForm=function(sid){if(!inventorySummary().length){stockImportForm();return}batch={id:uid(),revision:snapshot().revision,values:{},site:String(sid||state.sites[0]?.id||''),kind:'dispatch',search:'',selectedOnly:false};show(`<h2>一括出荷・返却伝票</h2><p>現場・実施者・日付は１回だけ入力。部材の数量をまとめて記入します。</p><form id="stockBatch"><div class="stock-batch-head"><div><label>現場を検索・選択</label><input id="batchSiteQuery" placeholder="現場名で候補を絞る" oninput="batchSiteFilter(this.value)"><select name="site" required onchange="batchContext()">${state.sites.map(s=>`<option value="${s.id}" ${String(s.id)===batch.site?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div><label>入出庫</label><select name="kind" onchange="batchContext()"><option value="dispatch">出荷：倉庫 → 現場</option><option value="return">返却：現場 → 倉庫</option></select><label>実施日</label><input name="date" type="date" required max="${today()}" value="${today()}"></div><div><label>実施者</label><input name="actor" required maxlength="60"><label>備考</label><input name="note"></div></div><div class="stock-tools"><input placeholder="部材名で検索（入力済み数量は保持）" oninput="batch.search=this.value;drawBatchRows()" id="batchSearch"><label><input type="checkbox" onchange="batch.selectedOnly=this.checked;drawBatchRows()"> 入力済みだけ表示</label><button type="button" class="secondary" onclick="batchPasteForm()">表の数量を貼り付け</button></div><div id="batchRows"></div><div class="stock-footer"><span id="batchCount"></span><span id="batchError" role="alert" class="stock-error"></span><div class="row"><button type="button" class="secondary" onclick="closeModal()">閉じる</button><button class="primary">まとめて確認・登録</button></div></div></form>`);$('modal').classList.add('stock-batch-dialog');$('modal').addEventListener('close',()=>$('modal').classList.remove('stock-batch-dialog'),{once:true});drawBatchRows();$('stockBatch').onsubmit=commitBatchForm};
// Named global actions are referenced by the prototype's inline controls.
window.batchContext=()=>{batch.site=$('stockBatch').elements.site.value;batch.kind=$('stockBatch').elements.kind.value;drawBatchRows()};
window.batchSiteFilter=q=>{const select=$('stockBatch').elements.site;for(const o of select.options)o.hidden=!o.textContent.includes(q)};
window.drawBatchRows=function(){let rows=inventorySummary(batch.site).filter(i=>i.name.toLowerCase().includes(batch.search.toLowerCase())&&(!batch.selectedOnly||Number(batch.values[i.id])>0));let chunks=[],columns=innerWidth>=1400?3:innerWidth<=700?1:2,chunkSize=Math.ceil(rows.length/columns)||1;for(let i=0;i<rows.length;i+=chunkSize)chunks.push(rows.slice(i,i+chunkSize));$('batchRows').innerHTML=`<div class="stock-scroll"><div class="sheet-columns">${chunks.map(rs=>`<table class="stock-sheet"><thead><tr><th>部材・規格</th><th>残数</th><th>今回数量</th></tr></thead><tbody>${rs.map(i=>`<tr class="${Number(batch.values[i.id])>0?'selected':''}"><td>${esc(i.name)} <small class="sheet-label">${esc(i.unit)}</small></td><td>${batch.kind==='dispatch'?i.warehouse:i.held}</td><td><input aria-label="${esc(i.name)}の数量" data-stock-id="${i.id}" type="number" min="0" step="1" value="${esc(batch.values[i.id]||'')}" oninput="batchQuantity(this.dataset.stockId,this.value)" placeholder="0"></td></tr>`).join('')}</tbody></table>`).join('')}</div></div>`;batchCount()};
window.batchQuantity=(id,v)=>{batch.values[id]=v;batchCount()};function batchCount(){let n=Object.values(batch.values).filter(v=>Number(v)>0).length;$('batchCount').textContent=`入力済み ${n}品目（検索で隠れた行も保持）`}
async function commitBatchForm(e){e.preventDefault();let f=e.target,b=f.querySelector('.primary');if(b.disabled)return;let values=new FormData(f),rows=Object.entries(batch.values).filter(([,v])=>v!==''&&Number(v)!==0);try{if(!rows.length)throw Error('数量を１品目以上入力してください');let ops=rows.map(([item,v],i)=>({kind:values.get('kind'),id:batch.id+'-'+i,batchId:batch.id,site:values.get('site'),actor:values.get('actor'),date:values.get('date'),note:values.get('note'),item,qty:Number(v)}));b.disabled=true;await inventoryCommitBatch(ops,batch.revision);if(f.isConnected)closeModal();render();notify(`${rows.length}品目を１枚の伝票として登録しました`)}catch(err){$('batchError').textContent=err.message}finally{b.disabled=false}}
function parseTable(text){const lines=[];let row=[],cell='',quoted=false;const delim=text.includes('\t')?'\t':',';for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(!quoted&&(c===delim||c==='\n')){row.push(cell.trim());cell='';if(c==='\n'){if(row.some(Boolean))lines.push(row);row=[]}}else if(c!=='\r')cell+=c}if(quoted)throw Error('引用符が閉じていません');row.push(cell.trim());if(row.some(Boolean))lines.push(row);if(lines[0]?.[0]?.replace(/^\uFEFF/,'').match(/^(部材名|資材名|品名)$/))lines.shift();return lines.map(r=>{r[0]=r[0].replace(/^\uFEFF/,'');return r})}
window.StockTableParser=parseTable;
window.stockImportForm=function(){importRows=[];const rev=snapshot().revision;show(`<h2>初期在庫を表から一括登録</h2><div class="stock-step">Excelの３列をコピーして貼り付け：<b>部材名　単位　倉庫数量</b><br>例：手すり1.8m　　本　　100<br>登録済み部材は上書きせずエラーにします。写真の数字を自動登録する機能ではありません。</div><label>CSVファイルを選ぶ（UTF-8）</label><input type="file" accept=".csv,.tsv,.txt" onchange="stockReadCsv(this.files[0])"><label>表を貼り付け</label><textarea id="stockPaste" class="stock-paste" oninput="document.getElementById(\'importConfirm\').disabled=true" placeholder="部材名&#9;単位&#9;倉庫数量"></textarea><button class="secondary" onclick="previewStockImport()">取り込み内容を確認</button><div id="importPreview"></div><div class="modalfoot"><span id="importError" role="alert" class="stock-error"></span><button class="secondary" onclick="closeModal()">閉じる</button><button id="importConfirm" class="primary" disabled>この表を一括登録</button></div>`);$('importConfirm').onclick=async()=>{let btn=$('importConfirm');btn.disabled=true;try{let ops=importRows.map(r=>({kind:'item',id:uid(),name:r[0],unit:r[1],initial:Number(r[2])}));await inventoryCommitBatch(ops,rev);closeModal();render();notify(`${ops.length}品目を一括登録しました`)}catch(e){$('importError').textContent=e.message;btn.disabled=false}}};
window.stockReadCsv=async f=>{try{if(f){if(f.size>2*1024*1024)throw Error('CSVは2MB以下にしてください');const box=$('stockPaste');box.value=await f.text();if(box.isConnected)previewStockImport()}}catch(e){const el=$('importError');if(el)el.textContent=e.message}};
window.previewStockImport=()=>{try{importRows=parseTable($('stockPaste').value);if(!importRows.length||importRows.length>2000)throw Error('1～2000行の表を指定してください');const names=new Set(inventorySummary().map(i=>i.name));for(const [i,r]of importRows.entries()){if(r.length!==3||!r[0]||!r[1]||r[2]===''||!Number.isSafeInteger(Number(r[2]))||Number(r[2])<0)throw Error(`${i+1}行目：部材名・単位・0以上の整数を指定してください`);if(names.has(r[0]))throw Error(`${i+1}行目：${r[0]} は重複しています`);names.add(r[0])}$('importPreview').innerHTML=`<p>${importRows.length}品目を登録します。</p><div class="stock-scroll stock-import-preview"><table class="stock-sheet"><thead><tr><th>部材名</th><th>単位</th><th>初期数量</th></tr></thead><tbody>${importRows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('importError').textContent='';$('importConfirm').disabled=false}catch(e){importRows=[];$('importError').textContent=e.message;$('importConfirm').disabled=true}};
window.batchPasteForm=()=>{let area=$('batchPasteArea');if(area){area.remove();return}area=document.createElement('div');area.id='batchPasteArea';area.innerHTML=`<p class="hint">部材名・数量の２列を貼り付け。確認すると、該当部材の今回数量を置き換えます。</p><textarea id="batchPasteText" class="stock-paste"></textarea><button type="button" class="secondary" onclick="applyBatchPaste()">数量を表へ反映</button><p id="batchPasteError" class="stock-error"></p>`;$('batchRows').before(area)};
window.applyBatchPaste=()=>{try{let rs=parseTable($('batchPasteText').value),next={...batch.values},items=inventorySummary(),seen=new Set();if(!rs.length)throw Error('表を貼り付けてください');for(const [i,r]of rs.entries()){let it=items.find(x=>x.name===r[0]);if(r.length!==2||!it||seen.has(r[0])||r[1]===''||!Number.isSafeInteger(Number(r[1]))||Number(r[1])<0)throw Error(`${i+1}行目：未登録の部材、重複、数量を確認してください`);seen.add(r[0]);next[it.id]=r[1]}batch.values=next;drawBatchRows();$('batchPasteArea').remove()}catch(e){$('batchPasteError').textContent=e.message}};
// Preserve old callers while moving the visible workflow to one batch sheet.
window.inventoryMoveForm=stockBatchForm;window.inventoryItemForm=stockImportForm;
// Global helpers avoid exposing the working object in markup.
Object.defineProperty(window,'batch',{get:()=>batch,configurable:true});
render();
})();


