(function(root){
'use strict';
const KEY='jinshou-inventory-v1';
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return {version:1,revision:0,items:[],moves:[]}}
function validId(v){return typeof v==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(v)}
function validDate(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v}
function balances(d){if(!d||d.version!==1||!Number.isSafeInteger(d.revision)||d.revision<0||!Array.isArray(d.items)||!Array.isArray(d.moves))throw Error('台帳データが不正です');const out=Object.create(null),seen=new Map(),reversed=new Set();for(const i of d.items){if(!i||!validId(i.id)||seen.has(i.id)||typeof i.name!=='string'||!i.name.trim()||typeof i.unit!=='string'||!i.unit.trim())throw Error('資材情報が不正です');validateQty(i.initial,true);seen.set(i.id,i);out[i.id]={warehouse:i.initial,sites:Object.create(null)}};for(const m of d.moves){if(!m||!validId(m.id)||seen.has(m.id)||!validId(m.site)||!['dispatch','return','reverse','purchase','damage','loss'].includes(m.type)||typeof m.actor!=='string'||!m.actor.trim()||!validDate(m.date))throw Error('履歴データが不正です');validateQty(m.qty);const b=out[m.item];if(!b)throw Error('資材が存在しません');if(m.type==='reverse'){const old=seen.get(m.reverse);if(!old||!['dispatch','return'].includes(old.type)||reversed.has(old.id)||old.item!==m.item||old.site!==m.site||old.qty!==m.qty||m.delta!==(old.type==='dispatch'?old.qty:-old.qty)||!String(m.note||'').trim()||m.date<old.date)throw Error('訂正履歴が不正です');reversed.add(old.id)}else if(m.reverse!==undefined||m.delta!==undefined)throw Error('履歴データが不正です');seen.set(m.id,m);if(m.type==='purchase'){b.warehouse+=m.qty;if(!Number.isSafeInteger(b.warehouse))throw Error('在庫数量が不正です');continue}if(['damage','loss'].includes(m.type)){b.sites[m.site]=(b.sites[m.site]||0)-m.qty;if(b.sites[m.site]<0)throw Error('現場残数が不足しています');continue}const delta=m.type==='dispatch'?-m.qty:m.type==='return'?m.qty:m.delta;b.warehouse+=delta;b.sites[m.site]=(b.sites[m.site]||0)-delta;if(!Number.isSafeInteger(b.warehouse)||!Number.isSafeInteger(b.sites[m.site]))throw Error('在庫数量が不正です');if(b.warehouse<0||b.sites[m.site]<0)throw Error('数量が残数を超えています');}return out}
function validateQty(n,zero=false){if(!Number.isSafeInteger(n)||n<(zero?0:1)||n>100000000)throw Error('数量は'+(zero?'0':'1')+'以上の整数で入力してください')}
function apply(d,op){balances(d);let next=clone(d);if(!validId(op.id))throw Error('操作IDが不正です');const duplicate=next.moves.find(m=>m.id===op.id)||next.items.find(i=>i.id===op.id);if(duplicate){const same=op.kind==='item'?duplicate.name===String(op.name||'').trim()&&duplicate.unit===String(op.unit||'').trim()&&duplicate.initial===op.initial:duplicate.type===op.kind&&duplicate.actor===String(op.actor||'').trim()&&duplicate.date===op.date&&duplicate.note===String(op.note||'').trim()&&(op.kind==='reverse'?duplicate.reverse===op.reverse:duplicate.item===op.item&&duplicate.site===String(op.site)&&duplicate.qty===op.qty);if(!same)throw Error('同じ操作IDに異なる内容が指定されています');return next;}
if(op.kind==='item'){if(!String(op.name||'').trim()||!String(op.unit||'').trim())throw Error('資材名と単位を入力してください');if(next.items.some(i=>i.name===op.name.trim()))throw Error('同じ名前の資材が登録されています');validateQty(op.initial,true);next.items.push({id:op.id,name:op.name.trim(),unit:op.unit.trim(),initial:op.initial,createdAt:new Date().toISOString()});}
else{if(!String(op.actor||'').trim())throw Error('実施者を入力してください');if(!/^\d{4}-\d{2}-\d{2}$/.test(op.date||'')||new Date(op.date+'T00:00:00Z').toISOString().slice(0,10)!==op.date)throw Error('実施日を正しく入力してください');const localDate=new Date(Date.now()+9*3600000).toISOString().slice(0,10);if(op.date>localDate)throw Error('未来の実績は登録できません');let m={id:op.id,actor:op.actor.trim(),date:op.date,createdAt:new Date().toISOString(),note:String(op.note||'').trim()};if(op.kind==='reverse'){const old=next.moves.find(x=>x.id===op.reverse);if(!old||!['dispatch','return'].includes(old.type)||m.date<old.date||next.moves.some(x=>x.reverse===old.id))throw Error('この記録は訂正できません');if(!m.note)throw Error('訂正理由を入力してください');Object.assign(m,{item:old.item,site:old.site,type:'reverse',reverse:old.id,qty:old.qty,delta:old.type==='dispatch'?old.qty:-old.qty});}else{if(!['dispatch','return','purchase','damage','loss'].includes(op.kind))throw Error('操作が不正です');validateQty(op.qty);if(!op.site)throw Error('現場を選択してください');Object.assign(m,{item:op.item,site:String(op.site),type:op.kind,qty:op.qty});}next.moves.push(m);const b=balances(next);for(const v of Object.values(b)){if(v.warehouse<0||Object.values(v.sites).some(n=>n<0))throw Error('数量が残数を超えています。元の記録や、その後の入出庫を確認してください');}}
next.revision++;balances(next);return next;}
function applyBatch(d,ops){
balances(d);
if(!Array.isArray(ops)||!ops.length||ops.length>2000)throw Error('一括登録は1〜2000行で指定してください');
const ids=new Set();for(const op of ops){if(!op||!validId(op.id)||ids.has(op.id))throw Error('一括登録の操作IDが重複または不正です');ids.add(op.id);if(op.batchId!==undefined&&!validId(op.batchId))throw Error('伝票IDが不正です');}
let next=clone(d),changed=false;
for(const op of ops){const existing=next.moves.find(m=>m.id===op.id)||next.items.find(i=>i.id===op.id);if(existing&&existing.batchId!==op.batchId)throw Error('同じ操作IDに異なる伝票が指定されています');const applied=apply(next,op);if(applied.revision!==next.revision){changed=true;const entry=applied.moves.find(m=>m.id===op.id)||applied.items.find(i=>i.id===op.id);if(op.batchId!==undefined)entry.batchId=op.batchId;}next=applied;}
next.revision=d.revision+(changed?1:0);balances(next);return next;
}
root.InventoryCore={fresh,balances,apply,applyBatch};if(typeof module!=='undefined'&&module.exports)module.exports=root.InventoryCore;if(typeof document==='undefined')return;
let data=fresh(),loadError='';try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);balances(parsed);data=parsed}}catch{loadError='資材データを読み込めません。保存内容を保護するため登録を停止しています。'}
const id=()=>crypto.randomUUID();const today=()=>{return new Date(Date.now()+9*3600000).toISOString().slice(0,10)};
async function commit(op,expectedRevision){if((op.kind==='return'||(op.kind==='reverse'&&data.moves.find(m=>m.id===op.reverse)?.type==='return'))&&(!root.canRecordReturn||!root.canRecordReturn(op.site||data.moves.find(m=>m.id===op.reverse)?.site)))throw Error('返却はこの現場のメンバーが操作できます');if(loadError)throw Error(loadError);const write=()=>{const raw=localStorage.getItem(KEY);const latest=raw?JSON.parse(raw):fresh();balances(latest);if(latest.revision!==expectedRevision){data=latest;throw Error('別の画面で更新されました。画面を確認してから登録し直してください')}const next=apply(latest,op);localStorage.setItem(KEY,JSON.stringify(next));data=next;};if(!navigator.locks)throw Error('このブラウザは安全な在庫保存に対応していません。最新のChromeまたはEdgeで開いてください');return navigator.locks.request(KEY,write)}
root.inventorySnapshot=()=>clone(data);
root.inventoryOrderChange=async function(cmd,rev){
 if(loadError)throw Error(loadError);
 return navigator.locks.request(KEY,()=>{
 const raw=localStorage.getItem(KEY),latest=raw?JSON.parse(raw):fresh();balances(latest);
 if(latest.revision!==rev){data=latest;throw Error('別の画面で更新されました。開き直して確認してください');}
 let next=clone(latest);next.orders=next.orders||[];
 if(cmd.kind==='create'||cmd.kind==='edit'){
 const o=clone(cmd.order),old=next.orders.find(x=>x.id===o.id);if(cmd.kind==='edit'&&(!old||old.status==='持出済み'))throw Error('持出済みの注文は変更できません。追加注文・返却で記録してください');
 if(!validId(o.id)||(cmd.kind==='create'&&next.orders.some(x=>x.id===o.id))||!state.sites.some(s=>String(s.id)===String(o.site))||!o.requester.trim()||!validDate(o.needed)||!o.lines.length)throw Error('現場・注文者・希望日・数量を確認してください');
 const seen=new Set();for(const line of o.lines){validateQty(line.qty);if(!next.items.some(i=>i.id===line.item)||seen.has(line.item))throw Error('部材が不正です');seen.add(line.item);line.checked=false;line.checkedBy='';}
 o.status='注文済み';o.createdAt=old?.createdAt||new Date().toISOString();o.history=[...(old?.history||[]),{at:new Date().toISOString(),actor:o.requester,action:old?'注文修正':'注文確定',before:old?{zone:old.zone||'',needed:old.needed,note:old.note,lines:old.lines}:null,after:{zone:o.zone||'',needed:o.needed,note:o.note,lines:clone(o.lines)}}];if(old)next.orders[next.orders.indexOf(old)]=o;else next.orders.push(o);
 }else{
 const o=next.orders.find(x=>x.id===cmd.id);if(!o)throw Error('注文がありません');
 if(o.status==='持出済み')throw Error('すでに持出済みです');
 if(cmd.kind==='check'){
 if(!String(cmd.actor||'').trim())throw Error('準備担当者を入力してください');const line=o.lines.find(l=>l.item===cmd.item);if(!line)throw Error('部材がありません');line.checked=!!cmd.checked;line.checkedBy=cmd.checked?cmd.actor.trim():'';line.checkedAt=new Date().toISOString();o.status=o.lines.every(l=>l.checked)?'準備完了':'準備中';
 }else if(cmd.kind==='dispatch'){
 if(!o.lines.every(l=>l.checked))throw Error('すべての部材を準備・チェックしてください');
 const ops=o.lines.map((l,i)=>({kind:'dispatch',id:o.id+'-'+i,batchId:o.id,item:l.item,qty:l.qty,site:String(o.site),actor:cmd.actor,date:cmd.date,note:'注文伝票 '+o.id}));
 next=applyBatch(next,ops);const saved=next.orders.find(x=>x.id===o.id);saved.status='持出済み';saved.carrier=cmd.actor;saved.dispatchedAt=cmd.date;
 }else throw Error('操作が不正です');
 }
 next.revision=latest.revision+1;localStorage.setItem(KEY,JSON.stringify(next));data=next;return clone(next);
 });
};
root.inventoryCommitBatch=async function(ops,expectedRevision){
if(loadError)throw Error(loadError);
if(!navigator.locks)throw Error('このブラウザは安全な在庫保存に対応していません。最新のChromeまたはEdgeで開いてください');
const commands=clone(ops);if(commands.some(o=>['purchase','damage','loss','item'].includes(o.kind))&&(!root.canAdjustStock||!root.canAdjustStock()))throw Error('購入・総保有数の変更は在庫管理者だけが操作できます');if(commands.some(o=>(o.kind==='return'||(o.kind==='reverse'&&data.moves.find(m=>m.id===o.reverse)?.type==='return'))&&!root.canRecordReturn(o.site||data.moves.find(m=>m.id===o.reverse)?.site)))throw Error('返却はこの現場のメンバーが操作できます');if(commands.some(o=>['damage','loss'].includes(o.kind))&&!root.canManageReturns())throw Error('最終締めは指定担当者だけが操作できます');
return navigator.locks.request(KEY,()=>{const raw=localStorage.getItem(KEY);const latest=raw?JSON.parse(raw):fresh();balances(latest);if(latest.revision!==expectedRevision){data=latest;throw Error('別の画面で更新されました。画面を確認してから登録し直してください');}
if(!Array.isArray(commands))throw Error('登録内容が不正です');
for(const op of commands){if(['dispatch','return','damage','loss'].includes(op.kind)){if(!state.sites.some(s=>String(s.id)===String(op.site)))throw Error('現場が存在しません');}}
const next=applyBatch(latest,commands);if(commands.some(o=>['purchase','damage','loss','item'].includes(o.kind)))next.stockAdjustedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(next));data=next;return clone(data);});
};
root.inventoryFinalReport=async function(ops,rev){if(!root.canManageReturns())throw Error('指定返却担当者のみ記録できます');return navigator.locks.request(KEY,()=>{let latest=JSON.parse(localStorage.getItem(KEY));if(latest.revision!==rev){data=latest;throw Error('更新されています。開き直してください')}let next=clone(latest);next.pendingLoss=next.pendingLoss||[];const loss=ops.filter(o=>['damage','loss'].includes(o.kind)),returns=ops.filter(o=>o.kind==='return');for(const o of loss){validateQty(o.qty);if(!o.actor.trim()||!o.note.trim()||!validDate(o.date))throw Error('記録者・日付・理由を確認してください');if(next.pendingLoss.some(x=>x.id===o.id))throw Error('登録済みです');next.pendingLoss.push({...o,reportedAt:new Date().toISOString(),settledAt:null})}if(returns.length)next=applyBatch(next,returns);const b=balances(next),reserved={};for(const o of next.pendingLoss.filter(x=>!x.settledAt)){const k=o.site+'|'+o.item;reserved[k]=(reserved[k]||0)+o.qty;if(!b[o.item]||reserved[k]>(b[o.item].sites[o.site]||0))throw Error('現場残数を超えています（報告済みの未精算分を含む）')}next.revision=latest.revision+1;localStorage.setItem(KEY,JSON.stringify(next));data=next;});};
root.inventorySettle=async function(ids,rev){if(!root.canAdjustStock())throw Error('在庫管理者のみ精算できます');return navigator.locks.request(KEY,()=>{let latest=JSON.parse(localStorage.getItem(KEY));if(latest.revision!==rev){data=latest;throw Error('更新されています。確認し直してください')}const rows=(latest.pendingLoss||[]).filter(x=>ids.includes(x.id)&&!x.settledAt);if(!rows.length||rows.length!==ids.length)throw Error('精算済み、または対象が変更されています');const at=new Date().toISOString(),date=new Date(Date.now()+9*3600000).toISOString().slice(0,10),batch=crypto.randomUUID();let next=applyBatch(latest,rows.map((r,i)=>({...r,id:batch+'-'+i,batchId:batch,date,actor:root.stockCurrentUser(),note:'精算：'+r.note})));for(const r of next.pendingLoss)if(ids.includes(r.id)){r.settledAt=at;r.settledBy=root.stockCurrentUser()}next.stockAdjustedAt=at;localStorage.setItem(KEY,JSON.stringify(next));data=next;});};
root.inventoryCorrectQuantity=async function(id,qty,actor,reason,rev){return navigator.locks.request(KEY,()=>{const latest=JSON.parse(localStorage.getItem(KEY));if(latest.revision!==rev){data=latest;throw Error('別の画面で更新されました。開き直してください')}const original=latest.moves.find(m=>m.id===id);if(!original||!['dispatch','return'].includes(original.type))throw Error('この伝票は数量訂正できません');if(original.type==='return'&&!root.canRecordReturn(original.site))throw Error('返却の訂正はこの現場のメンバーのみです');validateQty(qty,true);if(!actor.trim()||!reason.trim())throw Error('訂正者と理由を入力してください');const prior=(latest.corrections||[]).filter(c=>c.original===id).at(-1),active=prior?.replacement?latest.moves.find(m=>m.id===prior.replacement):prior?null:original;const reversed=active&&latest.moves.some(m=>m.reverse===active.id),oldQty=active&&!reversed?active.qty:0;if(qty===oldQty)throw Error('数量が変更されていません');const cid=crypto.randomUUID(),date=new Date(Date.now()+9*3600000).toISOString().slice(0,10),ops=[];if(active&&!reversed)ops.push({kind:'reverse',id:cid+'-r',reverse:active.id,actor,date,note:reason,batchId:cid});if(qty)ops.push({kind:original.type,id:cid+'-n',item:original.item,site:original.site,qty,actor,date,note:reason,batchId:cid});let next=ops.length?applyBatch(latest,ops):clone(latest);next.corrections=next.corrections||[];next.corrections.push({id:cid,original:id,slip:original.batchId||original.id,replacement:qty?cid+'-n':null,before:oldQty,after:qty,actor:actor.trim(),reason:reason.trim(),at:new Date().toISOString()});next.revision=latest.revision+1;localStorage.setItem(KEY,JSON.stringify(next));data=next;});};
root.inventorySummary=function(sid){const b=balances(data);return data.items.map(i=>({...i,warehouse:b[i.id].warehouse,held:sid?(b[i.id].sites[String(sid)]||0):Object.values(b[i.id].sites).reduce((a,n)=>a+n,0),sites:b[i.id].sites}))};
root.renderInventory=function(sid){const rows=root.inventorySummary(sid),moves=data.moves.filter(m=>!sid||String(m.site)===String(sid)).slice().reverse();return `<div class="inventory-view"><div class="section-head"><div><span class="eyebrow">MATERIAL CONTROL</span><h2>${sid?'この現場の資材台帳':'資材管理'}</h2><p>倉庫から現場へ。戻るまで、一つの記録で管理。</p></div><div class="row">${!sid?'<button class="secondary" onclick="inventoryItemForm()">＋ 資材・初期在庫</button>':''}<button class="primary" onclick="inventoryMoveForm('${sid||''}')">出荷・返却を記録</button></div></div>${loadError?`<div role="alert" class="notice">${esc(loadError)}</div>`:''}<div class="inventory-note">このブラウザ内の試作台帳です。社員間の共有は未接続です。数量は品目ごとの整数で管理します。</div><section class="panel"><div class="inventory-table"><table><thead><tr><th>資材 / 規格</th><th>単位</th><th>倉庫残数</th><th>${sid?'この現場にある数':'全現場への持出数'}</th></tr></thead><tbody>${rows.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.unit)}</td><td>${i.warehouse.toLocaleString()}</td><td><strong>${i.held.toLocaleString()}</strong>${!sid?`<small>${Object.entries(i.sites).filter(([,n])=>n>0).map(([s,n])=>esc(state.sites.find(x=>String(x.id)===s)?.name||'不明な現場')+'：'+n).join(' / ')}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="4">資材管理から、手持ちの資材と初期在庫を登録してください。</td></tr>'}</tbody></table></div></section><section class="panel"><h2>入出庫の履歴 <small>${moves.length}件</small></h2><p class="hint">返却は「現場 → 倉庫」、出荷は「倉庫 → 現場」。訂正は元の記録を残して数量を戻します。</p>${moves.map(m=>{const item=data.items.find(i=>i.id===m.item),reversed=data.moves.some(x=>x.reverse===m.id);return `<article class="inventory-log"><div><span class="inventory-kind ${m.type}">${m.type==='dispatch'?'出荷':m.type==='return'?'返却・入庫':'訂正'}</span><b>${esc(item?.name)}　${m.qty} ${esc(item?.unit)}</b>${reversed?'<span class="meta">（訂正済み）</span>':''}<p>${esc(m.date)} · ${esc(m.actor)} · ${esc(state.sites.find(s=>String(s.id)===String(m.site))?.name||'不明な現場')}</p><small>${esc(m.note)}</small></div>${m.type!=='reverse'&&!reversed?`<button class="text-action" onclick="inventoryReverseForm('${m.id}')">訂正</button>`:''}</article>`}).join('')||'<div class="empty">出荷・返却の記録はありません。</div>'}</section></div>`};
function wire(op){let f=document.getElementById('invForm'),busy=false,expectedRevision=data.revision;f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=f.querySelector('button.primary');button.disabled=true;try{const fields=Object.fromEntries(new FormData(f));const cmd={...fields,...op};if('qty'in fields)cmd.qty=Number(fields.qty);if('initial'in fields)cmd.initial=Number(fields.initial);if(cmd.kind!=='item'&&cmd.kind!=='reverse'&&!state.sites.some(s=>String(s.id)===String(cmd.site)))throw Error('現場が存在しません');await commit(cmd,expectedRevision);if(document.getElementById('invForm')===f)closeModal();render();notify('資材台帳を保存しました')}catch(err){let el=document.getElementById('invError');if(el&&document.getElementById('invForm')===f){el.textContent=err.message;el.hidden=false;}else notify(err.message);}finally{busy=false;button.disabled=false}}}
const error='<p id="invError" class="notice" role="alert" hidden></p>';
root.inventoryItemForm=function(){show(`<h2>資材と初期在庫を登録</h2><p>現在、倉庫にある数量を入力してください。登録後は履歴で管理します。</p><form id="invForm"><label>資材名・規格（必須）</label><input name="name" required maxlength="100" placeholder="手すり 1.8m"><label>単位（必須）</label><input name="unit" required maxlength="12" placeholder="本"><label>倉庫の初期在庫（必須）</label><input name="initial" type="number" min="0" step="1" max="100000000" required>${error}${foot('登録する')}</form>`);wire({kind:'item',id:id()})};
root.inventoryMoveForm=function(sid){if(!data.items.length){notify('先に資材管理で資材を登録してください');return}show(`<h2>出荷・返却を記録</h2><form id="invForm"><label>方向</label><select name="kind"><option value="dispatch">出荷：倉庫 → 現場</option><option value="return">返却：現場 → 倉庫</option></select><label>現場（必須）</label><select name="site" required>${state.sites.map(s=>`<option value="${s.id}" ${String(s.id)===String(sid)?'selected':''}>${esc(s.name)}</option>`).join('')}</select><label>資材（必須）</label><select name="item">${root.inventorySummary().map(i=>`<option value="${i.id}">${esc(i.name)} / ${esc(i.unit)}（倉庫 ${i.warehouse}）</option>`).join('')}</select><label>数量（必須）</label><input name="qty" type="number" min="1" max="100000000" step="1" required><label>実施者（必須）</label><input name="actor" required maxlength="60" placeholder="誰が持って行った・返したか"><label>実施日（必須）</label><input name="date" type="date" value="${today()}" max="${today()}" required><label>備考</label><textarea name="note" maxlength="1000"></textarea>${error}${foot('記録して在庫に反映')}</form>`);wire({id:id()})};
root.inventoryReverseForm=function(mid){show(`<h2>記録を訂正</h2><p>元の履歴は削除せず、数量を逆方向に戻す記録を追加します。正しい数量は改めて出荷・返却で登録してください。</p><form id="invForm"><label>訂正する人（必須）</label><input name="actor" required maxlength="60"><label>訂正日</label><input name="date" type="date" value="${today()}" max="${today()}" required><label>訂正理由（必須）</label><textarea name="note" required maxlength="1000"></textarea>${error}${foot('訂正を記録する')}</form>`);wire({kind:'reverse',reverse:mid,id:id()})};
window.addEventListener('storage',e=>{if(e.key===KEY){try{const parsed=e.newValue?JSON.parse(e.newValue):fresh();balances(parsed);data=parsed;loadError='';if(!document.querySelector('dialog[open]'))render()}catch{loadError='他の画面の保存内容を読み込めません。'}}});
})(typeof globalThis!=='undefined'?globalThis:this);



