/* Site media and daily KY. Browser-only prototype; no shared server persistence. */
const MEDIA_CATEGORIES=['施工前','施工中','施工後','足場','契約外追加足場','常用伝票','契約書','図面','その他'];
state.kyRecords=Array.isArray(state.kyRecords)?state.kyRecords:[];
const mediaFilters={};
const MEDIA_STORE='jinshou-site-media-v1';
function mediaRefresh(){const raw=localStorage.getItem(MEDIA_STORE);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data.files)||!Array.isArray(data.kyRecords))throw Error('資料の保存データを読み込めません');state.files=data.files;state.kyRecords=data.kyRecords}}
if(typeof localStorage!=='undefined'){if(!localStorage.getItem(MEDIA_STORE))localStorage.setItem(MEDIA_STORE,JSON.stringify({files:state.files,kyRecords:state.kyRecords}));mediaRefresh();window.addEventListener('storage',e=>{if(e.key===MEDIA_STORE){try{mediaRefresh();render()}catch{notify('資料の同期に失敗しました。再読み込みしてください')}}})}
function mediaToday(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())}
function kyStatus(sid,date=mediaToday()){let record=state.kyRecords.find(r=>r.site===sid&&r.date===date);return {registered:!!(record&&record.confirmed&&record.fileId&&record.hazard&&record.measure&&record.participants&&record.recorder),record}}
function mediaId(){return crypto.randomUUID()}
function mediaDateValid(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d}
function mediaRaster(type){return ['image/jpeg','image/png','image/webp','image/gif'].includes(type)}
function mediaFileValid(f,photo=false){return !!f&&f.size>0&&f.size<=25*1024*1024&&(mediaRaster(f.type)||(!photo&&(/\.(pdf|xlsx?|docx?)$/i.test(f.name)&&['application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword',''].includes(f.type))))}
async function mediaCommit(change){if(!navigator.locks)throw Error('安全な保存のため、この端末の対応ブラウザで開いてください');return navigator.locks.request(MEDIA_STORE,()=>{mediaRefresh();const oldFiles=state.files.slice(),oldKy=state.kyRecords.slice();try{change();localStorage.setItem(MEDIA_STORE,JSON.stringify({files:state.files,kyRecords:state.kyRecords}))}catch(e){state.files=oldFiles;state.kyRecords=oldKy;throw e}})}
function mediaButton(id,label='開く'){return `<button class="secondary" data-media-open="${esc(id)}" onclick="mediaOpen(this.dataset.mediaOpen)">${label}</button>`}
async function mediaBlob(id){const d=await db();return new Promise((resolve,reject)=>{let q=d.transaction('files').objectStore('files').get(id);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function mediaOpen(id){try{let f=await mediaBlob(id);if(!f&&!isNaN(Number(id)))f=await mediaBlob(Number(id));if(!f)throw Error('この端末には原本がありません');let u=URL.createObjectURL(f);if(mediaRaster(f.type)){show(`<h2>${esc(f.name)}</h2><img class="media-preview" src="${u}"><p><a href="${u}" download="${esc(f.name)}">原本を保存</a></p><button class="secondary" onclick="closeModal()">閉じる</button>`);$('modal').addEventListener('close',()=>URL.revokeObjectURL(u),{once:true})}else{const a=document.createElement('a');a.href=u;a.download=f.name||'資料';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);notify('原本をダウンロードします')}}catch(e){notify(e.message||'原本を開けませんでした')}}
function renderMedia(sid,kind){if(kind==='KY')return renderKy(sid);let filter=mediaFilters[sid+kind]||{},items=state.files.filter(f=>f.site===sid&&f.kind===kind),visible=items.filter(f=>(!filter.category||(f.category||'その他')===filter.category)&&(!filter.date||(f.capturedAt||'').slice(0,10)===filter.date)).sort((a,b)=>String(b.uploadedAt||b.date).localeCompare(String(a.uploadedAt||a.date)));let ks=kyStatus(sid);return `<section class="media-shell"><div class="section-head"><div><div class="eyebrow">PROJECT ARCHIVE</div><h2>${kind} <small>${items.length}件</small></h2></div><button class="primary" onclick="mediaUploadForm(${sid},'${kind}')">＋ ${kind}を追加</button></div><div class="media-filter"><select aria-label="分類で絞り込む" onchange="setMediaFilter(${sid},'${kind}','category',this.value)"><option value="">すべての分類</option>${MEDIA_CATEGORIES.map(c=>`<option ${filter.category===c?'selected':''}>${c}</option>`).join('')}</select><input aria-label="撮影日で絞り込む" type="date" value="${esc(filter.date||'')}" onchange="setMediaFilter(${sid},'${kind}','date',this.value)"><button class="secondary" onclick="clearMediaFilter(${sid},'${kind}')">絞り込み解除</button></div><p class="hint">撮影日時は登録者が入力した値です。未入力は「不明」と表示し、登録日時と区別します。</p><div class="media-gallery">${visible.map(f=>`<article class="media-card"><div class="media-thumb" ${mediaRaster(f.type)?`data-media-thumb="${esc(f.id)}"`:''}><span>${mediaRaster(f.type)?'PHOTO':'DOCUMENT'}</span></div><div class="media-card-body"><span class="pill">${esc(f.category||'その他')}</span><h3>${esc(f.name)}</h3><small>撮影日時：${esc(f.capturedAt?.replace('T',' ')||'不明')}</small><small>登録日時：${esc(f.uploadedAt?new Date(f.uploadedAt).toLocaleString('ja-JP'):f.date||'不明')}</small>${f.recorder?`<small>登録者：${esc(f.recorder)}</small>`:''}${mediaButton(f.id)}</div></article>`).join('')||'<div class="panel empty">該当するファイルはありません。</div>'}</div></section>`}
function setMediaFilter(sid,kind,key,value){(mediaFilters[sid+kind]||={})[key]=value;render()}
function clearMediaFilter(sid,kind){delete mediaFilters[sid+kind];render()}
async function hydrateMedia(){for(const el of document.querySelectorAll('[data-media-thumb]')){try{let f=await mediaBlob(el.dataset.mediaThumb);if(!f&&!isNaN(+el.dataset.mediaThumb))f=await mediaBlob(+el.dataset.mediaThumb);if(!el.isConnected||!f||!mediaRaster(f.type))continue;const u=URL.createObjectURL(f),img=new Image();img.alt='登録写真';img.onload=img.onerror=()=>URL.revokeObjectURL(u);img.src=u;el.replaceChildren(img)}catch{/* Missing local originals retain a neutral thumbnail. */}}}
function mediaUploadForm(sid,kind){show(`<h2>${kind}を追加</h2><form id="mediaUpload"><label>分類</label><select name="category">${MEDIA_CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select><label>撮影日時（分かる場合のみ・日本時間）</label><input type="datetime-local" name="capturedAt"><label>登録者（必須・試作用の入力）</label><input name="recorder" required maxlength="100"><label>ファイル（１件25MBまで・複数可）</label><input type="file" name="attachments" multiple required accept="${kind==='写真'?'.jpg,.jpeg,.png,.webp,.gif':'.jpg,.jpeg,.png,.webp,.gif,.pdf,.xls,.xlsx,.doc,.docx'}"><p class="hint">画像はブラウザで表示。PDF・Office資料は原本を保存して確認します。</p>${foot('登録する')}</form>`);$('mediaUpload').onsubmit=async e=>{e.preventDefault();let form=e.target,btn=form.querySelector('button.primary');if(btn.disabled)return;btn.disabled=true;try{const data=new FormData(form),files=Array.from(form.elements.attachments.files),recorder=String(data.get('recorder')).trim(),capturedAt=String(data.get('capturedAt'));if(!recorder||!files.length||files.some(f=>!mediaFileValid(f,kind==='写真')))throw Error('氏名と対応ファイルを確認してください（１件25MBまで）');if(capturedAt&&(!mediaDateValid(capturedAt.slice(0,10))||capturedAt.slice(0,10)>mediaToday()))throw Error('撮影日は今日以前の日付を指定してください');let metadata=[];for(const f of files){const id=mediaId();await storeFile(id,f);metadata.push({id,site:sid,kind,category:data.get('category'),capturedAt,recorder,name:f.name,type:f.type,uploadedAt:new Date().toISOString()})}await mediaCommit(()=>state.files.push(...metadata));if(form.isConnected)closeModal();render();notify('ファイルを登録しました')}catch(err){notify(err.message||'保存に失敗しました')}finally{btn.disabled=false}}}
function renderKy(sid){const records=state.kyRecords.filter(r=>r.site===sid).sort((a,b)=>b.date.localeCompare(a.date)),today=kyStatus(sid);return `<section class="media-shell"><div class="section-head"><div><div class="eyebrow">DAILY SAFETY RECORD</div><h2>毎日のKY・危険予知</h2></div><button class="primary" onclick="kyForm(${sid})">＋ KYを登録</button></div><div class="ky-banner ${today.registered?'complete':''}"><div><b>${mediaToday()} ／ ${today.registered?'登録済み':'未登録'}</b><small>作業日の記録が必要です。作業予定との自動照合は配置連携後に対応します。</small></div></div>${records.map(r=>`<details class="panel ky-record"><summary><b>${esc(r.date)}</b><span>${esc(r.recorder)} ／ 第${r.revision||1}版</span></summary><dl class="key-values"><dt>危険・注意点</dt><dd>${esc(r.hazard)}</dd><dt>対策・行動</dt><dd>${esc(r.measure)}</dd><dt>参加者</dt><dd>${esc(r.participants)}</dd></dl><div class="row">${mediaButton(r.fileId,'KY原本を開く')}<button class="secondary" data-ky-date="${esc(r.date)}" onclick="kyForm(${sid},this.dataset.kyDate)">記録を更新</button></div><p class="hint">記録日時 ${esc(new Date(r.updatedAt).toLocaleString('ja-JP'))} ／ KY実施確認済み</p>${r.history?.length?`<details><summary>更新履歴（${r.history.length}件）</summary>${r.history.map(h=>`<div class="item">第${h.revision}版 ／ ${esc(h.recorder)} ／ ${esc(new Date(h.updatedAt).toLocaleString('ja-JP'))}<p>危険：${esc(h.hazard)}<br>対策：${esc(h.measure)}<br>参加者：${esc(h.participants)}</p>${mediaButton(h.fileId,'この版の原本')}</div>`).join('')}</details>`:''}</details>`).join('')||'<div class="panel empty">KYの記録はまだありません。</div>'}</section>`}
function kyForm(sid,date=mediaToday()){mediaRefresh();const prior=kyStatus(sid,date).record||{};show(`<h2>KY・危険予知を${prior.date?'更新':'登録'}</h2><form id="kyForm"><label>作業日（必須）</label><input type="date" name="date" required max="${mediaToday()}" value="${esc(date)}" ${prior.date?'readonly':''}>${[['hazard','予想される危険・注意点'],['measure','危険に対する対策・行動'],['participants','参加者（複数名を入力）'],['recorder','記録者（試作用の入力）']].map(([k,l])=>`<label>${l}（必須）</label><textarea name="${k}" required maxlength="4000">${esc(prior[k]||'')}</textarea>`).join('')}<label>KYの写真または資料 ${prior.fileId?'（更新時は省略すると現在の原本を維持）':'（必須）'}</label><input type="file" name="attachment" accept=".jpg,.jpeg,.png,.webp,.gif,.pdf,.xls,.xlsx,.doc,.docx" ${prior.fileId?'':'required'}><label class="ky-confirm"><input type="checkbox" name="confirmed" required> 危険予知を実施しました</label><p class="hint">１現場・１日につき１記録。更新前の内容と原本は履歴に残ります。</p>${foot('KYを記録する')}</form>`);$('kyForm').onsubmit=async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('button.primary');if(btn.disabled)return;btn.disabled=true;try{const d=Object.fromEntries(new FormData(form));for(const k of ['hazard','measure','participants','recorder'])if(!String(d[k]||'').trim())throw Error('必須項目を入力してください');if(!mediaDateValid(d.date)||d.date>mediaToday()||!form.elements.confirmed.checked)throw Error('作業日と実施確認を確認してください');const current=kyStatus(sid,d.date).record;if(current!== (prior.date?prior:undefined))throw Error('この日の記録は既にあります。閉じて記録を更新してください');const f=form.elements.attachment.files[0];if(f&&!mediaFileValid(f))throw Error('25MB以内の画像・PDF・Office資料を選んでください');if(!f&&(!current?.fileId||!await mediaBlob(current.fileId)))throw Error('KY原本が見つかりません。写真または資料を再添付してください');let fileId=current?.fileId;if(f){fileId=mediaId();await storeFile(fileId,f)}if(kyStatus(sid,d.date).record!==current)throw Error('この日の記録が更新されました。閉じて再度確認してください');const history=current?[...(current.history||[]),{...current,history:undefined}]:[];const record={site:sid,date:d.date,hazard:d.hazard.trim(),measure:d.measure.trim(),participants:d.participants.trim(),recorder:d.recorder.trim(),confirmed:true,fileId,revision:(current?.revision||0)+1,history,updatedAt:new Date().toISOString()};await mediaCommit(()=>{const latest=kyStatus(sid,d.date).record;if(JSON.stringify(latest)!==JSON.stringify(current))throw Error('この日の記録が別の画面で更新されました。閉じて再度確認してください');state.kyRecords=state.kyRecords.filter(r=>!(r.site===sid&&r.date===d.date));state.kyRecords.push(record)});if(form.isConnected)closeModal();render();notify('KYを記録しました')}catch(err){notify(err.message||'KY保存に失敗しました')}finally{btn.disabled=false}}}

// Keep the original schedule upload interface while saving through the media namespace.
uploadFile=async function(f){if(!f)return;const sid=siteId,kind=tab,id=Date.now()*1000+crypto.getRandomValues(new Uint32Array(1))[0]%1000;try{if(!mediaFileValid(f,kind==='写真'))throw Error('25MB以内の対応ファイルを選んでください');await storeFile(id,f);await mediaCommit(()=>state.files.push({id,site:sid,kind,name:f.name,type:f.type,date:new Date().toLocaleString('ja-JP'),uploadedAt:new Date().toISOString()}));render();notify('ファイルを保存しました')}catch(e){notify(e.message||'ファイル保存に失敗しました')}};

