// Standalone prototype: local records, never interpreted as production attendance.
const originalRender=render, originalSiteForm=siteForm;
state.visits ||= [];
if(!state.premiumSeeded&&!mainStorageError){
 state.sites.forEach(s=>Object.assign(s,{createdBy:'山田 太郎（サンプル）',createdAt:'2026-09-01',structure:'鉄筋コンクリート造（RC造）',parking:'北側の指定駐車区画。搬入口前への駐車は禁止。',workHours:'8:00～17:00',weekend:'事前に元請け担当者へ確認',smoking:'指定の喫煙場所のみ可',locations:[]}));
 state.visits.push({id:1001,site:1,date:'2026-09-14',name:'山田 太郎',affiliation:'迅翔興業',work:'手すり取付・仕上げ確認',source:'サンプル記録'},{id:1002,site:1,date:'2026-09-12',name:'佐藤 花子',affiliation:'迅翔興業',work:'共用部の現場確認',source:'サンプル記録'},{id:1003,site:1,date:'2026-09-12',name:'高橋 健',affiliation:'協力会社（サンプル）',work:'ベランダ施工',source:'サンプル記録'});
 state.reports.push({id:2001,site:1,title:'2階ベランダの施工状況',note:'手すりの取付が完了。塗装の補修箇所を手直し案件に登録しました。（サンプル）',date:'2026/9/14 16:30'},{id:2002,site:2,title:'南面の現場確認',note:'作業前の確認を実施しました。（サンプル）',date:'2026/9/14 09:00'});
 state.tasks.push({id:3001,site:2,title:'足場点検の記録を確認',done:false});state.premiumSeeded=true;save();
}
const pinIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
function mapUrl(address){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address)}
function safePlaceUrl(value){try{const u=new URL(value);const host=u.hostname.toLowerCase();if(u.protocol!=='https:')return '';if(host==='maps.app.goo.gl'||host==='maps.apple.com'||host==='goo.gl'&&u.pathname.startsWith('/maps')||(host==='google.com'||host.endsWith('.google.com')||host==='google.co.jp'||host.endsWith('.google.co.jp'))&&(u.pathname.startsWith('/maps')||host.startsWith('maps.')))return u.href;return ''}catch{return ''}}
function phoneLink(p){const n=String(p||'').replace(/[^\d+]/g,'');return n?`<a class="phone-link" href="tel:${esc(n)}">${esc(p)} ↗</a>`:'<span class="meta">電話未登録</span>'}
function art(s){let i=s.id%3;return `<svg viewBox="0 0 600 260" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="sky${s.id}" x2="1" y2="1"><stop stop-color="#9eafc5"/><stop offset="1" stop-color="#e2e8ef"/></linearGradient><linearGradient id="face${s.id}" x2="1" y2=".2"><stop stop-color="#486583"/><stop offset="1" stop-color="#7e94ac"/></linearGradient></defs><rect width="600" height="260" fill="url(#sky${s.id})"/><path d="M0 210L600 180V260H0Z" fill="#738aa3"/><path d="M${120+i*15} 260V${50+i*15}L${350+i*20} 10V260Z" fill="#d6dee8"/><path d="M${350+i*20} 10L520 65V260H${350+i*20}Z" fill="url(#face${s.id})"/>${Array.from({length:6},(_,r)=>`<path d="M${120+i*15} ${75+r*32}L${350+i*20} ${35+r*35}L520 ${87+r*29}" fill="none" stroke="#3b5575" stroke-width="9"/>`).join('')}${Array.from({length:7},(_,c)=>`<path d="M${147+c*28} 57V260" stroke="#f3f5f8" stroke-width="5" opacity=".8"/>`).join('')}<path d="M0 0H600V260H0Z" fill="#112947" opacity=".25"/><path d="M0 0H600V260H0Z" fill="#0c2140" opacity=".13"/></svg>`}
function projectCard(s){let repairs=state.repairs.filter(r=>r.site===s.id&&r.status!=='完了').length,tasks=state.tasks.filter(t=>t.site===s.id&&!t.done).length,reports=state.reports.filter(r=>r.site===s.id).length;return `<article class="project-card" data-site-id="${s.id}" data-search="${esc(s.name+' '+s.address+' '+(company(s.prime)?.name||''))}"><div class="project-art">${art(s)}<span class="art-label">JINSHOU / PROJECT</span><span class="art-num">${String(s.id).slice(-3).padStart(3,'0')}</span></div><div class="project-info">${pill(s.status)}<h2><button class="text-action" style="font-size:inherit;color:inherit;font-weight:inherit;text-align:left" onclick="openSite(${s.id})">${esc(s.name)}</button></h2><div class="meta">${esc(s.address)}<br>${esc(s.start)} — ${esc(s.end)}</div><div class="project-company">元請け　${esc(company(s.prime)?.name||'未登録')}</div><div class="project-counts"><button class="${repairs?'attention':''}" onclick="goTab(${s.id},'手直し案件')"><span>未完了の手直し</span><b>${repairs}</b><small>件</small></button><button onclick="goTab(${s.id},'タスク')"><span>未完了タスク</span><b>${tasks}</b><small>件</small></button><button onclick="goTab(${s.id},'報告')"><span>報告・累計</span><b>${reports}</b><small>件</small></button></div><button class="project-open" onclick="openSite(${s.id})"><span>現場の詳細を見る</span><span>↗</span></button></div></article>`}
function goTab(id,t){siteId=id;page='detail';tab=t;render()}
function visitRecords(id){return state.visits.filter(v=>v.site===id).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)}
function peopleBlock(s,k,title){let c=company(s[k]);return `<div class="contact-head"><div class="company-icon">▥</div><div><span class="contact-role">${title}</span><h2 style="margin:5px 0">${esc(c?.name||'未登録')}</h2>${c?.phone?phoneLink(c.phone):''}</div></div>${(s[k+'People']||[]).map(n=>{let p=c?.people.find(p=>p.name===n);return `<div class="contact-person"><div><b>${esc(n)}</b><small>${esc(p?.dept)}</small></div><div>${phoneLink(p?.phone)}${p?.email?`<a href="mailto:${esc(p.email)}">${esc(p.email)}</a>`:''}</div></div>`}).join('')||'<p>担当者未登録</p>'}`}
function places(s){return ['コンビニ','トイレ','駐車場','ホームセンター'].map(kind=>{let p=(s.locations||[]).find(x=>x.kind===kind),url=p&&(safePlaceUrl(p.url)||(!p.url&&p.address?mapUrl(p.address):''));return url?`<a class="place-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${pinIcon}<span><b>${kind} ↗</b><small>${esc(p.name||p.address||'登録した地図を開く')}</small></span></a>`:`<button class="place-link disabled" onclick="locationForm(${s.id})">${pinIcon}<span><b>${kind}</b><small>位置情報を登録</small></span></button>`}).join('')}
function visitsPanel(s,full=false){let vs=visitRecords(s.id),names=[...new Set(vs.map(v=>v.name))];return `<section class="panel"><div class="section-head"><h2>${full?'入場・作業の履歴':'この現場に来た人'}</h2>${full?`<button class="secondary" onclick="visitForm(${s.id})">＋ 履歴を登録</button>`:`<button class="text-action" onclick="goTab(${s.id},'入場履歴')">すべて見る →</button>`}</div><div class="visit-avatars">${names.slice(0,8).map(n=>`<span class="avatar" title="${esc(n)}">${esc(n.slice(0,1))}</span>`).join('')}</div><p>${names.length}名・${vs.length}件の記録</p>${(full?vs:vs.slice(0,3)).map(v=>`<div class="visit-line"><span class="avatar">${esc(v.name.slice(0,1))}</span><div><b>${esc(v.name)} <small>${esc(v.affiliation)}</small></b><small>${esc(v.date)}　${esc(v.work)}</small><br><span class="visit-source">${esc(v.source)}</span></div></div>`).join('')||'<div class="empty">入場履歴はまだありません。</div>'}<p class="hint">現在はサンプルと手動登録の履歴です。配置予定と実際の入場は分け、将来の日報連携で実績を記録します。</p></section>`}
function overview(s){return `<div class="detail-grid"><div class="stack"><section class="panel"><div class="section-head"><h2>現場概要</h2><button class="secondary" onclick="siteForm(${s.id})">編集する</button></div>${s.address?`<a class="map-address" href="${esc(mapUrl(s.address))}" target="_blank" rel="noopener noreferrer"><span>${esc(s.address)}<br><small>地図を開く</small></span><span>↗</span></a>`:''}<dl class="key-values"><dt>案件名</dt><dd>${esc(s.name)}</dd><dt>工期</dt><dd>${esc(s.start)} ～ ${esc(s.end)}</dd><dt>建物構造</dt><dd>${esc(s.structure||'未登録')}</dd><dt>案件作成者</dt><dd>${esc(s.createdBy||'未登録')}</dd><dt>案件作成日</dt><dd>${esc(s.createdAt||'未登録')}</dd><dt>備考</dt><dd>${esc(s.note||'未登録')}</dd></dl></section><section class="panel"><div class="section-head"><h2>周辺施設・アクセス</h2><button class="text-action" onclick="locationForm(${s.id})">位置情報を編集 →</button></div><div class="location-grid">${places(s)}</div><p class="hint">住所または地図の共有URLを登録。タップするとマップが開きます。</p></section><section class="panel"><div class="section-head"><h2>施工に関する注意点</h2><button class="text-action" onclick="siteForm(${s.id})">編集する →</button></div><dl class="key-values">${[['parking','駐車スペース'],['workHours','作業可能時間'],['weekend','土日・休日'],['smoking','喫煙ルール']].map(([k,l])=>`<dt>${l}</dt><dd>${esc(s[k]||'未登録')}</dd>`).join('')}</dl></section></div><div class="stack"><section class="panel"><div class="section-label">CLIENT CONTACTS</div>${peopleBlock(s,'prime','元請け')}<hr style="border:0;border-top:1px solid var(--line);margin:24px 0">${peopleBlock(s,'client','発注者')}</section>${visitsPanel(s)}<section class="panel"><h2>この現場の確認事項</h2><div class="mini-metrics"><button onclick="goTab(${s.id},'手直し案件')">手直し ${state.repairs.filter(r=>r.site===s.id&&r.status!=='完了').length}件</button><button onclick="goTab(${s.id},'タスク')">未完了タスク ${state.tasks.filter(t=>t.site===s.id&&!t.done).length}件</button><button onclick="goTab(${s.id},'報告')">報告 ${state.reports.filter(r=>r.site===s.id).length}件</button></div>${repairList(state.repairs.filter(r=>r.site===s.id&&r.status!=='完了'),true)}</section></div></div>`}
render=function(){originalRender();if(page==='sites'){$('app').innerHTML=`<section class="command-hero"><div><div class="eyebrow">JINSHOU CONSTRUCTION / PROJECT WORKSPACE</div><h1>現場を見渡す。</h1><p>進捗、連絡、品質。現場を動かす情報を、ひとつに。</p></div><div class="hero-actions"><button class="primary" onclick="siteForm()">＋ 新しい現場</button></div></section><div class="overview-stats">${[['施工中の現場',state.sites.filter(s=>s.status==='施工中').length],['未完了の手直し',state.repairs.filter(r=>r.status!=='完了').length],['未完了タスク',state.tasks.filter(t=>!t.done).length],['現場からの報告・累計',state.reports.length]].map(([l,n])=>`<div class="overview-stat"><label>${l}</label><strong>${n}</strong><small>件</small></div>`).join('')}</div><div class="section-head"><div><div class="eyebrow">PROJECT DIRECTORY</div><h2 style="margin-top:8px">現場一覧 <span class="meta">/ ${state.sites.length}件</span></h2></div><input class="search" aria-label="現場を検索" placeholder="現場名・住所・元請けで検索" oninput="filterCards(this.value)"></div><div class="project-grid">${state.sites.map(projectCard).join('')}</div><div class="empty no-results">該当する現場がありません。</div><p class="hint">表示している建物はイメージ図です。会社・人物・履歴はサンプルです。</p>`}
if(page==='detail'){let s=state.sites.find(s=>s.id===siteId);let names=['概要','関連','工程表','タスク','報告','写真','資料','手直し案件','入場履歴'];let tabs=$('app').querySelector('.tabs');tabs.innerHTML=names.map(t=>`<button class="${tab===t?'active':''}" onclick="goTab(${s.id},'${t}')">${t}${t==='手直し案件'?' '+state.repairs.filter(r=>r.site===s.id&&r.status!=='完了').length:''}</button>`).join('');if(['概要','関連','入場履歴'].includes(tab)){while(tabs.nextSibling)tabs.nextSibling.remove();let content=document.createElement('div');if(tab==='概要')content.innerHTML=overview(s);if(tab==='入場履歴')content.innerHTML=visitsPanel(s,true);if(tab==='関連'){let related=s.prime?state.sites.filter(x=>x.id!==s.id&&x.prime===s.prime):[];content.innerHTML=`<div class="section-head"><div><h2>同じ元請けの現場</h2><p>${esc(company(s.prime)?.name||'元請け未登録')} ${s.prime?'／ '+related.length+'件':''}</p></div></div><div class="project-grid">${related.map(projectCard).join('')}</div>${!related.length?'<div class="panel empty">同じ元請けのほかの現場はありません。</div>':''}`;}tabs.after(content)}}if(page==='customers'){document.querySelectorAll('.table').forEach(table=>{table.querySelectorAll('tbody tr').forEach(tr=>{tr.children[1].innerHTML=phoneLink(tr.children[1].textContent)});let wrap=document.createElement('div');wrap.className='table-wrap';table.before(wrap);wrap.append(table)})}};
siteForm=function(id){originalSiteForm(id);let s=state.sites.find(s=>s.id===id)||{},form=$('siteForm'),oldSubmit=form.onsubmit,section=document.createElement('section');section.className='form-section';section.innerHTML=`<h3>現場の詳細・施工条件</h3>${[['structure','建物構造'],['parking','駐車スペース・駐車場所'],['workHours','作業可能時間'],['weekend','土日・休日の工事'],['smoking','喫煙ルール']].map(([k,l])=>`<div class="field"><label>${l}</label><input name="${k}" value="${esc(s[k]||'')}"></div>`).join('')}${!id?'<label>案件作成者（試作用・必須）</label><input name="createdBy" required placeholder="氏名を入力">':'<p class="hint">案件作成者・作成日は既存の記録を維持します。</p>'}`;form.querySelector('.modalfoot').before(section);form.onsubmit=e=>{if(!id){let input=document.createElement('input');input.type='hidden';input.name='createdAt';input.value=new Date().toLocaleDateString('sv-SE');form.append(input)}oldSubmit(e)}};
function locationForm(id){let s=state.sites.find(s=>s.id===id);show(`<h2>周辺施設の位置情報</h2><p>各施設の住所、または Google マップ・Apple マップの共有URLを登録します。</p><form id="locationForm">${['コンビニ','トイレ','駐車場','ホームセンター'].map((kind,i)=>{let p=(s.locations||[]).find(p=>p.kind===kind)||{};return `<section class="form-section"><h3>${kind}</h3><label>名称・目印</label><input name="name${i}" value="${esc(p.name||'')}" placeholder="施設名、駐車区画など"><label>住所</label><input name="address${i}" value="${esc(p.address||'')}"><label>地図の共有URL（指定すると住所より優先）</label><input name="url${i}" value="${esc(p.url||'')}" placeholder="https://maps.app.goo.gl/…"></section>`}).join('')}${foot()}</form>`);$('locationForm').onsubmit=e=>{e.preventDefault();let d=new FormData(e.target),ls=[];for(let [i,kind]of ['コンビニ','トイレ','駐車場','ホームセンター'].entries()){let p={kind,name:d.get('name'+i).trim(),address:d.get('address'+i).trim(),url:d.get('url'+i).trim()};if(p.url&&!safePlaceUrl(p.url)){notify(kind+'：Google マップか Apple マップのHTTPS共有URLを指定してください');return}if(p.name&&!p.address&&!p.url){notify(kind+'：住所か地図URLも入力してください');return}if(p.address||p.url)ls.push(p)}s.locations=ls;save();closeModal();render();notify('周辺施設を保存しました')}}
function visitForm(id){show(`<h2>入場・作業履歴を登録</h2><div class="notice">試作の手動記録です。配置カレンダーや日報とはまだ連携していません。</div><form id="visitForm"><label>実際に現場へ行った日（必須）</label><input name="date" type="date" required max="${new Date().toLocaleDateString('sv-SE')}" value="${new Date().toLocaleDateString('sv-SE')}"><label>氏名（必須）</label><input name="name" required><label>所属会社</label><input name="affiliation"><label>作業・訪問内容（必須）</label><textarea name="work" required></textarea>${foot('履歴に記録する')}</form>`);$('visitForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(!d.name.trim()||!d.work.trim()){notify('氏名と作業内容を入力してください');return}state.visits.push({...d,id:Date.now(),site:id,source:'手動登録（試作）',recordedAt:new Date().toISOString()});save();closeModal();render();notify('入場履歴を記録しました')}}
render();
