(function(){'use strict';
let generation=0;const actor=()=>{const a=window.portalSession?.identity();return window.portalSession?.connected()&&a?.code?JSON.stringify([a.kind||'employee',a.code]):''};
function formHTML(saved={}){const months=saved.rows||Array.from({length:12},(_,i)=>({month:new Date().getFullYear()+'-'+String(i+1).padStart(2,'0'),bill:'',paid:'',lease1:'',lease2:'',lease3:'',labor:''}));return `<section class="panel"><h2>現場の利益管理表</h2><p class="notice">社長権限で共有保存します。配置カレンダーの予定人工を利益表に自動表示します。指定単価の費用対象と請求額区分を選んだ月だけ、配置ベース概算を示します。</p><form id="profitDraft"><div class="row"><label>請負金額（円）<input name="contract" type="number" min="0" value="${esc(saved.contract||'')}"></label><label>1人工の固定費（円）<input name="fixed" type="number" min="0" value="${esc(saved.fixed??'')}"></label><label>1人工の給与単価（円）<input name="wage" type="number" min="0" value="${esc(saved.wage??'')}"></label></div><div class="stock-scroll"><table class="stock-sheet" style="min-width:1250px"><thead><tr>${['月','請求額','入金額','未入金','リース①','リース②','リース③','人工','請求−リース','固定費控除後','給与控除後','入金ベース残額'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${months.map((r,i)=>`<tr data-profit-row>${['month','bill','paid','lease1','lease2','lease3','labor'].map((k,j)=>`${j===3?'<td data-calc="unpaid"></td>':''}<td><input aria-label="${i+1}行目 ${k}" data-field="${k}" type="${k==='month'?'month':'number'}" ${k==='month'?'':'min="0" step="any"'} value="${esc(r[k])}" style="width:${k==='month'?130:100}px"></td>`).join('')}<td data-calc="net"></td><td data-calc="fixed"></td><td data-calc="profit"></td><td data-calc="cash"></td></tr>`).join('')}</tbody><tfoot><tr><th colspan="11">給与控除後残額 合計（請求ベース）</th><td id="profitSum"></td></tr></tfoot></table></div><p>手入力表の請求ベース＝請求−リース−人工×固定費単価−人工×給与単価。入金ベースは請求額を入金額に置き換えます。請求・人工の空欄はこの手入力表で0扱い、単価の空欄は利益未計算です。配置予定人工と請求原本は別列で自動表示し、旧手入力値は比較用に残します。</p><button class="primary" type="submit">入力内容を共有先に保存</button><span id="profitSaved" role="status"></span></form></section>`}
window.profitPanel=sid=>'<section class="panel" id="sharedProfit" data-site="'+esc(String(sid))+'"><h2>現場の利益管理表</h2><p data-profit-load role="status">社長権限と保存内容を確認中…</p></section>';
function wireForm(f,key,revision,owner,ticket){
 const calculate=()=>{let sum=0,complete=true;const ratesSet=f.elements.fixed.value!==''&&f.elements.wage.value!=='';f.querySelectorAll('[data-profit-row]').forEach(row=>{const val=k=>Number(row.querySelector('[data-field="'+k+'"]').value)||0,lease=val('lease1')+val('lease2')+val('lease3'),cost=val('labor')*Number(f.elements.fixed.value),pay=val('labor')*Number(f.elements.wage.value),net=val('bill')-lease,result={unpaid:val('bill')-val('paid'),net,fixed:ratesSet?net-cost:null,profit:ratesSet?net-cost-pay:null,cash:ratesSet?val('paid')-lease-cost-pay:null};if(ratesSet)sum+=result.profit;else complete=false;for(const [k,n]of Object.entries(result)){const c=row.querySelector('[data-calc="'+k+'"]');c.textContent=n===null?'単価未設定':n.toLocaleString();c.style.color=n===null?'':n<0?'#b32626':'#175b45'}});$('profitSum').textContent=complete?sum.toLocaleString()+'円':'単価未設定'};f.oninput=calculate;calculate();
 const feedback=f.querySelector('#profitSaved'),button=f.querySelector('[type=submit]');let saving=false;const alive=()=>f.isConnected&&actor()===owner&&generation===ticket;const opKey=siteSharedStore.key('__company__','利益管理',key);const compare=document.createElement('button');compare.type='button';compare.className='secondary';compare.textContent='最新の内容と比較';compare.hidden=true;f.append(compare);const comparison=document.createElement('section');f.append(comparison);const snapshot=()=>({contract:f.elements.contract.value,fixed:f.elements.fixed.value,wage:f.elements.wage.value,ratePurpose:f.elements.ratePurpose.value,invoiceBasis:f.elements.invoiceBasis.value,rows:[...f.querySelectorAll('[data-profit-row]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value])))});
 compare.onclick=async()=>{if(saving)return;compare.disabled=true;comparison.replaceChildren();try{const rows=await siteSharedStore.list('__company__','利益管理'),pending=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;const latest=rows.find(r=>r.id===key),latestRevision=Number(latest?.revision||0),input=snapshot(),saved=latest?.payload||{},requestId=pending?.requestId;const labels={contract:'請負金額',fixed:'固定費単価',wage:'給与単価',ratePurpose:'指定単価を差し引く人工区分',invoiceBasis:'概算に使う請求額'};const display=(k,v)=>({ratePurpose:{own:'自社社員',external:'外注',both:'自社社員と外注'},invoiceBasis:{manual:'旧手入力の請求額',salesExcl:'請求原本・税抜',salesIncl:'請求原本・税込'}}[k]?.[v]||v||'未設定');let table='<h3>保存済みの最新版と今回の入力</h3><p>最新版 第'+latestRevision+'版を確認し、下のボタンで今回の入力を保存し直します。</p><div style="overflow:auto"><table><thead><tr><th>項目</th><th>保存済みの最新版</th><th>今回の入力</th></tr></thead><tbody>';for(const [k,label]of Object.entries(labels))table+='<tr><th>'+label+'</th><td>'+esc(display(k,saved[k]))+'</td><td>'+esc(display(k,input[k]))+'</td></tr>';const fields={month:'月',bill:'請求',paid:'入金',lease1:'リース①',lease2:'リース②',lease3:'リース③',labor:'人工'};for(let i=0;i<Math.max(saved.rows?.length||0,input.rows.length);i++)for(const [k,label]of Object.entries(fields))table+='<tr><th>'+(i+1)+'行目 '+label+'</th><td>'+esc(saved.rows?.[i]?.[k]||'未入力')+'</td><td>'+esc(input.rows[i]?.[k]||'未入力')+'</td></tr>';comparison.innerHTML=table+'</tbody></table></div>';const resave=document.createElement('button');resave.type='button';resave.className='primary';resave.textContent='この入力で保存し直す';comparison.append(resave);resave.onclick=async()=>{if(saving||!alive())return;if(JSON.stringify(snapshot())!==JSON.stringify(input)){feedback.textContent='入力が変わりました。最新の内容ともう一度比較してください。';comparison.replaceChildren();return}resave.disabled=true;compare.disabled=true;button.disabled=true;saving=true;let handed=false;const locked=[...f.querySelectorAll('input,select')];locked.forEach(i=>i.disabled=true);try{const now=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;if((now?.requestId||null)!==(requestId||null))throw Error('未送信記録が変わりました。もう一度比較してください');if(requestId)await siteSharedStore.resolvePending(opKey,requestId);if(!alive())return;revision=latestRevision;comparison.replaceChildren();saving=false;locked.forEach(i=>i.disabled=false);handed=true;f.requestSubmit();}catch(e){if(alive()){feedback.textContent=e.message+' 入力はこの画面に残しています。';comparison.replaceChildren();}}finally{if(!handed){saving=false;if(alive()){button.disabled=false;locked.forEach(i=>i.disabled=false);}}if(alive())compare.disabled=false;}};}catch(e){if(alive())feedback.textContent=e.message+' 入力はこの画面に残しています。';}finally{if(alive())compare.disabled=false;}};
 f.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;button.disabled=true;feedback.textContent='保存中…';
 const value={contract:f.elements.contract.value,fixed:f.elements.fixed.value,wage:f.elements.wage.value,ratePurpose:f.elements.ratePurpose.value,invoiceBasis:f.elements.invoiceBasis.value,rows:[...f.querySelectorAll('[data-profit-row]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value])))};
 const inputs=[...f.querySelectorAll('input,select')];inputs.forEach(i=>i.disabled=true);
 try{if(actor()!==owner||generation!==ticket)throw Error('ログインが変わりました。開き直してください');const result=await siteSharedStore.save('__company__','利益管理',key,value,{revision});if(!f.isConnected||actor()!==owner||generation!==ticket)return;revision=Number(result.revision);feedback.textContent='共有先に保存しました';compare.hidden=true;comparison.replaceChildren();}
 catch(e){if(f.isConnected&&actor()===owner&&generation===ticket){feedback.textContent=e.message+' 入力はこの画面に残しています。';compare.hidden=false;}}
 finally{saving=false;if(f.isConnected){button.disabled=false;inputs.forEach(i=>i.disabled=false);}}
 };
}
function wireAuto(f,saved={}){
 const rateValues=['','own','external','both'],invoiceValues=['','manual','salesExcl','salesIncl'];
 const choices=document.createElement('div');choices.className='row';choices.innerHTML='<label>指定単価を差し引く人工区分 <select name="ratePurpose"><option value="">未設定（概算しない）</option><option value="own">自社社員</option><option value="external">外注</option><option value="both">自社社員と外注</option></select></label><label>概算に使う請求額 <select name="invoiceBasis"><option value="">未設定（概算しない）</option><option value="manual">旧手入力の請求額</option><option value="salesExcl">明示リンクした請求原本・税抜</option><option value="salesIncl">明示リンクした請求原本・税込</option></select></label>';
 f.querySelector('.stock-scroll').before(choices);f.elements.ratePurpose.value=rateValues.includes(saved.ratePurpose)?saved.ratePurpose:'';f.elements.invoiceBasis.value=invoiceValues.includes(saved.invoiceBasis)?saved.invoiceBasis:'';
 const th=[...f.querySelectorAll('thead th')].find(x=>x.textContent==='人工');th.textContent='旧手入力人工・比較用';th.insertAdjacentHTML('beforebegin','<th>配置予定人工（自動）</th><th>請求原本（自動）</th><th>配置ベース概算残額</th>');[...f.querySelectorAll('thead th')].find(x=>x.textContent==='給与控除後').textContent='旧手入力残額・比較用';f.querySelector('tfoot th').colSpan=14;f.querySelector('tfoot th').textContent='旧手入力残額 合計（比較用）';
 const note=document.createElement('p');note.textContent='配置ベース概算残額＝選択した請求額−手入力リース−指定単価×選択した予定人工。材料費など未連携の費用は控除していないため、確定利益ではありません。旧手入力人工・請求額と原本は並べて確認し、自動で上書きしません。選択した区分は共有保存してください。';choices.after(note);
 const total=document.createElement('p');total.setAttribute('data-auto-total','');f.querySelector('.stock-scroll').after(total);
 for(const row of f.querySelectorAll('[data-profit-row]'))row.querySelector('[data-field=labor]').closest('td').insertAdjacentHTML('beforebegin','<td data-auto-labor>取得前</td><td data-auto-bill>取得前</td><td data-auto-profit>取得前</td>');
 const calc=()=>{let totalValue=0,complete=true;const purpose=f.elements.ratePurpose.value,basis=f.elements.invoiceBasis.value,rate=f.dataset.sourceRegion==='inside'?23000:f.dataset.sourceRegion==='outside'?26000:null;
  for(const row of f.querySelectorAll('[data-profit-row]')){const labor=row.querySelector('[data-auto-labor]'),billCell=row.querySelector('[data-auto-bill]'),result=row.querySelector('[data-auto-profit]');const own=Number(row.dataset.sourceOwn||0),external=Number(row.dataset.sourceExternal||0);labor.textContent=row.dataset.sourceReady==='1'?'自社 '+own.toLocaleString('ja-JP',{maximumFractionDigits:3})+'／外注 '+external.toLocaleString('ja-JP',{maximumFractionDigits:3}):'未連携';const count=Number(row.dataset.sourceBillCount||0);billCell.textContent=row.dataset.salesReady==='1'?(count?count+'件・税抜 '+Number(row.dataset.sourceBillExcl).toLocaleString()+'円／税込 '+Number(row.dataset.sourceBillIncl).toLocaleString()+'円':'リンクなし'):'未読込';let why='';if(row.dataset.sourceReady!=='1')why='配置未連携';else if(!purpose)why='費用対象未設定';else if(rate===null)why='県内外未確認';else if(!basis)why='請求額区分未設定';else if(basis==='manual'&&row.querySelector('[data-field=bill]').value==='')why='手入力請求額未設定';else if(basis!=='manual'&&(row.dataset.salesReady!=='1'||!count))why='原本リンク未設定';if(why){result.textContent=why;complete=false;continue}const sourceBill=basis==='manual'?Number(row.querySelector('[data-field=bill]').value):Number(row.dataset[basis==='salesExcl'?'sourceBillExcl':'sourceBillIncl']);const usedUnits=purpose==='own'?own:purpose==='external'?external:own+external;const lease=['lease1','lease2','lease3'].reduce((n,k)=>n+Number(row.querySelector('[data-field='+k+']').value||0),0);const value=sourceBill-lease-usedUnits*rate;result.textContent=value.toLocaleString('ja-JP',{maximumFractionDigits:0})+'円';result.style.color=value<0?'#b32626':'#175b45';totalValue+=value}total.textContent=complete?'配置ベース概算残額 合計 '+totalValue.toLocaleString('ja-JP',{maximumFractionDigits:0})+'円':'配置ベース概算は未確定の月があります。'};
 f.addEventListener('input',calc);f.addEventListener('change',calc);f.refreshAuto=calc;calc();
}
function wireSources(box,key,owner,ticket){
 const panel=document.createElement('section');panel.className='panel';panel.id='profitPlacementSource';
 panel.innerHTML='<h3>配置予定人工・請求原本</h3><p>配置カレンダーの予定値です。出勤実績や利益額ではありません。</p><div class="row"><label>年 <input type="number" data-source-year min="2000" max="2100" value="'+new Date().getFullYear()+'"></label><label>請求月 <input type="month" data-sales-month value="'+new Date().toISOString().slice(0,7)+'"></label><button type="button" class="secondary" data-source-refresh>再読込</button></div><p data-source-status role="status">読込中…</p><div data-source-rows></div><div data-sales-rows></div>';
 box.append(panel);
 const alive=()=>panel.isConnected&&actor()===owner&&generation===ticket;
 const status=panel.querySelector('[data-source-status]'),source=panel.querySelector('[data-source-rows]'),sales=panel.querySelector('[data-sales-rows]');
 const money=n=>Number(n).toLocaleString('ja-JP')+'円';
 const units=n=>Number(n).toLocaleString('ja-JP',{maximumFractionDigits:3});
 let loading=false,rerun=false;
 const filters=()=>JSON.stringify([panel.querySelector('[data-source-year]').value,panel.querySelector('[data-sales-month]').value,...box.querySelectorAll('[data-profit-row] [data-field=month]')].map(x=>x?.value??x));
 async function refresh(){if(!alive())return;const f=box.querySelector('#profitDraft');f.dataset.sourceRegion='';for(const row of f.querySelectorAll('[data-profit-row]')){row.dataset.sourceReady='0';row.dataset.salesReady='0';row.dataset.sourceBillCount='0'}f.refreshAuto();if(loading){rerun=true;return}const selection=filters(),year=Number(panel.querySelector('[data-source-year]').value),month=panel.querySelector('[data-sales-month]').value;if(!Number.isInteger(year)||year<2000||year>2100||!/^20\d\d-(0[1-9]|1[0-2])$/.test(month)){status.textContent='年と請求月を確認してください';return}loading=true;status.textContent='配置予定と請求原本を確認中…';source.replaceChildren();sales.replaceChildren();const current=()=>alive()&&filters()===selection;try{
  const placement=await portalSession.call('profitPlacementSource',{p_site_key:key,p_year:year});if(!current()){rerun=alive();return}
  if(!placement?.linked){status.textContent='現場マスターとの明示リンクが未設定です。配置予定・請求原本を紐付けられません。';return}
  const rate=placement.region==='inside'?'県内 23,000円':placement.region==='outside'?'県外 26,000円':'県内・県外未確認';f.dataset.sourceRegion=placement.region;
  const monthRows=[...f.querySelectorAll('[data-profit-row]')];for(const formRow of monthRows){const period=formRow.querySelector('[data-field=month]').value,planned=placement.months.find(x=>x.month===period);formRow.dataset.sourceReady=planned?'1':'0';formRow.dataset.sourceOwn=planned?.ownUnits??'';formRow.dataset.sourceExternal=planned?.externalUnits??'';formRow.dataset.salesReady='0'}f.refreshAuto();
  source.innerHTML='<p>指定単価：'+esc(rate)+'／費用対象と請求額区分を明示選択した月だけ概算残額へ反映します。</p><div class="stock-scroll"><table class="stock-sheet"><thead><tr><th>月</th><th>自社社員の予定人工</th><th>外注の予定人工</th><th>未確定配置</th><th>確定配置</th><th>請負現場日</th></tr></thead><tbody>'+placement.months.map(r=>'<tr><td>'+esc(r.month)+'</td><td>'+units(r.ownUnits)+'</td><td>'+units(r.externalUnits)+'</td><td>'+Number(r.unconfirmedSchedules)+'</td><td>'+Number(r.confirmedSchedules)+'</td><td>'+Number(r.subcontractSiteDays)+'</td></tr>').join('')+'</tbody></table></div>';
  const periods=[...new Set([...monthRows.map(x=>x.querySelector('[data-field=month]').value),month])].filter(x=>/^20\d\d-(0[1-9]|1[0-2])$/.test(x));const batches=await Promise.all(periods.map(period=>portalSession.call('profitSalesCandidates',{p_site_key:key,p_month:period})));if(!current()){rerun=alive();return}if(batches.some(x=>!Array.isArray(x)||x.some(r=>r.amountExclTax==null||r.amountInclTax==null||!Number.isFinite(Number(r.amountExclTax))||!Number.isFinite(Number(r.amountInclTax)))))throw Error('請求原本の金額を確認してください');const byPeriod=new Map(periods.map((period,i)=>[period,batches[i]]));const rows=byPeriod.get(month)||[];
  for(const formRow of monthRows){const period=formRow.querySelector('[data-field=month]').value,list=byPeriod.get(period);formRow.dataset.salesReady=list?'1':'0';formRow.dataset.sourceBillCount=list?.filter(x=>x.linkActive&&x.linkedSiteKey===key).length||0;formRow.dataset.sourceBillExcl=list?.filter(x=>x.linkActive&&x.linkedSiteKey===key).reduce((n,x)=>n+Number(x.amountExclTax),0)||0;formRow.dataset.sourceBillIncl=list?.filter(x=>x.linkActive&&x.linkedSiteKey===key).reduce((n,x)=>n+Number(x.amountInclTax),0)||0}f.refreshAuto();
  const heading=document.createElement('h4');heading.textContent=month+'の請求原本（材料を含む売上、手入力請求額とは別）';sales.append(heading);
  if(!rows.length){const empty=document.createElement('p');empty.textContent='この月に選択できる請求原本はありません。';sales.append(empty)}
  for(const row of rows){const line=document.createElement('div');line.className='row';const label=document.createElement('span');label.textContent='#'+row.id+' ／ '+(row.billDate||'')+' ／ '+(row.client||'')+' ／ '+(row.project||'')+' ／ 税抜 '+money(row.amountExclTax)+'・税込 '+money(row.amountInclTax);line.append(label);const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=row.linkActive?'この現場とのリンクを解除':'この現場にリンク';line.append(button);button.onclick=async()=>{if(!alive())return;button.disabled=true;status.textContent='請求原本のリンクを保存中…';try{await portalSession.call('profitSalesLinkSave',{p_site_key:key,p_sales_record_id:row.id,p_expected_revision:Number(row.linkRevision||0),p_request_id:crypto.randomUUID(),p_active:!row.linkActive});if(alive()){status.textContent='リンクを保存しました。請求額は手入力表へ自動転記していません。';await refresh()}}catch(e){if(alive()){status.textContent=e.message+' 最新のリンク状態を確認してください。';button.disabled=false}}};sales.append(line)}
  status.textContent='配置予定と請求原本を表示しました。';
 }catch(e){if(alive())status.textContent='取得できませんでした：'+e.message}finally{loading=false;if(rerun&&alive()){rerun=false;refresh()}}}
 panel.querySelector('[data-source-refresh]').onclick=refresh;for(const input of panel.querySelectorAll('[data-source-year],[data-sales-month]'))input.addEventListener('change',refresh);box.querySelector('#profitDraft').addEventListener('change',e=>{if(e.target.matches('[data-field=month]'))refresh()});refresh();
}
async function mount(){const box=document.getElementById('sharedProfit');if(!box||box.dataset.bound)return;box.dataset.bound='1';const owner=actor(),ticket=generation,sid=box.dataset.site,status=box.querySelector('[data-profit-load]');
 if(!owner||!window.siteSharedStore){status.textContent='ポータルのログイン確認後、社長権限で表示できます。';return}
 try{const key=sitePortalSiteKey(sid),rows=await siteSharedStore.list('__company__','利益管理');if(!box.isConnected||actor()!==owner||generation!==ticket)return;const row=rows.find(r=>r.id===key);box.innerHTML=formHTML(row?.payload||{});wireAuto(box.querySelector('#profitDraft'),row?.payload||{});wireForm(box.querySelector('#profitDraft'),key,Number(row?.revision||0),owner,ticket);wireSources(box,key,owner,ticket);}
 catch(e){if(box.isConnected&&actor()===owner&&generation===ticket){status.textContent=e.message;const b=document.createElement('button');b.className='secondary';b.textContent='もう一度確認する';b.onclick=()=>{delete box.dataset.bound;b.remove();mount()};box.append(b)}}
}
window.addEventListener('portal-session-ready',()=>{generation++;const box=document.getElementById('sharedProfit');if(box){const sid=box.dataset.site;box.outerHTML=window.profitPanel(sid);mount()}});
window.addEventListener('DOMContentLoaded',()=>{new MutationObserver(mount).observe(document.getElementById('app'),{childList:true,subtree:true});mount();window.appSharedFeatures={...window.appSharedFeatures,'利益管理':true,'profits':true}});
})();
