(function(){
'use strict';
const KEY='jinshou-safety-records-v1',DRAFT='jinshou-safety-drafts-v1',DOCS='jinshou-safety-documents-v1';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const read=k=>JSON.parse(localStorage.getItem(k)||'[]');
const common=[['date','実施日','date'],['recorder','記録者氏名・ID','text']];
const education=[['person','受講者氏名・ポータルID','text'],['company','所属会社','text'],['teacher','教育担当者氏名・ID','text'],['version','教材名・版','text'],['language','使用言語・通訳者','text'],['contents','説明した内容と現場の具体例'],['understanding','本人が自分の言葉で説明した内容・理解確認の結果'],['test','理解度テストの結果・未理解の項目・再教育内容'],['expiry','有効期限・再教育が必要となる条件'],['learnerSign','受講者の記名確認','text'],['teacherSign','教育担当者の記名確認','text']];
const checks={
 common:['会社の安全方針','挨拶・報告・連絡・相談','緊急時の電話と連絡先','危険時の停止・指揮命令系統','高所作業・墜落制止用器具','工具・足場材の落下防止・受け渡し','上下作業の分離','第三者・車両の移動と隔離','休憩後・変更時・最後の一枚の再KY','事故・ヒヤリハット報告'],
 induction:['現場責任者・職長・会社窓口の連絡先','現場図・危険箇所・立入禁止区域','人・車両・重機の動線と誘導方法','資材置場・昇降口・避難経路・集合場所','当日の作業・必要資格・保護具','落下防止・区画・上下作業と他職種調整','緊急時の住所・入口・代替連絡先'],
 ky:['体調の確認','制服・作業服の着用','空調服の着用（不要時は対象外）','配置・共通教育・現場教育の確認','必要資格・有効期限','保護帽・墜落制止用器具の点検','墜落防止設備・親綱・昇降設備','前日・前回からの引継ぎの把握','本日の作業内容の把握','本日の流れ・動き・役割の把握','工具・資材の落下防止','真下・周囲の人・車両・設備への対策','立入禁止・見張員・養生','上下作業の分離・他職種調整','天候・風・照明・足元','全員の参加と発言'],
 heat:['始業前：体調・睡眠・疲労を本人に確認','10時：水分・塩分と体調を確認','昼：食事・休憩・衣服・体調を確認','15時：水分・塩分と体調を確認','終業時：体調と周囲の異変を確認']
};
const defs={
 common:{name:'共通安全教育',fields:education},
 induction:{name:'現場初回教育',fields:[...education,['routes','現場の危険箇所・禁止区域・動線・避難経路'],['contacts','指揮命令系統・緊急連絡先・現場入口'],['qualification','必要資格・保護具と確認者']]},
 near:{name:'ヒヤリハット',fields:[['title','件名','text'],['time','発生日時','datetime-local'],['place','発生場所','text'],['participants','終業時に話し合った参加者・所属・ID'],['work','その時の作業'],['event','何が起きたか・何が危険だったか'],['potential','条件が違えば誰にどのような被害が出たか'],['remaining','今も残る危険・作業停止と連絡の状況'],['action','その場の対策・今後の具体策'],['owner','対策担当者・期限'],['followup','受理者・受理日時・効果確認予定・結果'],['related','関連する事故・手直し・写真の記録番号']]},
 ky:{name:'KY・危険予知活動表',fields:[['work','作業内容・作業場所'],['leader','職長氏名・ID','text'],['deputy','副職長氏名・ID','text'],['participants','参加者（1行に氏名・会社・ID・本人確認を記入）'],['trigger','朝礼／休憩後／変更時／終盤・最後の一枚などの実施理由'],['change','前回から変わった条件・停止時刻'],['evidence','職長が確認した対策の実施状況（KY用紙の下部に反映）'],['handover','終業時の片付け・資材結束・写真・日報・引継ぎ'],['decisionReason','職長の判断理由・残る危険・未参加者への対応'],['leaderSign','職長の記名確認','text'],['restart','実際の開始・再開時刻','datetime-local']]},
 heat:{name:'毎日の体調・暑熱確認',fields:[['person','対象者氏名・会社・ID','text'],['leader','確認した職長氏名・ID','text'],['response','必要な対応・休憩・作業調整と対応時刻'],['personSign','作業員の記名確認','text'],['leaderSign','職長の記名確認','text']]}
};
const safetySamplePeople=[{type:'sample',id:'A',name:'【テスト】山田 太郎',company:'迅翔興業（見本）'},{type:'sample',id:'B',name:'【テスト】佐藤 花子',company:'迅翔興業（見本）'},{type:'sample',id:'C',name:'【テスト】鈴木 一郎',company:'協力会社（見本）'}];
window.safetyLoadSample=(kind='ky',sid=1)=>{const id=crypto.randomUUID(),data={sample:'1',date:today(),recorder:'【テスト】山田 太郎',teacher:'【テスト】山田 太郎',work:'【テスト】外壁足場の組立・資材の受け渡し',leader:'【テスト】山田 太郎',deputy:'【テスト】佐藤 花子',trigger:'朝礼・作業開始前',decision:'保留',attendees:safetySamplePeople.map(p=>({key:p.type+':'+p.id,name:p.name,company:p.company,confirmedAt:''})),risks:[{speaker:'【テスト】佐藤 花子',hazard:'資材の受け渡し時に足場板が落下し、下の人に当たる。',measure:'下部を立入禁止にし、声を掛け合い、相手の保持を確認して手を離す。',owner:'【テスト】山田 太郎',frequency:'2',severity:'3',afterFrequency:'1',afterSeverity:'3'}]};localStorage.setItem(DRAFT,JSON.stringify([...read(DRAFT),{id,kind,site:String(sid),data,updatedAt:new Date().toISOString()}]));safetyForm(kind,sid,id)};
window.safetyDrafts=()=>read(DRAFT);
const fieldsFor=k=>[...common,...defs[k].fields];
function field(k,l,t,v){return `<label>${esc(l)}${t?`<input name="${k}" type="${t}" value="${esc(v||'')}">`:`<textarea name="${k}" rows="3">${esc(v||'')}</textarea>`}</label>`}
function riskRow(r={},i=0){return `<div class="safety-risk"><span class="risk-number">${i+1}</span>${[['speaker','発言者'],['hazard','危険予測'],['owner','実施者'],['measure','私たちはこうする']].map(([k,l])=>`<label>${l}<textarea aria-label="${l}" data-risk="${k}" rows="2">${esc(r[k]||'')}</textarea></label>`).join('')}<div class="risk-scores">${[['frequency','前：頻度'],['severity','前：重篤度'],['afterFrequency','後：頻度'],['afterSeverity','後：重篤度']].map(([k,l])=>`<label>${l}<select data-risk="${k}"><option value="">―</option>${[1,2,3].map(n=>`<option ${String(r[k])===String(n)?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}</div><button type="button" class="secondary" data-remove-risk>削除</button></div>`}
function invalidateConfirmations(f,e){if(!f.dailyKy)return;if(e&&!e.target.matches('[data-risk], [name=work], [name=date], [name=trigger], [name=change]'))return;f.dailyKy.reset();}
function enhanceSafetyForm(f,kind,sid,data){
 const edu=['common','induction'].includes(kind),ky=kind==='ky';
 const reset=document.createElement('button');reset.type='button';reset.className='secondary safety-reset';reset.id='safetyReset';reset.textContent='保存せずに戻る';f.querySelector('.modalfoot').prepend(reset);const top=document.createElement('div');top.className='safety-top-actions';top.innerHTML='<button type="button" class="secondary" id="safetyDiscardTop">← 保存せずに戻る</button><button type="button" class="secondary" id="safetySampleButton">テスト用の記入例を開く</button>';f.prepend(top);top.querySelector('#safetyDiscardTop').onclick=()=>reset.click();top.querySelector('#safetySampleButton').onclick=()=>f.dispatchEvent(new Event('open-sample'));
 if(!edu&&!ky)return;
 $('modal').classList.add('safety-edit-dialog');$('modal').addEventListener('close',()=>$('modal').classList.remove('safety-edit-dialog'),{once:true});
 const save=()=>f.dispatchEvent(new Event('safety-save'));
 const members=()=>typeof siteResolvedMembers==='function'?siteResolvedMembers(sid):[];
 const selector=document.createElement('section');selector.className='safety-member-select';selector.innerHTML=`<h3>${edu?'受講する人':'今日の参加メンバー'}</h3><p>${edu?'現場メンバーを選ぶと氏名・会社・IDが入ります。':'参加者を追加し、下の確認表で本人が項目ごとに確認します。一括確認はありません。'}</p><div class="row"><select aria-label="現場メンバー" id="safetyMemberSelect"></select><button type="button" class="secondary" id="refreshSafetyMembers">メンバーを読み直す</button>${ky?'<button type="button" class="primary" id="addSafetyMember">参加者を追加</button>':''}</div><p id="memberLoadStatus" role="status"></p><div id="safetyAttendees"></div>`;
 f.prepend(selector);let people=members();if(data.sample)people=[...people,...safetySamplePeople];
 function options(){const sel=$('safetyMemberSelect');sel.innerHTML='<option value="">対象者を選択</option>'+people.map(p=>`<option value="${esc(p.type+':'+p.id)}">${esc(p.name)} ／ ${esc(p.company)} ／ ID ${esc(p.code||p.id)}</option>`).join('');if(edu)sel.value=data.personKey||'';if(!people.length)$('memberLoadStatus').textContent='メンバータブで対象者を追加してください。';}
 options();$('refreshSafetyMembers').onclick=async()=>{try{await refreshSitePeople();people=members();options();$('memberLoadStatus').textContent=people.length+'名を読み込みました。'}catch(e){$('memberLoadStatus').textContent=e.message}};
 if(edu){
 for(const k of ['person','company','version','contents','understanding','test','expiry','learnerSign','teacherSign','routes','contacts','qualification']){const el=f.elements[k];if(el){el.type==='textarea'?el.closest('label').hidden=true:el.closest('label').hidden=true;}}
 const hidden=document.createElement('input');hidden.type='hidden';hidden.name='personKey';hidden.value=data.personKey||'';f.append(hidden);
 const selected=document.createElement('p');selected.id='selectedSafetyPerson';selected.textContent=data.person||'受講者は未選択です。';selector.append(selected);
 $('safetyMemberSelect').onchange=e=>{const p=people.find(p=>p.type+':'+p.id===e.target.value);f.elements.personKey.value=e.target.value;f.elements.person.value=p?p.name+' ／ ID '+(p.code||p.id):'';f.elements.company.value=p?.company||'';selected.textContent=f.elements.person.value||'受講者は未選択です。';for(const box of f.querySelectorAll('[data-edu-check]'))box.checked=false;for(const el of f.querySelectorAll('[data-safety-check]'))el.value='未確認';for(const k of ['learner','teacher']){if(f.elements[k+'Ink'])f.elements[k+'Ink'].value='';if(f.elements[k+'SignedAt'])f.elements[k+'SignedAt'].value='';const c=f.querySelector('[data-signature='+k+']');c?.getContext('2d').clearRect(0,0,c.width,c.height)}save()};
 const version=kind==='common'?'共通安全教育・標準 第1版':'現場初回教育・標準 第1版';f.elements.version.value=version;
 const intro=document.createElement('section');intro.innerHTML=`<h3>使用する教材：${version}</h3><p>標準教材を使い、説明と本人の理解を項目ごとにチェックします。</p><a class="secondary" href="safety-guide.pdf#page=${kind==='common'?76:77}" target="_blank" rel="noopener">教育教材を開く</a><p>現場の場所・動線・連絡先は現場資料を示して説明してください。</p>`;selector.after(intro);
 const doc=f.elements.document;doc.closest('label').firstChild.textContent='追加で使った現場資料（任意）';
 const table=f.querySelector('.safety-table-wrap table');table.querySelector('thead').innerHTML='<tr><th>教育する内容</th><th>説明した</th><th>本人が説明・理解できた</th></tr>';
 for(const row of table.querySelectorAll('tbody tr')){const select=row.querySelector('select'),done=select.value==='説明・本人理解を確認';select.hidden=true;const label=select.dataset.safetyCheck,saved=data.checks?.find(c=>c.label===label);row.innerHTML=`<td>${esc(label)}</td><td><label><input type="checkbox" data-edu-check ${done||saved?.explained?'checked':''}>説明済み</label></td><td><label><input type="checkbox" data-edu-check ${done||saved?.understood?'checked':''}>理解を確認</label></td>`;row.cells[0].append(select);row.onchange=()=>{select.value=[...row.querySelectorAll('[data-edu-check]')].every(c=>c.checked)?'説明・本人理解を確認':'未確認';save()};}
 }else{
 f.elements.participants.closest('label').hidden=true;
 const host=$('safetyAttendees');function add(p){const key=p.key||p.type+':'+p.id;if([...host.children].some(r=>JSON.parse(r.dataset.attendee).key===key))return;const row=document.createElement('div');row.className='safety-attendee';row.dataset.attendee=JSON.stringify({key,name:p.name,company:p.company});row.dataset.confirmedAt=p.confirmedAt||'';row.classList.toggle('confirmed',!!p.confirmedAt);row.innerHTML=`<strong>${esc(p.name)}<small>${esc(p.company)} ／ ${esc(key)}</small></strong><button type="button" class="secondary" data-remove-person>参加から外す</button>`;row.querySelector('[data-remove-person]').onclick=()=>{row.remove();save()};host.append(row)}
 f.addKyPerson=add;(data.attendees||[]).forEach(add);$('addSafetyMember').onclick=()=>{const p=people.find(p=>p.type+':'+p.id===$('safetyMemberSelect').value);if(p){add(p);save()}};
 const risk=$('safetyRisks');const title=risk.previousElementSibling.previousElementSibling,desc=risk.previousElementSibling,button=$('addSafetyRisk');const section=document.createElement('section');section.className='ky-paper-entry';section.append(title,desc,risk,button);f.querySelector('.safety-fields').after(section);
 }
}
const dailyEnd=['最後の部材・終盤作業前の再確認','足場点検','片付け・清掃','車両の片付け','資材の結束・落下防止','本日の記録・日報','本日の報告','本日の引継ぎ'];
const heatDaily=['始業前：睡眠・疲労・食事・体調','10時：水分・塩分・体調','昼：食事・休憩・衣服・体調','15時：水分・塩分・体調','終業時：自分と周囲の体調'];
function setupDailyKy(f,data){
 const saved=data.daily||{},values=structuredClone(saved.responses||{});let people=[];if(saved.labels?.ky&&JSON.stringify(saved.labels.ky)!==JSON.stringify(checks.ky)){for(const key of Object.keys(values))if(key.startsWith('ky:'))delete values[key];}if(saved.labels?.end&&JSON.stringify(saved.labels.end)!==JSON.stringify(dailyEnd)){for(const key of Object.keys(values))if(key.startsWith('end:'))delete values[key];}
 const trigger=f.elements.trigger,sel=document.createElement('select');sel.name='trigger';const options=['朝礼','休憩後','作業変更時','終盤・最後の一枚','その他'];sel.innerHTML=options.map(x=>`<option>${x}</option>`).join('');sel.value=options.includes(data.trigger)?data.trigger:'朝礼';trigger.replaceWith(sel);
 f.elements.evidence.placeholder='例：立入禁止の区画を設置済み。見張り担当を決め、他の職種と作業時間を調整した。写真がある場合は写真名も記入。';const restart=f.elements.restart;restart.type='time';restart.value=(data.restart||'').includes('T')?data.restart.split('T')[1].slice(0,5):data.restart||'';
 restart.closest('label').firstChild.textContent='開始・再開時刻（実施日の時間のみ）';
 const dateNote=document.createElement('p');dateNote.textContent='実施日：'+f.elements.date.value+' ／ 時刻だけ入力してください。';restart.before(dateNote);f.elements.date.addEventListener('change',()=>dateNote.textContent='実施日：'+f.elements.date.value+' ／ 時刻だけ入力してください。');
 f.elements.handover.closest('label').hidden=true;
 const oldTable=f.querySelector('.safety-table-wrap');oldTable.previousElementSibling.hidden=true;oldTable.hidden=true;
 const section=document.createElement('section');section.className='daily-ky';section.innerHTML=`<h3>一人ずつ・項目ごとの確認</h3><p>各自の列を選び、項目ごとに「○ 確認」「× 問題」「－ 対象外」を選んでください。全項目をまとめて確認するボタンはありません。</p><div class="safety-table-wrap" id="dailyPersonal"></div><h3 id="dailyHeatTitle">熱中症予防・体調確認</h3><p>始業前・10時・昼・15時・終業時に記録します。まだ来ていない時間は未確認のまま残せます。問題があれば職長に連絡し、対応を下に残してください。</p><div class="safety-table-wrap" id="dailyHeat"></div><label>体調確認での対応・作業調整（問題がある場合）<textarea name="heatResponse" rows="2">${esc(saved.heatResponse||'')}</textarea></label><h3>終業時のヒヤリハット</h3><label>今日の話し合い<select name="nearStatus"><option value="">未確認</option><option>なし（全員で共有済み）</option><option>あり</option></select></label><div class="safety-fields">${[['nearEvent','誰が・どこで・何が起きたか'],['nearAction','その場の対策・次回の対策・担当者'],['nearRemaining','残る危険・職長の判断・引継ぎ']].map(([k,l])=>field(k,l,null,saved[k])).join('')}</div><h3>終業時の確認</h3><p>一番下のこの表まで、各自が確認してください。</p><div class="safety-table-wrap" id="dailyEnd"></div><label>記録する段階<select name="dayStage"><option>作業前・途中</option><option>終業確認を完了</option></select></label>`;
 f.querySelector('#safetySaveState').before(section);const legacy=f.elements.nearEvent.closest('.safety-fields');legacy.hidden=true;const nearHost=document.createElement('div');nearHost.id='dailyNearRows';legacy.after(nearHost);function addNear(x={}){const row=document.createElement('fieldset');row.className='daily-near-row';row.innerHTML='<legend>ヒヤリハット</legend>'+[['event','誰が・どこで・何が起きたか'],['action','対策・担当者'],['remaining','残る危険・判断・引継ぎ']].map(([k,l])=>`<label>${l}<textarea data-near="${k}" rows="2">${esc(x[k]||'')}</textarea></label>`).join('')+'<button type="button" class="secondary">この件を削除</button>';row.querySelector('button').onclick=()=>{row.remove();f.dispatchEvent(new Event('safety-save'))};nearHost.append(row)};(saved.nearEntries||[{event:saved.nearEvent,action:saved.nearAction,remaining:saved.nearRemaining}]).forEach(addNear);const add=document.createElement('button');add.type='button';add.className='secondary';add.textContent='＋ ヒヤリハットを追加';add.onclick=()=>{addNear();f.dispatchEvent(new Event('safety-save'))};nearHost.after(add);const photo=document.createElement('section');photo.className='leader-required';photo.innerHTML=`<h3>職長確認｜終業前に必ず確認</h3><p>提出漏れ・引継ぎ漏れを防ぐため、職長が1項目ずつ確認してください。</p>${[['leaderPhoto','写真の記録'],['leaderVoucher','常用伝票の提出'],['leaderDocuments','必要書類の提出'],['leaderHandover','本日の引継ぎ']].map(([k,l])=>`<label><input type="checkbox" name="${k}" ${saved[k]?'checked':''}> ${l}を確認した</label>`).join('')}<label>引継ぎ先・内容／提出不要の場合の理由<textarea name="leaderNote" rows="2">${esc(saved.leaderNote||'')}</textarea></label>`;section.querySelector('#dailyEnd').after(photo);f.elements.nearStatus.value=saved.nearStatus||'';f.elements.dayStage.value=saved.dayStage||'作業前・途中';
 function matrix(target,group,labels){$(target).innerHTML=`<table class="table daily-matrix"><thead><tr><th>確認する項目</th>${people.map(p=>`<th>${esc(p.name)}<small>${esc(p.company)}</small></th>`).join('')}</tr></thead><tbody>${labels.map((label,i)=>`<tr><th>${esc(label)}</th>${people.map((p,j)=>{const key=group+':'+i+':'+p.key,v=values[key]||{};return `<td><select data-daily-key="${esc(key)}" aria-label="${esc(p.name+' '+label)}">${[['','未確認'],['ok','○ 確認'],['issue','× 問題'],['na','－ 対象外']].map(([k,l])=>`<option value="${k}" ${v.result===k?'selected':''}>${l}</option>`).join('')}</select><input data-daily-note="${esc(key)}" aria-label="${esc(p.name+' '+label+' 理由・対応')}" placeholder="理由・対応" value="${esc(v.note||'')}" ${['issue','na'].includes(v.result)?'':'hidden'}></td>`}).join('')}</tr>`).join('')}</tbody></table>${people.length?'':'<div class="ky-empty-members"><strong>参加者が0人のため、チェック欄がまだありません。</strong><p>参加者を追加すると、その人の確認欄が表示されます。</p><button type="button" class="primary" data-pick-members>参加メンバーを選ぶ</button><button type="button" class="secondary" data-add-test-people>テスト用の3人を追加して試す</button></div>'}`;}
 function makeEndChecks(){for(const select of $('dailyEnd').querySelectorAll('[data-daily-key]')){const box=document.createElement('input');box.type='checkbox';box.dataset.dailyKey=select.dataset.dailyKey;box.setAttribute('aria-label',select.getAttribute('aria-label'));box.checked=select.value==='ok';select.replaceWith(box)}}
 function draw(){people=[...f.querySelectorAll('[data-attendee]')].map(r=>JSON.parse(r.dataset.attendee));matrix('dailyPersonal','ky',checks.ky);matrix('dailyHeat','heat',heatDaily);matrix('dailyEnd','end',dailyEnd);makeEndChecks();}
 section.addEventListener('click',e=>{if(e.target.matches('[data-pick-members]')){$('safetyMemberSelect').scrollIntoView({block:'center'});$('safetyMemberSelect').focus()}if(e.target.matches('[data-add-test-people]')){safetySamplePeople.forEach(p=>f.addKyPerson(p));if(!f.elements.sample){const marker=document.createElement('input');marker.type='hidden';marker.name='sample';marker.value='1';f.append(marker)}f.dispatchEvent(new Event('safety-save'))}});
 section.addEventListener('change',e=>{if(e.target.dataset.dailyKey){const key=e.target.dataset.dailyKey;values[key]={...(values[key]||{}),result:e.target.type==='checkbox'?(e.target.checked?'ok':''):e.target.value,at:new Date().toISOString()};const note=[...section.querySelectorAll('[data-daily-note]')].find(el=>el.dataset.dailyNote===key);note.hidden=!['issue','na'].includes(e.target.value);}});
 section.addEventListener('input',e=>{if(e.target.dataset.dailyNote){const key=e.target.dataset.dailyNote;values[key]={...(values[key]||{}),note:e.target.value,at:new Date().toISOString()}}});
 f.dailyKy={reset(){for(const key of Object.keys(values))if(key.startsWith('ky:'))delete values[key];draw()},value(){const keys=new Set(people.map(p=>p.key));return {schema:2,...Object.fromEntries(['leaderPhoto','leaderVoucher','leaderDocuments','leaderHandover'].map(k=>[k,f.elements[k].checked])),leaderNote:f.elements.leaderNote.value,nearEntries:[...f.querySelectorAll('.daily-near-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-near]')].map(el=>[el.dataset.near,el.value]))),responses:Object.fromEntries(Object.entries(values).filter(([k])=>keys.has(k.split(':').slice(2).join(':')))),people,labels:{ky:checks.ky,heat:heatDaily,end:dailyEnd},...Object.fromEntries(['heatResponse','nearStatus','nearEvent','nearAction','nearRemaining','dayStage'].map(k=>[k,f.elements[k].value]))}}};
 const observer=new MutationObserver(()=>{draw();f.dispatchEvent(new Event('safety-save'))});observer.observe($('safetyAttendees'),{childList:true});$('modal').addEventListener('close',()=>observer.disconnect(),{once:true});draw();
 const jump=document.createElement('button');jump.type='button';jump.className='secondary';jump.textContent='熱中症・体調確認へ';jump.onclick=()=>$('dailyHeatTitle').scrollIntoView({block:'start',behavior:'smooth'});f.querySelector('.safety-top-actions').append(jump);
}
function validateDailyKy(v){
 const d=v.daily;const complete=(group,labels)=>d.people.length&&d.people.every(p=>labels.every((_,i)=>{const r=d.responses[group+':'+i+':'+p.key];return r&&(r.result==='ok'||r.result==='na'&&r.note?.trim())}));
 if(v.decision!=='保留'){
 if(!complete('ky',d.labels.ky))throw Error('参加者全員が、確認表の各項目を確認してください。問題がある間は判断を保留してください。');
 if(!complete('heat',[d.labels.heat[0]]))throw Error('全員の始業前の体調確認が必要です。');
 if(!v.leaderSign?.trim()||!v.decisionReason?.trim()||!v.evidence?.trim()||!v.restart)throw Error('職長の記名・判断理由・対策の確認と開始時刻を記入してください。');
 }
 if(!v.risks.length||v.risks.some(r=>['speaker','hazard','measure','owner'].some(k=>!r[k]?.trim())))throw Error('発言者・危険・対策・実施者を記入してください。');
 if(Object.entries(d.responses).some(([k,r])=>k.startsWith('heat:')&&r.result==='issue')&&!d.heatResponse.trim())throw Error('体調に問題がある人への対応を記入してください。');
 if(d.dayStage==='終業確認を完了'){
 if(!d.nearStatus)throw Error('ヒヤリハットを全員で共有し、あり・なしを選んでください。');
 if(d.nearStatus==='あり'&&(!d.nearEntries?.length||d.nearEntries.some(x=>!x.event.trim()||!x.action.trim())))throw Error('ヒヤリハットの内容と対策を記入してください。');
 if(['leaderPhoto','leaderVoucher','leaderDocuments','leaderHandover'].some(k=>!d[k]))throw Error('職長確認の写真・常用伝票・必要書類・本日の引継ぎをすべて確認してください。');if(!complete('end',d.labels.end))throw Error('全員の終業チェックを完了してください。');
 if(!d.people.every(p=>d.labels.heat.every((_,i)=>{const r=d.responses['heat:'+i+':'+p.key];return r?.result&&(r.result!=='na'||r.note?.trim())})))throw Error('各時間帯の体調確認を残してください。対象外には理由が必要です。');
 }
}
function openDailyKy(r,latest){const v=r.data,d=v.daily,site=state.sites.find(s=>String(s.id)===r.site)?.name||'',chunks=[];for(let i=0;i<d.people.length;i+=10)chunks.push(d.people.slice(i,i+10));if(!chunks.length)chunks.push([]);const pages=[];
 const matrix=(group,people)=>`<table class="submission-matrix"><thead><tr><th>確認項目</th>${people.map(p=>`<th>${esc(p.name)}<small>${esc(p.company)}<br>${esc(p.key)}</small></th>`).join('')}</tr></thead><tbody>${d.labels[group].map((l,i)=>`<tr><th>${esc(l)}</th>${people.map(p=>{const x=d.responses[group+':'+i+':'+p.key]||{};return `<td><b>${({ok:'○',issue:'× 問題',na:'対象外'})[x.result]||'未確認'}</b>${x.note?'<div>'+esc(x.note)+'</div>':''}${x.at?`<small>${esc(new Date(x.at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}))}</small>`:''}</td>`}).join('')}</tr>`).join('')}</tbody></table>`;
 for(const people of chunks){
 pages.push({title:'危険予知活動表（KY）',body:`<p>作業：${esc(v.work)} ／ 職長：${esc(v.leader)} ／ 副職長：${esc(v.deputy)}</p><table class="submission-risks"><colgroup><col style="width:10%"><col style="width:27%"><col style="width:5%"><col style="width:5%"><col style="width:5%"><col style="width:28%"><col style="width:5%"><col style="width:5%"><col style="width:5%"></colgroup><thead><tr><th rowspan="2">発言者<br>実施者</th><th rowspan="2">予測される危険</th><th colspan="3">対策前</th><th rowspan="2">私たちはこうする</th><th colspan="3">対策後</th></tr><tr><th>頻度</th><th>重篤度</th><th>危険度</th><th>頻度</th><th>重篤度</th><th>危険度</th></tr></thead><tbody>${[...v.risks,...Array(Math.max(0,5-v.risks.length)).fill({})].map(x=>`<tr><td class="risk-person-cell"><div><small>発言者</small>${esc(x.speaker||'　')}</div><div><small>実施者</small>${esc(x.owner||'　')}</div></td><td>${esc(x.hazard||'')}</td><td>${esc(x.frequency||'')}</td><td>${esc(x.severity||'')}</td><td>${x.frequency&&x.severity?Number(x.frequency)+Number(x.severity):''}</td><td>${esc(x.measure||'')}</td><td>${esc(x.afterFrequency||'')}</td><td>${esc(x.afterSeverity||'')}</td><td>${x.afterFrequency&&x.afterSeverity?Number(x.afterFrequency)+Number(x.afterSeverity):''}</td></tr>`).join('')}</tbody></table><table class="risk-scale"><tr><th>頻度</th><td>1：たまに（1～3回／日）</td><td>2：よく（10回程度／日）</td><td>3：頻繁（常時）</td></tr><tr><th>重篤度</th><td>1：不休災害</td><td>2：休業3日以内</td><td>3：休業4日以上</td></tr><tr><th>危険度</th><td colspan="3">頻度＋重篤度＝2～6。高い順に対策し、対策後は3以下を目指す。数値だけで開始を決めず、実際の対策を確認する。</td></tr></table>${matrix('ky',people)}<p>職長判断：${esc(v.decision)} ／ ${esc(v.decisionReason)} ／ 記名：${esc(v.leaderSign)} ／ 開始：${esc(v.restart||'未記入')}</p><p>条件変更：${esc(v.change||'なし')} ／ 対策確認：${esc(v.evidence||'未記入')}</p>`});
 pages.push({title:'熱中症予防・体調確認表',body:`<p>○：確認　×：問題あり　対象外：理由を記録 ／ まだ確認していない時間帯は「未確認」</p>${matrix('heat',people)}<h2>職長の対応・休憩・作業調整</h2><div class="submission-note">${esc(d.heatResponse||'記載なし')}</div><p>確認責任者：${esc(v.leader)} ／ 記録者：${esc(v.recorder)}</p>`});
 pages.push({title:'ヒヤリハット・終業確認表',body:`<h2>終業時の話し合い：${esc(d.nearStatus||'未確認')}</h2>${(d.nearEntries||[{event:d.nearEvent,action:d.nearAction,remaining:d.nearRemaining}]).map((x,i)=>`<table class="submission-notes"><tr><th>ヒヤリハット ${i+1}</th><td>${esc(x.event||'記載なし')}</td></tr><tr><th>対策・担当者</th><td>${esc(x.action||'記載なし')}</td></tr><tr><th>残る危険・判断・引継ぎ</th><td>${esc(x.remaining||'記載なし')}</td></tr></table>`).join('')}${matrix('end',people)}<section class="leader-required"><h2>職長確認｜終業前に必ず確認</h2><p>確認者：${esc(v.leader)} ／ 提出・引継ぎ漏れがないか、職長が各項目を確認。</p><div class="leader-check-grid">${[['leaderPhoto','写真の記録'],['leaderVoucher','常用伝票の提出'],['leaderDocuments','必要書類の提出'],['leaderHandover','本日の引継ぎ']].map(([k,l])=>`<div>${d[k]?'☑':'□'} ${l}　${d[k]?'確認済み':'未確認'}</div>`).join('')}</div><p>${esc(d.leaderNote||'')}</p></section><p>記録段階：${esc(d.dayStage)} ／ 職長：${esc(v.leader)} ／ 記録者：${esc(v.recorder)}</p>`});}
 show(`<style>@media print{@page{size:A4 landscape;margin:5mm}}</style><div class="paper-preview-actions"><h2>印刷プレビュー ／ A4横・${pages.length}枚</h2><p>白い用紙1枚ごとに印刷されます。記載量が多い場合は続きのページになります。${v.sample?'【テスト用・提出不可】架空の記入済み見本です。':''}</p><button class="primary" onclick="safetyPrintDocument()">印刷画面を開く</button><button class="secondary" onclick="safetyPrintDocument(true)">印刷用ファイルを保存</button>${r.id.startsWith('print-sample')?`<a class="secondary" href="safety-sample-${d.people.length}.pdf" target="_blank" rel="noopener">見本のPDFを開く・印刷</a>`:''}<p id="safetyPrintMessage" role="status"></p><button class="secondary" onclick="safetyPrintSample(6)">6人の記入済み見本</button><button class="secondary" onclick="safetyPrintSample(10)">10人の記入済み見本</button>${r.id.startsWith('print-sample')?'':`<button class="secondary" onclick="safetyForm('ky','${r.site}','${r.id}')">続き・改訂を記入</button>`}<button class="secondary" onclick="closeModal()">戻る</button>${(latest.history||[]).map(h=>`<button class="secondary" onclick="safetyOpen('${r.id}',${h.revision})">第${h.revision}版</button>`).join('')}</div><div class="submission-pages">${pages.map((p,i)=>`<article class="submission-page"><header><span>迅翔興業 ／ 現場安全記録</span><strong>${v.sample?'テスト用・提出不可':'第'+r.revision+'版'}</strong></header><h1>${p.title}</h1><div class="submission-meta"><div><b>現場名</b><strong>${esc(site)}</strong></div><div><b>実施日</b><strong>${esc(v.date)}</strong></div><div><b>実施区分</b><strong>${esc(i%3===0?v.trigger:i%3===1?'始業前・休憩時・終業時':'終業時')}</strong></div><div><b>参加人数</b><strong>${d.people.length}名</strong></div></div>${p.body}<footer>${esc(r.verification)} ／ 記録ID：${esc(r.id)}<span>${i+1} / ${pages.length}</span></footer></article>`).join('')}</div>`);window.paginateSafetyDocument?.();$('modal').classList.add('submission-dialog');$('modal').addEventListener('close',()=>{if(!$('modal').open)$('modal').classList.remove('submission-dialog')},{once:true});}
window.safetyPrintSample=(count=10)=>{count=count===6?6:10;const names=['山田 太郎','佐藤 花子','鈴木 一郎','田中 次郎','高橋 健','伊藤 誠','渡辺 翔','中村 亮','小林 隆','加藤 航'];const people=names.slice(0,count).map((name,i)=>({key:'TEST-'+String(i+1).padStart(2,'0'),name,company:i<4?'迅翔興業（見本）':i<7?'協力会社A（見本）':'協力会社B（見本）'}));const responses={};const labels={ky:checks.ky,heat:heatDaily,end:dailyEnd};for(const [g,ls]of Object.entries(labels))ls.forEach((l,i)=>people.forEach(p=>responses[g+':'+i+':'+p.key]={result:'ok',at:today()+'T'+(g==='ky'?'08:00':g==='end'?'17:00':['08:00','10:00','12:00','15:00','17:00'][i])+':00+09:00'}));const data={sample:'1',date:today(),trigger:'朝礼',work:'南面足場の組立・資材の受け渡し',leader:names[0],deputy:names[1],recorder:names[0],decision:'開始可',decisionReason:'立入禁止区画と資材の受け渡し手順を全員で確認。',leaderSign:names[0]+'（見本）',restart:'08:10',change:'変更なし',evidence:'下部の区画・見張り位置を職長が確認（見本）。',risks:[{speaker:names[1],owner:names[0],hazard:'足場板が落下し、下にいる作業員に当たる。',measure:'下部を区画し、相手が保持したことを声で確認してから手を離す。',frequency:'2',severity:'3',afterFrequency:'1',afterSeverity:'3'}],daily:{schema:1,people,labels,responses,heatResponse:'各休憩で水分・塩分補給と体調を確認。異常の申告なし（見本）。',nearStatus:'あり',nearEvent:'15時の休憩後、資材置場で通路に張り出した結束バンドにつまずきかけた。けがなし（見本）。',nearAction:'鈴木が直ちに撤去。職長が通路を再確認し、翌朝も資材置場を確認する（見本）。',nearRemaining:'残る障害物なし。翌朝のKYで全員に共有する（見本）。',dayStage:'終業確認を完了'}};data.daily.leaderPhoto=true;data.daily.leaderVoucher=true;data.daily.leaderDocuments=true;data.daily.leaderHandover=true;data.daily.leaderNote='必要書類を提出し、翌日の作業と注意事項を次の職長へ引継ぎ済み（見本）。';data.daily.nearEntries=[{event:data.daily.nearEvent,action:data.daily.nearAction,remaining:data.daily.nearRemaining},{event:'資材搬入時、歩行者と運搬経路が重なりかけた（見本）。',action:'誘導員を配置し通路を分離。担当：田中（見本）。',remaining:'翌朝も区画を確認する（見本）。'}];const r={id:'print-sample-'+count,site:String(siteId||1),revision:1,data,history:[],verification:'架空の記入例・実際の確認や署名の記録ではありません'};openDailyKy(r,r)};

function collect(f){return {...Object.fromEntries(new FormData(f)),...(f.dailyKy?{daily:f.dailyKy.value()}:{}),checks:[...f.querySelectorAll('[data-safety-check]')].map(el=>({label:el.dataset.safetyCheck,result:el.value,explained:el.closest('tr').querySelectorAll('[data-edu-check]')[0]?.checked||false,understood:el.closest('tr').querySelectorAll('[data-edu-check]')[1]?.checked||false,note:el.closest('tr').querySelector('input:not([type=checkbox])')?.value||''})),attendees:[...f.querySelectorAll('[data-attendee]')].map(row=>({...JSON.parse(row.dataset.attendee),confirmedAt:row.dataset.confirmedAt||''})),risks:[...f.querySelectorAll('.safety-risk')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-risk]')].map(el=>[el.dataset.risk,el.value])))} }
window.safetyForm=(kind,sid,id)=>{
 const prior=read(KEY).find(r=>r.id===id),draft=read(DRAFT).find(r=>r.id===id),base=draft||prior||{},recordId=id||crypto.randomUUID(),data=base.data||{date:today()},d=defs[kind];let closed=false;
 show(`<h2>${data.sample?'【テスト用】 ':''}${d.name}を記録</h2><p>${esc(state.sites.find(s=>String(s.id)===String(sid))?.name||'共通教育')}</p><p class="notice">この端末での試作記録です。記名確認は本人認証・電子署名の検証には未接続です。</p>${kind==='near'?'<p>終業時に「今日どんなヒヤリハットがあったか」を話し合って記入してください。緊急の危険は入力を待たず、作業停止・救護・電話連絡を優先してください。</p>':''}${kind==='heat'?'<p>病名・服薬・詳細な症状はこの共有用記録に書かず、職長へ個別に相談してください。</p>':''}<form id="safetyForm"><div class="safety-fields">${fieldsFor(kind).map(([k,l,t])=>field(k,l,t,data[k])).join('')}</div>${['common','induction'].includes(kind)?`<label>使用した教育資料<select name="document"><option value="">資料を選択</option>${read(DOCS).filter(x=>!x.site||String(x.site)===String(sid)).map(x=>`<option value="${x.id}" ${data.document===x.id?'selected':''}>${esc(x.name)} ／ ${esc(x.version)}</option>`).join('')}</select></label><p>本人と担当者がそれぞれ内容を確認し、下のサイン欄に記入してください。代表者1人の確認で会社全員を受講済みにしません。</p>`:''}${checks[kind]?`<h3>確認項目</h3><div class="safety-table-wrap"><table class="table"><thead><tr><th>項目</th><th>結果</th><th>説明・対象外の理由・措置</th></tr></thead><tbody>${checks[kind].map((l,i)=>`<tr><td>${l}</td><td><select data-safety-check="${l}">${['未確認',...(['common','induction'].includes(kind)?['説明・本人理解を確認','再説明が必要']:['適合','問題あり','対象外'])].map(x=>`<option ${data.checks?.[i]?.result===x?'selected':''}>${x}</option>`).join('')}</select></td><td><input aria-label="${l}の説明" value="${esc(data.checks?.[i]?.note||'')}"></td></tr>`).join('')}</tbody></table></div>`:''}${kind==='ky'?`<h3>全員の発言・危険と対策</h3><p>頻度：1＝たまに起こる（1～3回／日）、2＝よく起こる（10回程度／日）、3＝頻繁に起こる（常時）。重篤度：1＝不休災害、2＝休業3日以内、3＝休業4日以上。危険度＝頻度＋重篤度（2～6）。数字が高いものから対策し、対策後は3以下を目指します。数値だけで作業開始を決めず、実際の対策を確認します。</p><div id="safetyRisks">${(data.risks?.length?data.risks:[{}]).map(riskRow).join('')}</div><button class="secondary" type="button" id="addSafetyRisk">＋ 発言・危険の行を追加</button><label>職長の判断<select name="decision">${['保留','開始可','再開可'].map(v=>`<option ${data.decision===v?'selected':''}>${v}</option>`).join('')}</select></label>`:''}<p id="safetySaveState" role="status">入力すると下書きを保存します。</p><p id="safetyError" role="alert"></p><div class="modalfoot"><button class="secondary" type="button" id="safetyBack">下書きを残して戻る</button><button class="primary" type="submit">記録を確定して確認</button></div></form>`);
 const f=$('safetyForm');if(data.sample){const marker=document.createElement('input');marker.type='hidden';marker.name='sample';marker.value='1';f.append(marker);}
 enhanceSafetyForm(f,kind,sid,data);if(kind==='ky')setupDailyKy(f,data);
 if(kind==='heat'){
 const host=document.createElement('section');host.innerHTML='<button type="button" class="secondary" id="chooseSafetyPerson">現場メンバーから対象者を選ぶ</button><select name="personKey" aria-label="対象の現場メンバー"><option value="'+esc(data.personKey||'')+'">'+esc(data.person||'未選択・記名入力')+'</option></select><p id="safetyPeopleStatus"></p>';f.prepend(host);
 $('chooseSafetyPerson').onclick=async()=>{try{await refreshSitePeople();const people=siteResolvedMembers(sid);const select=f.elements.personKey;select.innerHTML='<option value="">対象者を選択</option>'+people.map(p=>'<option value="'+esc(p.type+':'+p.id)+'">'+esc(p.name+' ／ '+p.company+' ／ ID '+(p.code||p.id))+'</option>').join('');select.onchange=()=>{const p=people.find(p=>p.type+':'+p.id===select.value);if(p){f.elements.person.value=p.name+' ／ ID '+(p.code||p.id);if(f.elements.company)f.elements.company.value=p.company;persist()}};$('safetyPeopleStatus').textContent=people.length?'参加のみのメンバーも選択できます。':'先にメンバータブで対象者・会社を追加してください。'}catch(e){$('safetyPeopleStatus').textContent=e.message}};
 }
 if(['common','induction'].includes(kind)){
 const pads=document.createElement('section');pads.innerHTML='<h3>手書きサイン（本人と教育担当者がそれぞれ記入）</h3>'+[['learner','受講者'],['teacher','教育担当者']].map(([k,l])=>`<label>${l}のサイン</label><canvas data-signature="${k}" width="600" height="150" style="width:100%;height:150px;border:1px solid #9baec5;touch-action:none;background:white"></canvas><input type="hidden" name="${k}Ink" value="${esc(data[k+'Ink']||'')}"><input type="hidden" name="${k}SignedAt" value="${esc(data[k+'SignedAt']||'')}"><button type="button" class="secondary" data-clear-sign="${k}">このサインを書き直す</button>`).join('');f.querySelector('#safetySaveState').before(pads);
 for(const canvas of pads.querySelectorAll('canvas')){const key=canvas.dataset.signature,ctx=canvas.getContext('2d');ctx.lineWidth=2.5;ctx.lineCap='round';let drawing=false;const ink=data[key+'Ink'];if(ink&&/^data:image\/png;base64,/.test(ink)){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,600,150);img.src=ink}const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*600/r.width,(e.clientY-r.top)*150/r.height]};canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e))};canvas.onpointermove=e=>{if(drawing){ctx.lineTo(...point(e));ctx.stroke()}};canvas.onpointerup=()=>{if(!drawing)return;drawing=false;f.elements[key+'Ink'].value=canvas.toDataURL('image/png');f.elements[key+'SignedAt'].value=new Date().toISOString();persist()};pads.querySelector('[data-clear-sign='+key+']').onclick=()=>{ctx.clearRect(0,0,600,150);f.elements[key+'Ink'].value='';f.elements[key+'SignedAt'].value='';persist()}}
 }
 let saving=Promise.resolve();const persist=()=>{const value={id:recordId,kind,site:String(sid||''),data:collect(f),updatedAt:new Date().toISOString()};saving=saving.catch(()=>{}).then(()=>navigator.locks.request(DRAFT,()=>{const rows=read(DRAFT);localStorage.setItem(DRAFT,JSON.stringify([...rows.filter(x=>x.id!==recordId),value]))}));saving.then(()=>{if($('safetySaveState'))$('safetySaveState').textContent='下書き保存済み '+new Date().toLocaleTimeString('ja-JP')}).catch(()=>{if($('safetyError'))$('safetyError').textContent='保存できません。画面を閉じずに容量を確認してください。'});return saving};f.oninput=e=>{invalidateConfirmations(f,e);persist()};f.onchange=e=>{invalidateConfirmations(f,e);persist()};f.addEventListener('safety-save',persist);
 if(kind==='ky'){$('addSafetyRisk').onclick=()=>{$('safetyRisks').insertAdjacentHTML('beforeend',riskRow({},f.querySelectorAll('.safety-risk').length));invalidateConfirmations(f);persist()};$('safetyRisks').onclick=e=>{if(e.target.matches('[data-remove-risk]')){e.target.closest('.safety-risk').remove();invalidateConfirmations(f);persist()}}}
 async function discard(){if(!confirm('今回の入力を保存せずに一覧へ戻りますか？開く前の下書きと確定済みの記録は残ります。'))return;try{await saving.catch(()=>{});closed=true;await navigator.locks.request(DRAFT,()=>{const rows=read(DRAFT).filter(x=>x.id!==recordId);if(draft)rows.push(draft);localStorage.setItem(DRAFT,JSON.stringify(rows))});closeModal();render()}catch(e){closed=false;$('safetyError').textContent=e.message}}
 $('safetyReset').onclick=discard;
 f.addEventListener('open-sample',async()=>{try{await persist();closed=true;closeModal();setTimeout(()=>safetyLoadSample(kind,sid),0)}catch{}});
 $('safetyBack').onclick=async()=>{try{await persist();closed=true;closeModal();render()}catch{}};
 const cancelHandler=e=>{e.preventDefault();$('safetyBack')?.click()};$('modal').addEventListener('cancel',cancelHandler);
 $('modal').addEventListener('close',()=>{$('modal').removeEventListener('cancel',cancelHandler);if(!closed&&f.isConnected)persist();},{once:true});
 f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('[type=submit]');button.disabled=true;try{const v=collect(f);for(const [k,l]of fieldsFor(kind).filter(([k])=>['date','recorder','person','title','event','work','leader'].includes(k)))if(!String(v[k]||'').trim())throw Error(l+'を記入してください。');if(!v.date||v.date>today())throw Error('実施日は今日以前にしてください。');
 if(['common','induction'].includes(kind)){if(!v.personKey)throw Error('現場メンバーから受講者を選んでください。');for(const k of ['teacher','version','learnerInk','teacherInk'])if(!String(v[k]||'').trim())throw Error('教育担当者・教材と、受講者・担当者それぞれのサインを記入してください。');if(v.checks.some(c=>c.result!=='説明・本人理解を確認'))throw Error('未確認・再説明の項目があります。下書きで残してください。');}
 if(kind==='ky'&&v.daily){validateDailyKy(v);}else if(kind==='ky'){if(v.decision!=='保留'&&(!v.attendees.length||v.attendees.some(p=>!p.confirmedAt)))throw Error('参加者全員が、自分の名前の欄で本人確認してください。');if(!v.risks.length||v.risks.some(r=>['speaker','hazard','measure','owner'].some(k=>!r[k]?.trim())))throw Error('発言者・危険・具体策・実施者をすべての行に記入してください。');if(v.decision!=='保留'&&(v.checks.some(c=>!['適合','対象外'].includes(c.result)||c.result==='対象外'&&!c.note.trim())||!v.leaderSign?.trim()||!v.evidence?.trim()||!v.decisionReason?.trim()))throw Error('開始・再開には確認項目、対象外理由、完了証拠、職長の記名と判断理由が必要です。');}
 await persist();await navigator.locks.request(KEY,()=>{const rows=read(KEY),current=rows.find(x=>x.id===recordId);if(JSON.stringify(current)!==JSON.stringify(prior))throw Error('他の画面で更新されました。下書きを確認してください。');const doc=read(DOCS).find(x=>x.id===v.document);const record={id:recordId,kind,site:String(sid||''),data:v,document:doc?{...doc}:null,updatedAt:new Date().toISOString(),revision:(prior?.revision||0)+1,history:prior?[...(prior.history||[]),{...prior,history:undefined}]:[],verification:'本人認証未連携・端末内の記名記録'};localStorage.setItem(KEY,JSON.stringify([...rows.filter(x=>x.id!==recordId),record]))});await navigator.locks.request(DRAFT,()=>localStorage.setItem(DRAFT,JSON.stringify(read(DRAFT).filter(x=>x.id!==recordId))));closed=true;closeModal();render();safetyOpen(recordId)
 }catch(err){$('safetyError').textContent=err.message}finally{button.disabled=false}};
};
window.safetyOpen=(id,revision)=>{const latest=read(KEY).find(x=>x.id===id),r=revision?(latest?.history||[]).find(x=>x.revision===revision):latest;if(!r)return;const d=defs[r.kind],v=r.data;if(v.daily){openDailyKy(r,latest);return;}show(`<div class="paper-preview-actions"><h2>${v.sample?'【テスト用】 ':''}${d.name} ／ 第${r.revision}版</h2><button class="primary" onclick="window.print()">印刷・PDF保存</button><button class="secondary" onclick="safetyForm('${r.kind}','${r.site}','${r.id}')">追記・改訂する</button><button class="secondary" onclick="closeModal()">戻る</button><p>${esc(r.verification)}</p>${(latest.history||[]).map(h=>`<button class="secondary" onclick="safetyOpen('${id}',${h.revision})">第${h.revision}版を見る</button>`).join('')}</div><article class="accident-paper safety-paper"><h1>${d.name}</h1><p>${esc(state.sites.find(s=>String(s.id)===r.site)?.name||'共通教育')} ／ ${esc(v.date)} ／ 第${r.revision}版</p><table>${fieldsFor(r.kind).filter(([k])=>!(['common','induction'].includes(r.kind)&&!v[k])&&!(k==='participants'&&v.attendees?.length)).map(([k,l])=>`<tr><th>${l}</th><td>${esc(v[k]||'未記入')}</td></tr>`).join('')}${v.decision?`<tr><th>職長の判断（記録）</th><td>${esc(v.decision)}</td></tr>`:''}</table>${v.attendees?.length?`<h2>参加者ごとの本人確認</h2><table><tr><th>氏名・会社・ID</th><th>確認日時</th></tr>${v.attendees.map(p=>`<tr><td>${esc(p.name)} ／ ${esc(p.company)} ／ ${esc(p.key)}</td><td>${p.confirmedAt?esc(new Date(p.confirmedAt).toLocaleString('ja-JP')):'未確認'}</td></tr>`).join('')}</table>`:''}${['learner','teacher'].filter(k=>/^data:image\/png;base64,/.test(v[k+'Ink']||'')).map(k=>`<section><h3>${k==='learner'?'受講者':'教育担当者'}のサイン</h3><img src="${esc(v[k+'Ink'])}" alt="手書きサイン" style="width:60%;max-height:100px;object-fit:contain"><p>${esc(v[k+'SignedAt'])}</p></section>`).join('')}${r.document?`<h2>教育資料</h2><p>${esc(r.document.name)} ／ ${esc(r.document.version)} ／ 資料ID ${esc(r.document.id)}</p>`:''}${v.checks?.length?`<h2>確認項目</h2><table>${v.checks.map(c=>`<tr><th>${esc(c.label)}</th><td>${esc(c.result)}</td><td>${esc(c.note)}</td></tr>`).join('')}</table>`:''}${v.risks?.length?`<h2>発言者ごとの危険・対策</h2><table class="safety-risk-print"><thead><tr><th>発言者</th><th>予測される危険</th><th>私たちはこうする</th><th>実施者</th><th>対策前<br>頻度＋重篤度</th><th>対策後<br>頻度＋重篤度</th></tr></thead><tbody>${v.risks.map(x=>`<tr><td>${esc(x.speaker)}</td><td>${esc(x.hazard)}</td><td>${esc(x.measure)}</td><td>${esc(x.owner)}</td><td>${x.frequency&&x.severity?`${x.frequency}＋${x.severity}＝${Number(x.frequency)+Number(x.severity)}`:'未評価'}</td><td>${x.afterFrequency&&x.afterSeverity?`${x.afterFrequency}＋${x.afterSeverity}＝${Number(x.afterFrequency)+Number(x.afterSeverity)}`:'未評価'}</td></tr>`).join('')}</tbody></table>`:''}<footer>記録ID ${esc(r.id)} ／ ${esc(new Date(r.updatedAt).toLocaleString('ja-JP'))}<br>${esc(r.verification)}</footer></article>`);$('modal').classList.add('paper-preview-dialog');$('modal').addEventListener('close',()=>$('modal').classList.remove('paper-preview-dialog'),{once:true})};
window.safetyList=(sid,kinds)=>{const rs=read(KEY).filter(r=>String(r.site)===String(sid)&&kinds.includes(r.kind)),ds=read(DRAFT).filter(r=>String(r.site)===String(sid)&&kinds.includes(r.kind));return `<div class="safety-actions">${kinds.includes('ky')?`<button class="secondary" onclick="safetyLoadSample('ky','${sid}')">テスト用KY・3人の確認を試す</button><button class="secondary" onclick="safetyPrintSample(10)">10人の印刷プレビュー</button>`:''}${kinds.map(k=>`<button class="primary" onclick="safetyForm('${k}','${sid}')">＋ ${defs[k].name}</button>`).join('')}</div><p>下書きは途中で閉じても残ります。確定後の改訂は版ごとに履歴を保存します。</p><div class="work-list">${ds.map(r=>`<button class="work-item" onclick="safetyForm('${r.kind}','${sid}','${r.id}')"><strong>${r.data.sample?'【テスト用】 ':''}下書き ／ ${defs[r.kind].name}</strong><p>${esc(r.data.date)} ${esc(r.data.person||r.data.title||r.data.work||'')}</p></button>`).join('')}${rs.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(r=>`<button class="work-item" onclick="safetyOpen('${r.id}')"><strong>${r.data.sample?'【テスト用】 ':''}${defs[r.kind].name} ／ 第${r.revision}版</strong><p>${esc(r.data.date)} ${esc(r.data.person||r.data.title||r.data.work||'')}</p><p>${esc(r.data.decision||'記録済み')} ／ 内容・印刷を見る</p></button>`).join('')||'<p>確定した記録はまだありません。</p>'}</div>`};
window.safetyDocumentForm=sid=>{show(`<h2>教育資料・必要書類を追加</h2><form id="safetyDocument"><label>資料名<input name="name" required></label><label>版（例：2026年9月 第1版）<input name="version" required></label><label>ファイル<input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" required></label><p>更新版は新しい資料として追加します。過去の受講記録は当時の版を保持します。</p><p id="documentError" role="alert"></p>${foot('資料を保存')}</form>`);$('safetyDocument').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,file=f.elements.file.files[0];if(!mediaFileValid(file))throw Error('対応ファイルを25MB以内で選んでください。');const id=crypto.randomUUID();await storeFile(id,file);await navigator.locks.request(DOCS,()=>localStorage.setItem(DOCS,JSON.stringify([...read(DOCS),{id,site:String(sid||''),name:f.elements.name.value.trim(),version:f.elements.version.value.trim(),filename:file.name,at:new Date().toISOString()}])));closeModal();render()}catch(err){$('documentError').textContent=err.message}}};
window.safetyEducationStatus=async sid=>{const el=$('educationStatus');if(!el)return;el.textContent='メンバーと教育記録を確認中…';try{await refreshSitePeople();const people=siteResolvedMembers(sid),records=read(KEY);el.innerHTML='<table class="table"><thead><tr><th>氏名・ID</th><th>共通教育</th><th>現場初回教育</th></tr></thead><tbody>'+people.map(p=>{const cell=k=>{const r=records.filter(r=>r.kind===k&&r.data.personKey===p.type+':'+p.id&&(k==='common'||String(r.site)===String(sid))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];return r?'<button class="secondary" onclick="safetyOpen(\''+r.id+'\')">'+esc(r.data.date)+' ／ '+esc(r.data.version)+' 記録あり</button>':'記録なし'};return '<tr><th>'+esc(p.name)+' ／ '+esc(p.code||p.id)+'</th><td>'+cell('common')+'</td><td>'+cell('induction')+'</td></tr>'}).join('')+'</tbody></table><p>この端末の記録との照合です。「記録あり」は本人認証済み・有効期限内の受講を保証する表示ではありません。</p>'}catch(e){el.textContent=e.message}};
window.safetyDocuments=sid=>`<section class="panel"><div class="row between"><h2>安全教育・必要書類</h2><button class="primary" onclick="safetyDocumentForm('${sid||''}')">＋ 資料・改訂版を追加</button></div><a class="work-item" href="safety-guide.pdf#page=58" target="_blank" rel="noopener"><h3>安全教育と業務アプリ 統合ガイド</h3><p>今回受領した資料 ／ 58ページから事故分析・安全教育 ／ 運用案を含む参考資料</p></a>${read(DOCS).filter(r=>!r.site||String(r.site)===String(sid)).map(r=>`<button class="work-item" onclick="mediaOpen('${r.id}')"><h3>${esc(r.name)}</h3><p>${esc(r.version)} ／ ${esc(r.filename)}</p></button>`).join('')}</section>`;
window.addEventListener('DOMContentLoaded',()=>{const nav=document.querySelector('aside nav'),b=document.createElement('button');b.textContent='安全教育・書類';b.dataset.nav='safetyLibrary';b.onclick=()=>navigate('safetyLibrary');nav.append(b);const prior=render;render=function(){if(page==='safetyLibrary'){page='sites';try{prior()}finally{page='safetyLibrary'}$('app').innerHTML=heading('SAFETY LIBRARY','安全教育・書類','共通教材と現場で使う様式を、いつでも確認できます。')+safetyDocuments('');document.querySelectorAll('aside nav button').forEach(n=>n.classList.toggle('active',n===b))}else prior();nav.querySelector('[data-nav=subcontractors]')?.after(b);if(page!=='detail')return;const tabs=document.querySelector('#app .tabs');if(!tabs)return;for(const name of ['安全教育']){const t=document.createElement('button');t.textContent=name;t.classList.toggle('active',tab===name);t.onclick=()=>goTab(siteId,name);tabs.append(t)}if(['安全教育','ヒヤリハット','KY'].includes(tab)){while(tabs.nextSibling)tabs.nextSibling.remove();tabs.insertAdjacentHTML('afterend',tab==='安全教育'?safetyDocuments(siteId)+`<section class="panel"><h2>メンバーごとの教育記録</h2><button class="secondary" onclick="safetyEducationStatus('${siteId}')">ポータルのメンバーと照合する</button><div id="educationStatus"></div></section>`+safetyList(siteId,['common','induction']):tab==='ヒヤリハット'?`<h2>終業時のヒヤリハット共有</h2>`+safetyList(siteId,['near']):`<h2>毎日のKY・再KY・体調確認</h2>`+safetyList(siteId,['ky'])+`<details class="panel"><summary>以前のヒヤリハット・体調記録</summary>${safetyList(siteId,['near','heat'])}</details>`+`<details class="panel"><summary>以前の添付式KY記録を見る</summary>${renderKy(siteId)}</details>`)}};render()});
})();



window.safetyPrintDocument=async(download=false)=>{const el=document.querySelector('.submission-pages');if(!el)return;const win=download?null:window.open('about:blank','_blank');try{const css=await (await fetch('safety-records.css')).text();const html='<!doctype html><html lang="ja"><meta charset="utf-8"><title>現場安全記録・印刷</title><style>'+css+'\nbody{margin:0;background:#e6ebf1}.print-controls{padding:16px;background:white} @page{size:A4 landscape;margin:5mm}@media print{.print-controls{display:none!important}body{background:white}.submission-pages{display:block!important}} </style><div class="print-controls"><button onclick="window.print()">印刷・PDF保存</button><p>印刷が開かない場合は、このファイルをChromeまたはEdgeで開き、Ctrl＋Pで印刷してください。</p></div>'+el.outerHTML+'</html>';if(win){win.document.open();win.document.write(html);win.document.close();win.focus();document.getElementById('safetyPrintMessage').textContent='別画面を開きました。上の「印刷・PDF保存」を押してください。';}else{const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='現場安全記録_印刷用.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);document.getElementById('safetyPrintMessage').textContent='保存したファイルをChromeまたはEdgeで開くと印刷できます。';}}catch(e){win?.close();document.getElementById('safetyPrintMessage').textContent='印刷用画面を作成できませんでした。'+e.message}};
