(function(){
'use strict';
// Load after member-scope and shared-site-profiles. Server data stays in memory.
const cache=new Map(),resolved=new Map(),pending=new Map(),errors=new Map();let generation=0;
const areas=['概要','関連','工程表','タスク','報告','写真','資料','KY','資材台帳','チャット','手直し案件','入場履歴','事故報告','安全教育'];
const identity=()=>portalSession.connected()?[(portalSession.identity()?.kind||'employee'),portalSession.identity()?.code].join(':'):'';
const employee=()=>identity().startsWith('employee:');
const key=sid=>sitePortalSiteKey(sid);
window.siteMemberRules=sid=>cache.get(key(sid))||[];
window.siteResolvedMembers=sid=>resolved.get(key(sid))||[];
window.siteMembersRefresh=async sid=>{const k=key(sid),a=identity(),g=generation;if(!employee())throw Error('この現場の職長・リーダーのみ名簿を確認できます');if(pending.has(k))return pending.get(k);const promise=(async()=>{let rows=[],cursor='';for(let i=0;i<100;i++){const page=await portalSession.call('membersList',{p_site_key:k,p_after_key:cursor});if(a!==identity()||g!==generation)return [];if(!Array.isArray(page))throw Error('メンバーの取得結果を確認できません');rows.push(...page);if(page.length<100){let people=[],after='';for(let j=0;j<100;j++){const part=await portalSession.call('membersResolved',{p_site_key:k,p_after_key:after});if(a!==identity()||g!==generation)return [];if(!Array.isArray(part))throw Error('参加者の取得結果を確認できません');people.push(...part);if(part.length<100)break;const last=part.at(-1)?.key;if(!last||last<=after||j===99)throw Error('参加者の件数または読込位置を確認できません');after=last}cache.set(k,rows);resolved.set(k,people);errors.delete(k);return rows}const next=page.at(-1)?.key;if(!next||next<=cursor)throw Error('名簿の読込位置を確認できません');cursor=next}throw Error('名簿の件数が多いため取得できません')})().catch(e=>{if(a===identity()&&g===generation){cache.delete(k);resolved.delete(k);errors.set(k,e.message)}throw e}).finally(()=>{if(pending.get(k)===promise)pending.delete(k)});pending.set(k,promise);return promise};
window.refreshSitePeople=async()=>({employees:await siteMembersRefresh(siteId).then(()=>siteResolvedMembers(siteId).filter(x=>x.type==='employee')),companies:siteMemberRules(siteId).filter(x=>x.type==='company'),workers:siteResolvedMembers(siteId).filter(x=>x.type==='worker')});
function controls(r){return `<label>閲覧<select name="view"><option value="true" ${r.view?'selected':''}>許可する</option><option value="false" ${!r.view?'selected':''}>参加のみ・閲覧不可</option></select></label><fieldset><legend>閲覧できる項目</legend>${areas.map(x=>`<label><input type="checkbox" name="section" value="${x}" ${(r.sections||[]).includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset>${r.type==='employee'?`<label>役割<select name="role">${[['member','作業メンバー'],['foreman','職長'],['leader','リーダー']].map(([v,t])=>`<option value="${v}" ${r.role===v?'selected':''}>${t}</option>`).join('')}</select></label><label><input type="checkbox" name="educationTarget" ${r.educationTarget?'checked':''}>安全教育の対象</label>`:'<p>会社全員への設定より、個人の設定（閲覧不可を含む）が優先します。</p>'}`}
function edit(sid,r){const actor=identity(),g=generation;show(`<h2>${esc(r.name)}の現場設定</h2><form id="sharedMemberEdit">${controls(r)}<label>入場予定日<input type="date" name="entryDate" value="${esc(r.entryDate||'')}"></label>${r.type!=='employee'?`<label><input type="checkbox" name="educationTarget" ${r.educationTarget?'checked':''}>安全教育の対象</label>`:''}<p role="alert"></p><button type="button" class="secondary" onclick="closeModal()">保存せず戻る</button><button type="submit">設定を保存</button></form>`);const f=$('sharedMemberEdit');f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');if(b.disabled)return;b.disabled=true;try{if(actor!==identity()||g!==generation)throw Error('ログインが変わりました。開き直してください');const view=f.elements.view.value==='true',sections=view?[...f.querySelectorAll('[name=section]:checked')].map(x=>x.value):[];if(view&&!sections.length)throw Error('閲覧する項目を選んでください');await sitePortal.memberSave(sid,{...r,view,sections,scope:'selected',role:f.elements.role?.value||'member',educationTarget:!!f.elements.educationTarget?.checked,entryDate:f.elements.entryDate.value});if(actor!==identity()||g!==generation)return;await siteMembersRefresh(sid);if(f.isConnected){closeModal();render()}}catch(err){if(f.isConnected)f.querySelector('[role=alert]').textContent=err.message+' 入力内容は残しています。'}finally{b.disabled=false}}}
window.siteMemberScopeEdit=(sid,type,id)=>{const r=siteMemberRules(sid).find(x=>x.type===type&&String(x.id)===String(id));if(r)edit(sid,r)};
window.siteMemberForm=sid=>{const actor=identity(),g=generation;show('<h2>ポータルからメンバーを選ぶ</h2><form id="sharedMemberSearch"><label>種類<select name="kind"><option value="employee">社員</option><option value="company">会社全員</option><option value="worker">外注個人</option></select></label><label>氏名・会社名・ID<input name="query"></label><button type="submit">検索</button></form><p id="sharedMemberSearchError" role="alert"></p><div id="sharedMemberCandidates"></div><button id="sharedMemberNext" hidden>次の候補</button><button class="secondary" onclick="closeModal()">戻る</button>');const f=$('sharedMemberSearch'),list=$('sharedMemberCandidates'),next=$('sharedMemberNext');let cursor=0,request=0;async function search(more){const ticket=++request,kind=f.elements.kind.value,q=f.elements.query.value.trim();if(!more)cursor=0;next.hidden=true;try{let rows;if(kind==='employee'){const d=await portalSession.call('members',{p_site_key:key(sid)});rows=(d.employees||[]).map(r=>({...r,type:'employee',id:String(r.id)})).filter(r=>(r.name+' '+r.id).includes(q));}else{const data=await portalSession.call('externalCandidates',{p_site_key:key(sid),p_kind:kind,p_query:q,p_after_id:cursor,p_limit:50});rows=data.map(r=>({...r,id:String(r.id),type:kind,company:r.company_name||r.name,companyId:String(r.company_id||r.id)}));}if(!f.isConnected||actor!==identity()||g!==generation||ticket!==request)return;if(kind!=='employee'){next.hidden=rows.length<50;cursor=Number(rows.at(-1)?.id||cursor)}list.replaceChildren();for(const r of rows){const b=document.createElement('button');b.className='work-item';b.textContent=(r.type==='company'?'会社全員：':'')+r.name+' ／ ID '+r.id+(r.company?' ／ '+r.company:'');b.onclick=()=>edit(sid,{...r,view:true,sections:['安全教育'],role:'member',educationTarget:r.type==='employee'});list.append(b)}if(!rows.length)list.textContent='該当する候補はありません';$('sharedMemberSearchError').textContent=''}catch(e){if(f.isConnected&&ticket===request)$('sharedMemberSearchError').textContent=e.message}}f.onsubmit=e=>{e.preventDefault();search(false)};f.elements.kind.onchange=()=>search(false);next.onclick=()=>search(true);search(false)};
window.siteMemberById=window.siteMemberForm;
window.siteMemberRemove=async(sid,type,id)=>{const r=siteMemberRules(sid).find(x=>x.type===type&&String(x.id)===String(id)),a=identity(),g=generation;if(!r)return;try{await sitePortal.memberSave(sid,r,true);if(a!==identity()||g!==generation)return;await siteMembersRefresh(sid);render()}catch(e){notify(e.message)}};
window.addEventListener('portal-session-ready',()=>{generation++;cache.clear();resolved.clear();errors.clear();pending.clear();if($('sharedMemberEdit')||$('sharedMemberSearch'))closeModal();render()});
window.addEventListener('DOMContentLoaded',()=>{const previous=render;render=function(){previous();if(page!=='detail'||tab!=='メンバー')return;const sid=siteId,k=key(sid),tabs=document.querySelector('#app .tabs');if(!tabs)return;let panel=$('sharedMembersPanel');if(!panel){panel=document.createElement('section');panel.id='sharedMembersPanel';panel.className='panel';tabs.after(panel)}
 // Replace obsolete local rule panels, retain separate education/sheet status panels.
 $('scopePanel')?.remove();for(const p of [...document.querySelectorAll('#app > .panel')])if(p!==panel&&p.querySelector('h2')?.textContent==='現場メンバー')p.remove();
 panel.innerHTML='<h2>現場メンバー</h2><p>会社全員、社員、外注個人を追加できます。個人の閲覧不可は会社全員への許可より優先します。</p>';const status=document.createElement('p');status.textContent=errors.get(k)||(!cache.has(k)?'共有メンバーを確認中…':'');panel.append(status);const reload=document.createElement('button');reload.className='secondary';reload.textContent='共有メンバーを読み直す';reload.onclick=async()=>{try{await siteMembersRefresh(sid)}catch{}if(page==='detail'&&String(siteId)===String(sid)&&tab==='メンバー')render()};panel.append(reload);if(cache.has(k)){const add=document.createElement('button');add.textContent='＋ ポータルから追加';add.onclick=()=>siteMemberForm(sid);panel.append(add);for(const r of siteMemberRules(sid)){const box=document.createElement('article');box.className='work-item';box.innerHTML=`<h3>${esc(r.name)}${r.type==='company'?'（会社全員）':''}</h3><p>ID ${esc(r.id)} ／ ${esc(r.company||'')}</p><p>${r.view?esc((r.sections||[]).join('・')):'参加のみ・閲覧不可'}</p>`;const b=document.createElement('button');b.textContent='設定を変更';b.onclick=()=>edit(sid,r);box.append(b);panel.append(box)}}else if(!errors.has(k)&&!pending.has(k))siteMembersRefresh(sid).then(()=>{if(page==='detail'&&String(siteId)===String(sid)&&tab==='メンバー')render()}).catch(()=>{if(page==='detail'&&String(siteId)===String(sid)&&tab==='メンバー')render()});};window.appSharedFeatures={...window.appSharedFeatures,'メンバー':true};render()});
})();
