(function(){
const KEY='jinshou-site-members-v1',SYNC='jinshou-site-sync-v1';let directory=null;
const read=k=>JSON.parse(localStorage.getItem(k)||'{}');
async function write(k,id,value){return navigator.locks.request(k,()=>{const all=read(k);all[id]=value;localStorage.setItem(k,JSON.stringify(all))})}
window.siteMemberRules=sid=>read(KEY)[sid]||[];
// Individual rules override company rules, including an explicit view denial.
window.siteMemberAccess=(sid,person)=>{const rules=siteMemberRules(sid),own=rules.find(r=>r.type===person.type&&r.id===String(person.id)),group=person.type==='worker'?rules.find(r=>r.type==='company'&&r.id===String(person.companyId)):null;return own?own.view===true:group?.view===true};
window.siteResolvedMembers=sid=>{const rules=siteMemberRules(sid),people=directory?[...directory.employees,...directory.workers]:rules.filter(r=>r.type!=='company');return people.filter(p=>rules.some(r=>r.type===p.type&&r.id===p.id||p.type==='worker'&&r.type==='company'&&r.id===p.companyId)).map(p=>({...p,view:siteMemberAccess(sid,p)}))};
window.refreshSitePeople=async()=>{directory=await sitePortal.members();return directory};
window.siteMemberForm=async sid=>{show('<h2>ポータルのメンバーを確認中…</h2><button class="secondary" onclick="closeModal()">戻る</button>');try{await refreshSitePeople();const candidates=[...directory.employees,...directory.companies,...directory.workers];show(`<h2>現場メンバーを追加</h2><p>会社を追加すると、その会社の在籍者が対象です。個人の設定を追加した場合は、会社の設定より優先します。</p><form id="memberRule"><label>氏名・会社名・IDを検索<input id="memberQuery"></label><label>対象<select name="who" required>${candidates.map((r,i)=>`<option value="${i}">${esc(r.type==='company'?'会社全員：':r.type==='employee'?'社員：':'外注個人：')}${esc(r.name)} ／ ID ${esc(r.type==='worker'?(r.code||r.id):r.id)} ${esc(r.company||'')}</option>`).join('')}</select></label><label>閲覧設定<select name="view"><option value="true">メンバーに追加し、閲覧を許可する</option><option value="false">メンバーに追加するが、閲覧は許可しない</option></select></label><p class="notice">保存するとポータルの社員メンバーと教育管理の役割に反映します。職長・リーダーはこの現場の受講状況を確認できます。</p><p id="memberError" role="alert"></p>${foot('メンバーを保存')}</form>`);$('memberQuery').oninput=e=>{const q=e.target.value.toLowerCase();for(const o of $('memberRule').elements.who.options)o.hidden=!o.textContent.toLowerCase().includes(q)};$('memberRule').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,r=candidates[Number(f.elements.who.value)];if(!r)throw Error('対象を選択してください');const values={...r,view:f.elements.view.value==='true',...(f.scopeValues?f.scopeValues():{})};await sitePortal.memberSave(sid,values);await navigator.locks.request(KEY,()=>{const all=read(KEY),rules=all[sid]||[];all[sid]=[...rules.filter(x=>!(x.type===r.type&&x.id===r.id)),{...r,view:f.elements.view.value==='true',...(f.scopeValues?f.scopeValues():{}),updatedAt:new Date().toISOString()}];localStorage.setItem(KEY,JSON.stringify(all))});closeModal();render()}catch(err){$('memberError').textContent=err.message}}}catch(err){show(`<h2>ポータルのログインを確認してください</h2><p>${esc(err.message)}</p><a class="primary" href="https://shota-1003.github.io/jinshou-employee-app/" target="_blank" rel="noopener">ポータルを開く</a><button class="secondary" onclick="closeModal()">戻る</button>`)}};
window.siteMemberRemove=async(sid,type,id)=>{const r=siteMemberRules(sid).find(x=>x.type===type&&x.id===id);try{if(r&&!r.sample)await sitePortal.memberSave(sid,r,true)}catch(e){notify(e.message);return}await navigator.locks.request(KEY,()=>{const all=read(KEY);all[sid]=(all[sid]||[]).filter(r=>!(r.type===type&&r.id===id));localStorage.setItem(KEY,JSON.stringify(all))});render()};
const syncing=new Map();let syncEpoch=0;window.siteSyncSessionEpoch=()=>syncEpoch;
const syncActor=()=>window.portalSession?.connected()&&portalSession.identity()?JSON.stringify([portalSession.identity().kind||'employee',portalSession.identity().code||'']):'';
window.siteSyncNow=sid=>{
 const id=String(sid),requestedBy=syncActor(),requestedEpoch=syncEpoch;if(!requestedBy)return Promise.resolve();if(syncing.has(id))return syncing.get(id);
 const job=navigator.locks.request(SYNC+':'+id,async()=>{
  if(syncEpoch!==requestedEpoch||syncActor()!==requestedBy)return;
  const s=state.sites.find(x=>String(x.id)===id),actor=requestedBy,epoch=requestedEpoch;if(!s)return;
  const old=read(SYNC)[id]||{};if(old.portalId)return old;
  if(old.owner&&old.owner!==actor){notify('この現場の登録は別の本人が開始しました。管理者に確認してください。');return old}
  if(old.attempted||old.pending&&!old.owner){notify('以前の登録結果を確認できません。重複登録を避けるため管理者に確認してください。');return old}
  await write(SYNC,id,{...old,owner:actor,status:'ポータルに反映中',pending:true,attempted:true});
  try{
   if(syncEpoch!==epoch||syncActor()!==actor)return read(SYNC)[id];
   const rows=await sitePortal.registerSite(s);if(syncEpoch!==epoch||syncActor()!==actor)return read(SYNC)[id];const r=rows?.[0];
   if(!r?.site_id){if(!r?.similar_candidates?.length)throw Error('登録結果を確認できませんでした。');await write(SYNC,id,{...old,owner:actor,attempted:true,status:'似た現場があります。登録先を確認してください',pending:false,candidates:r.similar_candidates});notify('似た現場があります。メンバー欄で登録先を確認してください。')}
   else{await write(SYNC,id,{...old,owner:actor,attempted:true,portalId:String(r.site_id),status:'ポータル登録済み',pending:false,at:new Date().toISOString(),sheet:'反映未確認'});notify('現場マスターに反映しました。スプレッドシートへの反映は確認待ちです。')}
  }catch(err){if(syncEpoch===epoch&&syncActor()===actor){await write(SYNC,id,{...old,owner:actor,attempted:true,status:'登録結果を確認できません。重複登録を避けるため管理者に確認してください。',pending:false});notify('登録結果を確認できません。重複登録を避けるため管理者に確認してください。')}}
  if(page==='detail'&&String(siteId)===id&&tab==='メンバー'&&!$('modal').open)render();
  return read(SYNC)[id];
 });syncing.set(id,job);job.finally(()=>syncing.delete(id)).catch(()=>{});return job;
};
window.addEventListener('portal-session-ready',()=>{syncEpoch++});
window.siteSyncLink=async(sid,pid)=>{const s=read(SYNC)[sid];if(!s?.owner||s.owner!==syncActor()||!s.candidates?.some(c=>String(c.site_id)===String(pid)))return;await write(SYNC,sid,{...s,portalId:String(pid),status:'既存のポータル現場に紐付け済み',pending:false,at:new Date().toISOString(),sheet:'反映未確認'});render()};
function panel(sid){const rows=siteMemberRules(sid),shared=window.siteSharedProfilesSnapshot?.().rows.find(r=>String(r.localId)===String(sid)),sync=shared?{portalId:shared.portal_site_id,status:shared.portal_site_id?'ポータル登録済み':'ポータル現場IDを確認中',sheet:'反映状況を確認中'}:read(SYNC)[sid];return `<section class="panel"><div class="row between"><h2>現場メンバー</h2><button class="primary" onclick="siteMemberForm('${sid}')">＋ ポータルから追加</button></div><p>社員・外注個人・外注会社を選べます。個人の「閲覧不可」は会社全員への許可より優先します。</p><p class="notice">社員の教育管理権限はポータルに連携します。教育以外の項目別閲覧制限は引き続き設定案です。</p><div class="work-list">${rows.map(r=>`<div class="work-item"><h3>${esc(r.name)}${r.type==='company'?'（会社全員）':''}</h3><p>${esc(r.company||'')} ／ ${r.type==='company'?'会社ID':'ポータルID'}：${esc(r.code||r.id)}</p><strong>${r.view?'閲覧許可の設定案':'参加のみ・閲覧不可の設定案'}</strong><p><button class="secondary" onclick="siteMemberRemove('${sid}','${r.type}','${esc(r.id)}')">この設定を外す</button></p></div>`).join('')||'<p>メンバー未設定です。</p>'}</div></section><section class="panel"><h2>現場マスター連携</h2><p>${esc(sync?.status||'未連携')}</p>${sync?.portalId?`<p>ポータル現場ID：${esc(sync.portalId)} ／ スプレッドシート：${esc(sync.sheet)}</p>`:shared?`<p>ポータル現場IDを確認中です。管理者に連絡してください。</p>`:`<button class="primary" onclick="siteSyncNow('${sid}')">ポータルへ反映・再試行</button>`}${(sync?.candidates||[]).map(c=>`<button class="work-item" onclick="siteSyncLink('${sid}','${c.site_id}')">${esc(c.site_name)} ／ ID ${c.site_id} に紐付ける</button>`).join('')}<p>ポータルに登録された現場は、既存の日報シートへの追加処理の対象になります。シートへの反映完了はまだこの画面から確認できません。</p></section>`}
window.addEventListener('DOMContentLoaded',()=>{const oldForm=siteForm;siteForm=function(id){oldForm(id);const f=$('siteForm'),submit=f.onsubmit,existing=new Set(state.sites.map(s=>s.id));if(!id)f.insertAdjacentHTML('afterbegin','<p class="notice">登録後、ポータルの現場マスターへの反映を試みます。本人確認待ち・類似現場・通信エラーは現場の「メンバー」に残します。</p>');f.onsubmit=async e=>{const actor=syncActor(),epoch=syncEpoch;await submit(e);if(epoch!==syncEpoch||actor!==syncActor())return;if(!id){const s=state.sites.find(s=>!existing.has(s.id));if(s){await siteSyncNow(s.id);if(epoch===syncEpoch&&actor===syncActor())goTab(s.id,'メンバー')}}}};const prior=render;render=function(){prior();if(page!=='detail')return;const tabs=document.querySelector('#app .tabs');if(!tabs)return;const b=document.createElement('button');b.textContent='メンバー';b.classList.toggle('active',tab==='メンバー');b.onclick=()=>goTab(siteId,'メンバー');tabs.children[0]?.after(b);if(tab==='メンバー'){while(tabs.nextSibling)tabs.nextSibling.remove();tabs.insertAdjacentHTML('afterend',panel(siteId))}};render()});
})();
