(function(){'use strict';
let generation=0,request=0,currentSite='';
const active=()=>['employees','subcontractors'].includes(page);
const owner=()=>portalSession.connected()?JSON.stringify(portalSession.identity()):'';
const employee=()=>portalSession.connected()&&(portalSession.identity()?.kind||'employee')==='employee';
const sites=()=>window.siteSharedProfilesSnapshot?.().rows.filter(x=>x.can_manage_members)||[];
function checked(a,g,t,host){if(a!==owner()||g!==generation||t!==request||!host.isConnected)throw Error('ログインまたは表示条件が変わりました')}
function screen(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));
 const host=document.createElement('section');host.className='panel';host.id='sharedWorkforce';
 $('app').replaceChildren(host);if(!employee()){host.innerHTML='<h1>'+ (page==='employees'?'社員管理':'外注管理')+'</h1><p>社員の本人ログインと管理権限が必要です。</p>';return}
 const choices=sites();if(!choices.some(s=>s.site_key===currentSite))currentSite=choices[0]?.site_key||'';
 host.innerHTML='<h1>'+(page==='employees'?'社員管理':'外注管理')+'</h1><p>ポータルの登録情報を表示します。現場へ追加するときと同じIDです。</p><form id="workforceSearch"><label>管理する現場<select name="site"><option value="">現場を選択</option>'+choices.map(s=>'<option value="'+esc(s.site_key)+'" '+(s.site_key===currentSite?'selected':'')+'>'+esc(s.name||s.profile?.name)+'</option>').join('')+'</select></label>'+(page==='subcontractors'?'<label>種類<select name="kind"><option value="company">外注会社</option><option value="worker">外注個人</option></select></label>':'<input type="hidden" name="kind" value="employee">')+'<label>氏名・会社名・ID<input name="query" maxlength="100"></label><label><input type="checkbox" name="onlyMembers">この現場に登録されたメンバーだけ</label><button type="submit">検索・再読み込み</button></form><p role="status"></p><div data-results></div><button data-next hidden>次の50件</button><p>氏名・所属・在籍状況の変更は、ポータルの社員管理・外注管理で行ってください。変更後、この一覧を再読み込みします。</p><a href="https://shota-1003.github.io/jinshou-employee-app/" target="_blank" rel="noopener">ポータルの管理画面へ</a>';
 const f=$('workforceSearch'),status=host.querySelector('[role=status]'),result=host.querySelector('[data-results]'),next=host.querySelector('[data-next]');let cursor=0,memberRows=[],lastFilter='';
 async function search(more=false){const a=owner(),g=generation,t=++request,kind=f.elements.kind.value,k=f.elements.site.value,q=f.elements.query.value.trim(),only=f.elements.onlyMembers.checked;currentSite=k;next.hidden=true;const filter=JSON.stringify([k,kind,q,only]);if(!more||filter!==lastFilter)cursor=0;lastFilter=filter;result.replaceChildren();if(!k){status.textContent='管理権限のある現場を選んでください。';return}status.textContent='ポータルの登録情報を確認中…';try{let rows=[];
 if(only){memberRows=[];let after='';for(let i=0;i<100;i++){const part=await portalSession.call('membersList',{p_site_key:k,p_after_key:after});checked(a,g,t,host);if(!Array.isArray(part))throw Error('名簿の形式を確認できません');memberRows.push(...part);if(part.length<100)break;const n=part.at(-1)?.key;if(!n||n<=after||i===99)throw Error('名簿の読込位置を確認できません');after=n}rows=memberRows.filter(r=>r.type===kind&&[r.name,r.company,r.id].join(' ').toLowerCase().includes(q.toLowerCase()));
 }else if(kind==='employee'){const d=await portalSession.call('members',{p_site_key:k});checked(a,g,t,host);if(!Array.isArray(d.employees))throw Error('社員の取得結果を確認できません');rows=d.employees.map(r=>({...r,type:'employee',id:String(r.id),company:r.company||'迅翔興業'})).filter(r=>[r.name,r.company,r.id].join(' ').toLowerCase().includes(q.toLowerCase()));
 }else{rows=await portalSession.call('externalCandidates',{p_site_key:k,p_kind:kind,p_query:q,p_after_id:cursor,p_limit:50});checked(a,g,t,host);if(!Array.isArray(rows))throw Error('外注の取得結果を確認できません');next.hidden=rows.length<50;if(rows.length===50){const n=Number(rows.at(-1).id);if(!Number.isSafeInteger(n)||n<=cursor)throw Error('読込位置を確認できません');cursor=n}rows=rows.map(r=>({...r,type:kind,id:String(r.id),company:r.company_name||r.company||r.name,companyId:String(r.company_id||r.companyId||r.id)}))}
 checked(a,g,t,host);status.textContent=rows.length+'件 ／ ポータルの登録情報';const table=document.createElement('table');table.className='table';table.innerHTML='<thead><tr><th>氏名・会社名</th><th>所属会社</th><th>メンバー登録ID</th><th>会社ID</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+esc(r.company||'')+'</td><td>'+esc(r.type+':'+r.id)+'</td><td>'+esc(r.type==='company'?r.id:r.companyId||r.company_id||'—')+'</td></tr>').join('')+'</tbody>';result.append(table);if(!rows.length)result.insertAdjacentHTML('beforeend','<p>該当する登録はありません。</p>');
 }catch(e){if(a===owner()&&g===generation&&t===request&&host.isConnected){result.replaceChildren();next.hidden=true;status.textContent=e.message}}}
 f.onsubmit=e=>{e.preventDefault();search()};f.elements.site.onchange=()=>search();f.elements.kind.onchange=()=>search();f.elements.onlyMembers.onchange=()=>search();next.onclick=()=>search(true);search();
}
window.addEventListener('DOMContentLoaded',()=>{const previous=render;render=function(){if(active())screen();else previous()};portalDirectoryRefresh=()=>{if(active())screen()};portalDirectoryLogin=()=>notify('普段お使いのポータルへの本人ログインを確認してください。ここで別の暗証番号入力は不要です。');portalDirectoryDisconnect=()=>notify('この画面では接続解除しません。ログアウトはポータルで行ってください。');if(active())screen();window.appSharedFeatures={...window.appSharedFeatures,'employees':true,'subcontractors':true}});
window.addEventListener('portal-session-ready',()=>{generation++;request++;currentSite='';if(active())screen()});
window.sharedWorkforceAvailable=()=>employee()&&window.siteSharedProfilesSnapshot?.().ready===true&&sites().length>0;
})();

